// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file dsf_define_datatypes.cpp
 * This source file contains the implementation of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "dsf_define_datatypes.h"

#include "txcdr/Cdr.h"

#include <utility>


namespace DSF {

Timespec::Timespec()
{
}

Timespec::~Timespec()
{
}

Timespec::Timespec(
        const Timespec& x)
{
    m_tv_sec = x.m_tv_sec;
    m_tv_nsec = x.m_tv_nsec;
}

Timespec::Timespec(
        Timespec&& x) noexcept
{
    m_tv_sec = x.m_tv_sec;
    m_tv_nsec = x.m_tv_nsec;
}

Timespec& Timespec::operator =(
        const Timespec& x)
{

    m_tv_sec = x.m_tv_sec;
    m_tv_nsec = x.m_tv_nsec;
    return *this;
}

Timespec& Timespec::operator =(
        Timespec&& x) noexcept
{

    m_tv_sec = x.m_tv_sec;
    m_tv_nsec = x.m_tv_nsec;
    return *this;
}

bool Timespec::operator ==(
        const Timespec& x) const
{
    return (m_tv_sec == x.m_tv_sec &&
           m_tv_nsec == x.m_tv_nsec);
}

bool Timespec::operator !=(
        const Timespec& x) const
{
    return !(*this == x);
}

/*!
 * @brief This function sets a value in member tv_sec
 * @param _tv_sec New value for member tv_sec
 */
void Timespec::tv_sec(
        int32_t _tv_sec)
{
    m_tv_sec = _tv_sec;
}

/*!
 * @brief This function returns the value of member tv_sec
 * @return Value of member tv_sec
 */
int32_t Timespec::tv_sec() const
{
    return m_tv_sec;
}

/*!
 * @brief This function returns a reference to member tv_sec
 * @return Reference to member tv_sec
 */
int32_t& Timespec::tv_sec()
{
    return m_tv_sec;
}


/*!
 * @brief This function sets a value in member tv_nsec
 * @param _tv_nsec New value for member tv_nsec
 */
void Timespec::tv_nsec(
        uint32_t _tv_nsec)
{
    m_tv_nsec = _tv_nsec;
}

/*!
 * @brief This function returns the value of member tv_nsec
 * @return Value of member tv_nsec
 */
uint32_t Timespec::tv_nsec() const
{
    return m_tv_nsec;
}

/*!
 * @brief This function returns a reference to member tv_nsec
 * @return Reference to member tv_nsec
 */
uint32_t& Timespec::tv_nsec()
{
    return m_tv_nsec;
}


NamedValue::NamedValue()
{
}

NamedValue::~NamedValue()
{
}

NamedValue::NamedValue(
        const NamedValue& x)
{
    m_name = x.m_name;
    m_value = x.m_value;
}

NamedValue::NamedValue(
        NamedValue&& x) noexcept
{
    m_name = std::move(x.m_name);
    m_value = std::move(x.m_value);
}

NamedValue& NamedValue::operator =(
        const NamedValue& x)
{

    m_name = x.m_name;
    m_value = x.m_value;
    return *this;
}

NamedValue& NamedValue::operator =(
        NamedValue&& x) noexcept
{

    m_name = std::move(x.m_name);
    m_value = std::move(x.m_value);
    return *this;
}

bool NamedValue::operator ==(
        const NamedValue& x) const
{
    return (m_name == x.m_name &&
           m_value == x.m_value);
}

bool NamedValue::operator !=(
        const NamedValue& x) const
{
    return !(*this == x);
}

/*!
 * @brief This function copies the value in member name
 * @param _name New value to be copied in member name
 */
void NamedValue::name(
        const std::string& _name)
{
    m_name = _name;
}

/*!
 * @brief This function moves the value in member name
 * @param _name New value to be moved in member name
 */
void NamedValue::name(
        std::string&& _name)
{
    m_name = std::move(_name);
}

/*!
 * @brief This function returns a constant reference to member name
 * @return Constant reference to member name
 */
const std::string& NamedValue::name() const
{
    return m_name;
}

/*!
 * @brief This function returns a reference to member name
 * @return Reference to member name
 */
std::string& NamedValue::name()
{
    return m_name;
}


/*!
 * @brief This function copies the value in member value
 * @param _value New value to be copied in member value
 */
void NamedValue::value(
        const std::string& _value)
{
    m_value = _value;
}

/*!
 * @brief This function moves the value in member value
 * @param _value New value to be moved in member value
 */
void NamedValue::value(
        std::string&& _value)
{
    m_value = std::move(_value);
}

/*!
 * @brief This function returns a constant reference to member value
 * @return Constant reference to member value
 */
const std::string& NamedValue::value() const
{
    return m_value;
}

/*!
 * @brief This function returns a reference to member value
 * @return Reference to member value
 */
std::string& NamedValue::value()
{
    return m_value;
}


StructuredDataMapEntry::StructuredDataMapEntry()
{
}

StructuredDataMapEntry::~StructuredDataMapEntry()
{
}

StructuredDataMapEntry::StructuredDataMapEntry(
        const StructuredDataMapEntry& x)
{
    m_key = x.m_key;
    m_pairs = x.m_pairs;
}

StructuredDataMapEntry::StructuredDataMapEntry(
        StructuredDataMapEntry&& x) noexcept
{
    m_key = std::move(x.m_key);
    m_pairs = std::move(x.m_pairs);
}

StructuredDataMapEntry& StructuredDataMapEntry::operator =(
        const StructuredDataMapEntry& x)
{

    m_key = x.m_key;
    m_pairs = x.m_pairs;
    return *this;
}

StructuredDataMapEntry& StructuredDataMapEntry::operator =(
        StructuredDataMapEntry&& x) noexcept
{

    m_key = std::move(x.m_key);
    m_pairs = std::move(x.m_pairs);
    return *this;
}

bool StructuredDataMapEntry::operator ==(
        const StructuredDataMapEntry& x) const
{
    return (m_key == x.m_key &&
           m_pairs == x.m_pairs);
}

bool StructuredDataMapEntry::operator !=(
        const StructuredDataMapEntry& x) const
{
    return !(*this == x);
}

/*!
 * @brief This function copies the value in member key
 * @param _key New value to be copied in member key
 */
void StructuredDataMapEntry::key(
        const std::string& _key)
{
    m_key = _key;
}

/*!
 * @brief This function moves the value in member key
 * @param _key New value to be moved in member key
 */
void StructuredDataMapEntry::key(
        std::string&& _key)
{
    m_key = std::move(_key);
}

/*!
 * @brief This function returns a constant reference to member key
 * @return Constant reference to member key
 */
const std::string& StructuredDataMapEntry::key() const
{
    return m_key;
}

/*!
 * @brief This function returns a reference to member key
 * @return Reference to member key
 */
std::string& StructuredDataMapEntry::key()
{
    return m_key;
}


/*!
 * @brief This function copies the value in member pairs
 * @param _pairs New value to be copied in member pairs
 */
void StructuredDataMapEntry::pairs(
        const std::vector<DSF::NamedValue>& _pairs)
{
    m_pairs = _pairs;
}

/*!
 * @brief This function moves the value in member pairs
 * @param _pairs New value to be moved in member pairs
 */
void StructuredDataMapEntry::pairs(
        std::vector<DSF::NamedValue>&& _pairs)
{
    m_pairs = std::move(_pairs);
}

/*!
 * @brief This function returns a constant reference to member pairs
 * @return Constant reference to member pairs
 */
const std::vector<DSF::NamedValue>& StructuredDataMapEntry::pairs() const
{
    return m_pairs;
}

/*!
 * @brief This function returns a reference to member pairs
 * @return Reference to member pairs
 */
std::vector<DSF::NamedValue>& StructuredDataMapEntry::pairs()
{
    return m_pairs;
}


DataBuffer::DataBuffer()
{
}

DataBuffer::~DataBuffer()
{
}

DataBuffer::DataBuffer(
        const DataBuffer& x)
{
    m_data = x.m_data;
    m_length = x.m_length;
}

DataBuffer::DataBuffer(
        DataBuffer&& x) noexcept
{
    m_data = std::move(x.m_data);
    m_length = x.m_length;
}

DataBuffer& DataBuffer::operator =(
        const DataBuffer& x)
{

    m_data = x.m_data;
    m_length = x.m_length;
    return *this;
}

DataBuffer& DataBuffer::operator =(
        DataBuffer&& x) noexcept
{

    m_data = std::move(x.m_data);
    m_length = x.m_length;
    return *this;
}

bool DataBuffer::operator ==(
        const DataBuffer& x) const
{
    return (m_data == x.m_data &&
           m_length == x.m_length);
}

bool DataBuffer::operator !=(
        const DataBuffer& x) const
{
    return !(*this == x);
}

/*!
 * @brief This function copies the value in member data
 * @param _data New value to be copied in member data
 */
void DataBuffer::data(
        const std::vector<uint8_t>& _data)
{
    m_data = _data;
}

/*!
 * @brief This function moves the value in member data
 * @param _data New value to be moved in member data
 */
void DataBuffer::data(
        std::vector<uint8_t>&& _data)
{
    m_data = std::move(_data);
}

/*!
 * @brief This function returns a constant reference to member data
 * @return Constant reference to member data
 */
const std::vector<uint8_t>& DataBuffer::data() const
{
    return m_data;
}

/*!
 * @brief This function returns a reference to member data
 * @return Reference to member data
 */
std::vector<uint8_t>& DataBuffer::data()
{
    return m_data;
}


/*!
 * @brief This function sets a value in member length
 * @param _length New value for member length
 */
void DataBuffer::length(
        uint32_t _length)
{
    m_length = _length;
}

/*!
 * @brief This function returns the value of member length
 * @return Value of member length
 */
uint32_t DataBuffer::length() const
{
    return m_length;
}

/*!
 * @brief This function returns a reference to member length
 * @return Reference to member length
 */
uint32_t& DataBuffer::length()
{
    return m_length;
}


namespace DataTypes {

DT_FILE::DT_FILE()
{
}

DT_FILE::~DT_FILE()
{
}

DT_FILE::DT_FILE(
        const DT_FILE& x)
{
    m_fname = x.m_fname;
    m_fdata = x.m_fdata;
    m_fversion = x.m_fversion;
}

DT_FILE::DT_FILE(
        DT_FILE&& x) noexcept
{
    m_fname = std::move(x.m_fname);
    m_fdata = std::move(x.m_fdata);
    m_fversion = std::move(x.m_fversion);
}

DT_FILE& DT_FILE::operator =(
        const DT_FILE& x)
{

    m_fname = x.m_fname;
    m_fdata = x.m_fdata;
    m_fversion = x.m_fversion;
    return *this;
}

DT_FILE& DT_FILE::operator =(
        DT_FILE&& x) noexcept
{

    m_fname = std::move(x.m_fname);
    m_fdata = std::move(x.m_fdata);
    m_fversion = std::move(x.m_fversion);
    return *this;
}

bool DT_FILE::operator ==(
        const DT_FILE& x) const
{
    return (m_fname == x.m_fname &&
           m_fdata == x.m_fdata &&
           m_fversion == x.m_fversion);
}

bool DT_FILE::operator !=(
        const DT_FILE& x) const
{
    return !(*this == x);
}

/*!
 * @brief This function copies the value in member fname
 * @param _fname New value to be copied in member fname
 */
void DT_FILE::fname(
        const std::string& _fname)
{
    m_fname = _fname;
}

/*!
 * @brief This function moves the value in member fname
 * @param _fname New value to be moved in member fname
 */
void DT_FILE::fname(
        std::string&& _fname)
{
    m_fname = std::move(_fname);
}

/*!
 * @brief This function returns a constant reference to member fname
 * @return Constant reference to member fname
 */
const std::string& DT_FILE::fname() const
{
    return m_fname;
}

/*!
 * @brief This function returns a reference to member fname
 * @return Reference to member fname
 */
std::string& DT_FILE::fname()
{
    return m_fname;
}


/*!
 * @brief This function copies the value in member fdata
 * @param _fdata New value to be copied in member fdata
 */
void DT_FILE::fdata(
        const DSF::DataBuffer& _fdata)
{
    m_fdata = _fdata;
}

/*!
 * @brief This function moves the value in member fdata
 * @param _fdata New value to be moved in member fdata
 */
void DT_FILE::fdata(
        DSF::DataBuffer&& _fdata)
{
    m_fdata = std::move(_fdata);
}

/*!
 * @brief This function returns a constant reference to member fdata
 * @return Constant reference to member fdata
 */
const DSF::DataBuffer& DT_FILE::fdata() const
{
    return m_fdata;
}

/*!
 * @brief This function returns a reference to member fdata
 * @return Reference to member fdata
 */
DSF::DataBuffer& DT_FILE::fdata()
{
    return m_fdata;
}


/*!
 * @brief This function copies the value in member fversion
 * @param _fversion New value to be copied in member fversion
 */
void DT_FILE::fversion(
        const std::string& _fversion)
{
    m_fversion = _fversion;
}

/*!
 * @brief This function moves the value in member fversion
 * @param _fversion New value to be moved in member fversion
 */
void DT_FILE::fversion(
        std::string&& _fversion)
{
    m_fversion = std::move(_fversion);
}

/*!
 * @brief This function returns a constant reference to member fversion
 * @return Constant reference to member fversion
 */
const std::string& DT_FILE::fversion() const
{
    return m_fversion;
}

/*!
 * @brief This function returns a reference to member fversion
 * @return Reference to member fversion
 */
std::string& DT_FILE::fversion()
{
    return m_fversion;
}


DT_TIME::DT_TIME()
{
    m__d = 127;
}

DT_TIME::~DT_TIME()
{
}

DT_TIME::DT_TIME(
        const DT_TIME& x)
{
    m__d = x.m__d;

    switch (m__d)
    {
        case 0:
            m_T0 = x.m_T0;
            break;


        default:
            m_T1 = x.m_T1;

            break;
    }
}

DT_TIME::DT_TIME(
        DT_TIME&& x) noexcept
{
    m__d = x.m__d;

    switch (m__d)
    {
        case 0:
            m_T0 = std::move(x.m_T0);

            break;


        default:
            m_T1 = x.m_T1;
            break;
    }
}

DT_TIME& DT_TIME::operator =(
        const DT_TIME& x)
{
    m__d = x.m__d;

    switch (m__d)
    {
        case 0:
            m_T0 = x.m_T0;
            break;


        default:
            m_T1 = x.m_T1;

            break;
    }

    return *this;
}

DT_TIME& DT_TIME::operator =(
        DT_TIME&& x) noexcept
{
    m__d = x.m__d;

    switch (m__d)
    {
        case 0:
            m_T0 = std::move(x.m_T0);

            break;


        default:
            m_T1 = x.m_T1;
            break;
    }

    return *this;
}

bool DT_TIME::operator ==(
        const DT_TIME& x) const
{
    if (m__d != x.m__d)
    {
        return false;
    }

    switch (m__d)
    {
        case 0:
            return (m_T0 == x.m_T0);
            break;


        default:
            return m_T1 == x.m_T1;

            break;
    }
    return false;
}

bool DT_TIME::operator !=(
        const DT_TIME& x) const
{
    return !(*this == x);
}

void DT_TIME::_d(
        uint8_t __d)
{
    bool b = false;

    switch (m__d)
    {
        case 0:
            switch (__d)
            {
                case 0:
                    b = true;
                    break;
                default:
                    break;
            }
            break;


        default:
            b = true;
            switch (__d)
            {
                case 0:
                    b = false;
                    break;
                default:
                    break;
            }
            break;

    }

    if (!b)
    {
        //throw BadParamException("Discriminator doesn't correspond with the selected union member");
    }

    m__d = __d;
}

uint8_t DT_TIME::_d() const
{
    return m__d;
}

uint8_t& DT_TIME::_d()
{
    return m__d;
}

void DT_TIME::T0(
        const std::vector<char>& _T0)
{
    m_T0 = _T0;
    m__d = 0;

}

void DT_TIME::T0(
        std::vector<char>&& _T0)
{
    m_T0 = std::move(_T0);
    m__d = 0;

}

const std::vector<char>& DT_TIME::T0() const
{
    bool b = false;

    switch (m__d)
    {
        case 0:
            b = true;
            break;
        default:
            break;
    }

    if (!b)
    {
        //throw BadParamException("This member has not been selected");
    }

    return m_T0;
}

std::vector<char>& DT_TIME::T0()
{
    bool b = false;

    switch (m__d)
    {
        case 0:
            b = true;
            break;
        default:
            break;
    }

    if (!b)
    {
        //throw BadParamException("This member has not been selected");
    }

    return m_T0;
}


void DT_TIME::T1(
        int32_t _T1)
{
    m_T1 = _T1;
    m__d = 127;

}

int32_t DT_TIME::T1() const
{
    bool b = true;

    switch (m__d)
    {
        case 0:
            b = false;
            break;
        default:
            break;
    }
    if (!b)
    {
        //throw BadParamException("This member has not been selected");
    }

    return m_T1;
}

int32_t& DT_TIME::T1()
{
    bool b = true;

    switch (m__d)
    {
        case 0:
            b = false;
            break;
        default:
            break;
    }
    if (!b)
    {
        //throw BadParamException("This member has not been selected");
    }

    return m_T1;
}


DT_DATE::DT_DATE()
{
    m__d = 127;
}

DT_DATE::~DT_DATE()
{
}

DT_DATE::DT_DATE(
        const DT_DATE& x)
{
    m__d = x.m__d;

    switch (m__d)
    {
        case 0:
            m_D0 = x.m_D0;
            break;


        default:
            m_D1 = x.m_D1;

            break;
    }
}

DT_DATE::DT_DATE(
        DT_DATE&& x) noexcept
{
    m__d = x.m__d;

    switch (m__d)
    {
        case 0:
            m_D0 = std::move(x.m_D0);

            break;


        default:
            m_D1 = x.m_D1;
            break;
    }
}

DT_DATE& DT_DATE::operator =(
        const DT_DATE& x)
{
    m__d = x.m__d;

    switch (m__d)
    {
        case 0:
            m_D0 = x.m_D0;
            break;


        default:
            m_D1 = x.m_D1;

            break;
    }

    return *this;
}

DT_DATE& DT_DATE::operator =(
        DT_DATE&& x) noexcept
{
    m__d = x.m__d;

    switch (m__d)
    {
        case 0:
            m_D0 = std::move(x.m_D0);

            break;


        default:
            m_D1 = x.m_D1;
            break;
    }

    return *this;
}

bool DT_DATE::operator ==(
        const DT_DATE& x) const
{
    if (m__d != x.m__d)
    {
        return false;
    }

    switch (m__d)
    {
        case 0:
            return (m_D0 == x.m_D0);
            break;


        default:
            return m_D1 == x.m_D1;

            break;
    }
    return false;
}

bool DT_DATE::operator !=(
        const DT_DATE& x) const
{
    return !(*this == x);
}

void DT_DATE::_d(
        uint8_t __d)
{
    bool b = false;

    switch (m__d)
    {
        case 0:
            switch (__d)
            {
                case 0:
                    b = true;
                    break;
                default:
                    break;
            }
            break;


        default:
            b = true;
            switch (__d)
            {
                case 0:
                    b = false;
                    break;
                default:
                    break;
            }
            break;

    }

    if (!b)
    {
        //throw BadParamException("Discriminator doesn't correspond with the selected union member");
    }

    m__d = __d;
}

uint8_t DT_DATE::_d() const
{
    return m__d;
}

uint8_t& DT_DATE::_d()
{
    return m__d;
}

void DT_DATE::D0(
        const std::vector<char>& _D0)
{
    m_D0 = _D0;
    m__d = 0;

}

void DT_DATE::D0(
        std::vector<char>&& _D0)
{
    m_D0 = std::move(_D0);
    m__d = 0;

}

const std::vector<char>& DT_DATE::D0() const
{
    bool b = false;

    switch (m__d)
    {
        case 0:
            b = true;
            break;
        default:
            break;
    }

    if (!b)
    {
        //throw BadParamException("This member has not been selected");
    }

    return m_D0;
}

std::vector<char>& DT_DATE::D0()
{
    bool b = false;

    switch (m__d)
    {
        case 0:
            b = true;
            break;
        default:
            break;
    }

    if (!b)
    {
        //throw BadParamException("This member has not been selected");
    }

    return m_D0;
}


void DT_DATE::D1(
        int32_t _D1)
{
    m_D1 = _D1;
    m__d = 127;

}

int32_t DT_DATE::D1() const
{
    bool b = true;

    switch (m__d)
    {
        case 0:
            b = false;
            break;
        default:
            break;
    }
    if (!b)
    {
        //throw BadParamException("This member has not been selected");
    }

    return m_D1;
}

int32_t& DT_DATE::D1()
{
    bool b = true;

    switch (m__d)
    {
        case 0:
            b = false;
            break;
        default:
            break;
    }
    if (!b)
    {
        //throw BadParamException("This member has not been selected");
    }

    return m_D1;
}


DT_TIME_OF_DAY::DT_TIME_OF_DAY()
{
    m__d = 127;
}

DT_TIME_OF_DAY::~DT_TIME_OF_DAY()
{
}

DT_TIME_OF_DAY::DT_TIME_OF_DAY(
        const DT_TIME_OF_DAY& x)
{
    m__d = x.m__d;

    switch (m__d)
    {
        case 0:
            m_TOD0 = x.m_TOD0;
            break;


        default:
            m_TOD1 = x.m_TOD1;

            break;
    }
}

DT_TIME_OF_DAY::DT_TIME_OF_DAY(
        DT_TIME_OF_DAY&& x) noexcept
{
    m__d = x.m__d;

    switch (m__d)
    {
        case 0:
            m_TOD0 = std::move(x.m_TOD0);

            break;


        default:
            m_TOD1 = x.m_TOD1;
            break;
    }
}

DT_TIME_OF_DAY& DT_TIME_OF_DAY::operator =(
        const DT_TIME_OF_DAY& x)
{
    m__d = x.m__d;

    switch (m__d)
    {
        case 0:
            m_TOD0 = x.m_TOD0;
            break;


        default:
            m_TOD1 = x.m_TOD1;

            break;
    }

    return *this;
}

DT_TIME_OF_DAY& DT_TIME_OF_DAY::operator =(
        DT_TIME_OF_DAY&& x) noexcept
{
    m__d = x.m__d;

    switch (m__d)
    {
        case 0:
            m_TOD0 = std::move(x.m_TOD0);

            break;


        default:
            m_TOD1 = x.m_TOD1;
            break;
    }

    return *this;
}

bool DT_TIME_OF_DAY::operator ==(
        const DT_TIME_OF_DAY& x) const
{
    if (m__d != x.m__d)
    {
        return false;
    }

    switch (m__d)
    {
        case 0:
            return (m_TOD0 == x.m_TOD0);
            break;


        default:
            return m_TOD1 == x.m_TOD1;

            break;
    }
    return false;
}

bool DT_TIME_OF_DAY::operator !=(
        const DT_TIME_OF_DAY& x) const
{
    return !(*this == x);
}

void DT_TIME_OF_DAY::_d(
        uint8_t __d)
{
    bool b = false;

    switch (m__d)
    {
        case 0:
            switch (__d)
            {
                case 0:
                    b = true;
                    break;
                default:
                    break;
            }
            break;


        default:
            b = true;
            switch (__d)
            {
                case 0:
                    b = false;
                    break;
                default:
                    break;
            }
            break;

    }

    if (!b)
    {
        //throw BadParamException("Discriminator doesn't correspond with the selected union member");
    }

    m__d = __d;
}

uint8_t DT_TIME_OF_DAY::_d() const
{
    return m__d;
}

uint8_t& DT_TIME_OF_DAY::_d()
{
    return m__d;
}

void DT_TIME_OF_DAY::TOD0(
        const std::vector<char>& _TOD0)
{
    m_TOD0 = _TOD0;
    m__d = 0;

}

void DT_TIME_OF_DAY::TOD0(
        std::vector<char>&& _TOD0)
{
    m_TOD0 = std::move(_TOD0);
    m__d = 0;

}

const std::vector<char>& DT_TIME_OF_DAY::TOD0() const
{
    bool b = false;

    switch (m__d)
    {
        case 0:
            b = true;
            break;
        default:
            break;
    }

    if (!b)
    {
        //throw BadParamException("This member has not been selected");
    }

    return m_TOD0;
}

std::vector<char>& DT_TIME_OF_DAY::TOD0()
{
    bool b = false;

    switch (m__d)
    {
        case 0:
            b = true;
            break;
        default:
            break;
    }

    if (!b)
    {
        //throw BadParamException("This member has not been selected");
    }

    return m_TOD0;
}


void DT_TIME_OF_DAY::TOD1(
        int32_t _TOD1)
{
    m_TOD1 = _TOD1;
    m__d = 127;

}

int32_t DT_TIME_OF_DAY::TOD1() const
{
    bool b = true;

    switch (m__d)
    {
        case 0:
            b = false;
            break;
        default:
            break;
    }
    if (!b)
    {
        //throw BadParamException("This member has not been selected");
    }

    return m_TOD1;
}

int32_t& DT_TIME_OF_DAY::TOD1()
{
    bool b = true;

    switch (m__d)
    {
        case 0:
            b = false;
            break;
        default:
            break;
    }
    if (!b)
    {
        //throw BadParamException("This member has not been selected");
    }

    return m_TOD1;
}


DT_DATE_AND_TIME::DT_DATE_AND_TIME()
{
    m__d = 127;
}

DT_DATE_AND_TIME::~DT_DATE_AND_TIME()
{
}

DT_DATE_AND_TIME::DT_DATE_AND_TIME(
        const DT_DATE_AND_TIME& x)
{
    m__d = x.m__d;

    switch (m__d)
    {
        case 0:
            m_DT0 = x.m_DT0;
            break;


        default:
            m_DT1 = x.m_DT1;

            break;
    }
}

DT_DATE_AND_TIME::DT_DATE_AND_TIME(
        DT_DATE_AND_TIME&& x) noexcept
{
    m__d = x.m__d;

    switch (m__d)
    {
        case 0:
            m_DT0 = std::move(x.m_DT0);

            break;


        default:
            m_DT1 = x.m_DT1;
            break;
    }
}

DT_DATE_AND_TIME& DT_DATE_AND_TIME::operator =(
        const DT_DATE_AND_TIME& x)
{
    m__d = x.m__d;

    switch (m__d)
    {
        case 0:
            m_DT0 = x.m_DT0;
            break;


        default:
            m_DT1 = x.m_DT1;

            break;
    }

    return *this;
}

DT_DATE_AND_TIME& DT_DATE_AND_TIME::operator =(
        DT_DATE_AND_TIME&& x) noexcept
{
    m__d = x.m__d;

    switch (m__d)
    {
        case 0:
            m_DT0 = std::move(x.m_DT0);

            break;


        default:
            m_DT1 = x.m_DT1;
            break;
    }

    return *this;
}

bool DT_DATE_AND_TIME::operator ==(
        const DT_DATE_AND_TIME& x) const
{
    if (m__d != x.m__d)
    {
        return false;
    }

    switch (m__d)
    {
        case 0:
            return (m_DT0 == x.m_DT0);
            break;


        default:
            return m_DT1 == x.m_DT1;

            break;
    }
    return false;
}

bool DT_DATE_AND_TIME::operator !=(
        const DT_DATE_AND_TIME& x) const
{
    return !(*this == x);
}

void DT_DATE_AND_TIME::_d(
        uint8_t __d)
{
    bool b = false;

    switch (m__d)
    {
        case 0:
            switch (__d)
            {
                case 0:
                    b = true;
                    break;
                default:
                    break;
            }
            break;


        default:
            b = true;
            switch (__d)
            {
                case 0:
                    b = false;
                    break;
                default:
                    break;
            }
            break;

    }

    if (!b)
    {
        //throw BadParamException("Discriminator doesn't correspond with the selected union member");
    }

    m__d = __d;
}

uint8_t DT_DATE_AND_TIME::_d() const
{
    return m__d;
}

uint8_t& DT_DATE_AND_TIME::_d()
{
    return m__d;
}

void DT_DATE_AND_TIME::DT0(
        const std::vector<char>& _DT0)
{
    m_DT0 = _DT0;
    m__d = 0;

}

void DT_DATE_AND_TIME::DT0(
        std::vector<char>&& _DT0)
{
    m_DT0 = std::move(_DT0);
    m__d = 0;

}

const std::vector<char>& DT_DATE_AND_TIME::DT0() const
{
    bool b = false;

    switch (m__d)
    {
        case 0:
            b = true;
            break;
        default:
            break;
    }

    if (!b)
    {
        //throw BadParamException("This member has not been selected");
    }

    return m_DT0;
}

std::vector<char>& DT_DATE_AND_TIME::DT0()
{
    bool b = false;

    switch (m__d)
    {
        case 0:
            b = true;
            break;
        default:
            break;
    }

    if (!b)
    {
        //throw BadParamException("This member has not been selected");
    }

    return m_DT0;
}


void DT_DATE_AND_TIME::DT1(
        int32_t _DT1)
{
    m_DT1 = _DT1;
    m__d = 127;

}

int32_t DT_DATE_AND_TIME::DT1() const
{
    bool b = true;

    switch (m__d)
    {
        case 0:
            b = false;
            break;
        default:
            break;
    }
    if (!b)
    {
        //throw BadParamException("This member has not been selected");
    }

    return m_DT1;
}

int32_t& DT_DATE_AND_TIME::DT1()
{
    bool b = true;

    switch (m__d)
    {
        case 0:
            b = false;
            break;
        default:
            break;
    }
    if (!b)
    {
        //throw BadParamException("This member has not been selected");
    }

    return m_DT1;
}


DT_LDATE::DT_LDATE()
{
    m__d = 127;
}

DT_LDATE::~DT_LDATE()
{
}

DT_LDATE::DT_LDATE(
        const DT_LDATE& x)
{
    m__d = x.m__d;

    switch (m__d)
    {
        case 0:
            m_LD0 = x.m_LD0;
            break;


        default:
            m_LD1 = x.m_LD1;

            break;
    }
}

DT_LDATE::DT_LDATE(
        DT_LDATE&& x) noexcept
{
    m__d = x.m__d;

    switch (m__d)
    {
        case 0:
            m_LD0 = std::move(x.m_LD0);

            break;


        default:
            m_LD1 = x.m_LD1;
            break;
    }
}

DT_LDATE& DT_LDATE::operator =(
        const DT_LDATE& x)
{
    m__d = x.m__d;

    switch (m__d)
    {
        case 0:
            m_LD0 = x.m_LD0;
            break;


        default:
            m_LD1 = x.m_LD1;

            break;
    }

    return *this;
}

DT_LDATE& DT_LDATE::operator =(
        DT_LDATE&& x) noexcept
{
    m__d = x.m__d;

    switch (m__d)
    {
        case 0:
            m_LD0 = std::move(x.m_LD0);

            break;


        default:
            m_LD1 = x.m_LD1;
            break;
    }

    return *this;
}

bool DT_LDATE::operator ==(
        const DT_LDATE& x) const
{
    if (m__d != x.m__d)
    {
        return false;
    }

    switch (m__d)
    {
        case 0:
            return (m_LD0 == x.m_LD0);
            break;


        default:
            return m_LD1 == x.m_LD1;

            break;
    }
    return false;
}

bool DT_LDATE::operator !=(
        const DT_LDATE& x) const
{
    return !(*this == x);
}

void DT_LDATE::_d(
        uint8_t __d)
{
    bool b = false;

    switch (m__d)
    {
        case 0:
            switch (__d)
            {
                case 0:
                    b = true;
                    break;
                default:
                    break;
            }
            break;


        default:
            b = true;
            switch (__d)
            {
                case 0:
                    b = false;
                    break;
                default:
                    break;
            }
            break;

    }

    if (!b)
    {
        //throw BadParamException("Discriminator doesn't correspond with the selected union member");
    }

    m__d = __d;
}

uint8_t DT_LDATE::_d() const
{
    return m__d;
}

uint8_t& DT_LDATE::_d()
{
    return m__d;
}

void DT_LDATE::LD0(
        const std::vector<char>& _LD0)
{
    m_LD0 = _LD0;
    m__d = 0;

}

void DT_LDATE::LD0(
        std::vector<char>&& _LD0)
{
    m_LD0 = std::move(_LD0);
    m__d = 0;

}

const std::vector<char>& DT_LDATE::LD0() const
{
    bool b = false;

    switch (m__d)
    {
        case 0:
            b = true;
            break;
        default:
            break;
    }

    if (!b)
    {
        //throw BadParamException("This member has not been selected");
    }

    return m_LD0;
}

std::vector<char>& DT_LDATE::LD0()
{
    bool b = false;

    switch (m__d)
    {
        case 0:
            b = true;
            break;
        default:
            break;
    }

    if (!b)
    {
        //throw BadParamException("This member has not been selected");
    }

    return m_LD0;
}


void DT_LDATE::LD1(
        int32_t _LD1)
{
    m_LD1 = _LD1;
    m__d = 127;

}

int32_t DT_LDATE::LD1() const
{
    bool b = true;

    switch (m__d)
    {
        case 0:
            b = false;
            break;
        default:
            break;
    }
    if (!b)
    {
        //throw BadParamException("This member has not been selected");
    }

    return m_LD1;
}

int32_t& DT_LDATE::LD1()
{
    bool b = true;

    switch (m__d)
    {
        case 0:
            b = false;
            break;
        default:
            break;
    }
    if (!b)
    {
        //throw BadParamException("This member has not been selected");
    }

    return m_LD1;
}


DT_LTIME_OF_DAY::DT_LTIME_OF_DAY()
{
    m__d = 127;
}

DT_LTIME_OF_DAY::~DT_LTIME_OF_DAY()
{
}

DT_LTIME_OF_DAY::DT_LTIME_OF_DAY(
        const DT_LTIME_OF_DAY& x)
{
    m__d = x.m__d;

    switch (m__d)
    {
        case 0:
            m_LTOD0 = x.m_LTOD0;
            break;


        default:
            m_LTOD1 = x.m_LTOD1;

            break;
    }
}

DT_LTIME_OF_DAY::DT_LTIME_OF_DAY(
        DT_LTIME_OF_DAY&& x) noexcept
{
    m__d = x.m__d;

    switch (m__d)
    {
        case 0:
            m_LTOD0 = std::move(x.m_LTOD0);

            break;


        default:
            m_LTOD1 = x.m_LTOD1;
            break;
    }
}

DT_LTIME_OF_DAY& DT_LTIME_OF_DAY::operator =(
        const DT_LTIME_OF_DAY& x)
{
    m__d = x.m__d;

    switch (m__d)
    {
        case 0:
            m_LTOD0 = x.m_LTOD0;
            break;


        default:
            m_LTOD1 = x.m_LTOD1;

            break;
    }

    return *this;
}

DT_LTIME_OF_DAY& DT_LTIME_OF_DAY::operator =(
        DT_LTIME_OF_DAY&& x) noexcept
{
    m__d = x.m__d;

    switch (m__d)
    {
        case 0:
            m_LTOD0 = std::move(x.m_LTOD0);

            break;


        default:
            m_LTOD1 = x.m_LTOD1;
            break;
    }

    return *this;
}

bool DT_LTIME_OF_DAY::operator ==(
        const DT_LTIME_OF_DAY& x) const
{
    if (m__d != x.m__d)
    {
        return false;
    }

    switch (m__d)
    {
        case 0:
            return (m_LTOD0 == x.m_LTOD0);
            break;


        default:
            return m_LTOD1 == x.m_LTOD1;

            break;
    }
    return false;
}

bool DT_LTIME_OF_DAY::operator !=(
        const DT_LTIME_OF_DAY& x) const
{
    return !(*this == x);
}

void DT_LTIME_OF_DAY::_d(
        uint8_t __d)
{
    bool b = false;

    switch (m__d)
    {
        case 0:
            switch (__d)
            {
                case 0:
                    b = true;
                    break;
                default:
                    break;
            }
            break;


        default:
            b = true;
            switch (__d)
            {
                case 0:
                    b = false;
                    break;
                default:
                    break;
            }
            break;

    }

    if (!b)
    {
        //throw BadParamException("Discriminator doesn't correspond with the selected union member");
    }

    m__d = __d;
}

uint8_t DT_LTIME_OF_DAY::_d() const
{
    return m__d;
}

uint8_t& DT_LTIME_OF_DAY::_d()
{
    return m__d;
}

void DT_LTIME_OF_DAY::LTOD0(
        const std::vector<char>& _LTOD0)
{
    m_LTOD0 = _LTOD0;
    m__d = 0;

}

void DT_LTIME_OF_DAY::LTOD0(
        std::vector<char>&& _LTOD0)
{
    m_LTOD0 = std::move(_LTOD0);
    m__d = 0;

}

const std::vector<char>& DT_LTIME_OF_DAY::LTOD0() const
{
    bool b = false;

    switch (m__d)
    {
        case 0:
            b = true;
            break;
        default:
            break;
    }

    if (!b)
    {
        //throw BadParamException("This member has not been selected");
    }

    return m_LTOD0;
}

std::vector<char>& DT_LTIME_OF_DAY::LTOD0()
{
    bool b = false;

    switch (m__d)
    {
        case 0:
            b = true;
            break;
        default:
            break;
    }

    if (!b)
    {
        //throw BadParamException("This member has not been selected");
    }

    return m_LTOD0;
}


void DT_LTIME_OF_DAY::LTOD1(
        int64_t _LTOD1)
{
    m_LTOD1 = _LTOD1;
    m__d = 127;

}

int64_t DT_LTIME_OF_DAY::LTOD1() const
{
    bool b = true;

    switch (m__d)
    {
        case 0:
            b = false;
            break;
        default:
            break;
    }
    if (!b)
    {
        //throw BadParamException("This member has not been selected");
    }

    return m_LTOD1;
}

int64_t& DT_LTIME_OF_DAY::LTOD1()
{
    bool b = true;

    switch (m__d)
    {
        case 0:
            b = false;
            break;
        default:
            break;
    }
    if (!b)
    {
        //throw BadParamException("This member has not been selected");
    }

    return m_LTOD1;
}


DT_LDATE_AND_TIME::DT_LDATE_AND_TIME()
{
    m__d = 127;
}

DT_LDATE_AND_TIME::~DT_LDATE_AND_TIME()
{
}

DT_LDATE_AND_TIME::DT_LDATE_AND_TIME(
        const DT_LDATE_AND_TIME& x)
{
    m__d = x.m__d;

    switch (m__d)
    {
        case 0:
            m_LDT0 = x.m_LDT0;
            break;


        default:
            m_LDT1 = x.m_LDT1;

            break;
    }
}

DT_LDATE_AND_TIME::DT_LDATE_AND_TIME(
        DT_LDATE_AND_TIME&& x) noexcept
{
    m__d = x.m__d;

    switch (m__d)
    {
        case 0:
            m_LDT0 = std::move(x.m_LDT0);

            break;


        default:
            m_LDT1 = x.m_LDT1;
            break;
    }
}

DT_LDATE_AND_TIME& DT_LDATE_AND_TIME::operator =(
        const DT_LDATE_AND_TIME& x)
{
    m__d = x.m__d;

    switch (m__d)
    {
        case 0:
            m_LDT0 = x.m_LDT0;
            break;


        default:
            m_LDT1 = x.m_LDT1;

            break;
    }

    return *this;
}

DT_LDATE_AND_TIME& DT_LDATE_AND_TIME::operator =(
        DT_LDATE_AND_TIME&& x) noexcept
{
    m__d = x.m__d;

    switch (m__d)
    {
        case 0:
            m_LDT0 = std::move(x.m_LDT0);

            break;


        default:
            m_LDT1 = x.m_LDT1;
            break;
    }

    return *this;
}

bool DT_LDATE_AND_TIME::operator ==(
        const DT_LDATE_AND_TIME& x) const
{
    if (m__d != x.m__d)
    {
        return false;
    }

    switch (m__d)
    {
        case 0:
            return (m_LDT0 == x.m_LDT0);
            break;


        default:
            return m_LDT1 == x.m_LDT1;

            break;
    }
    return false;
}

bool DT_LDATE_AND_TIME::operator !=(
        const DT_LDATE_AND_TIME& x) const
{
    return !(*this == x);
}

void DT_LDATE_AND_TIME::_d(
        uint8_t __d)
{
    bool b = false;

    switch (m__d)
    {
        case 0:
            switch (__d)
            {
                case 0:
                    b = true;
                    break;
                default:
                    break;
            }
            break;


        default:
            b = true;
            switch (__d)
            {
                case 0:
                    b = false;
                    break;
                default:
                    break;
            }
            break;

    }

    if (!b)
    {
        //throw BadParamException("Discriminator doesn't correspond with the selected union member");
    }

    m__d = __d;
}

uint8_t DT_LDATE_AND_TIME::_d() const
{
    return m__d;
}

uint8_t& DT_LDATE_AND_TIME::_d()
{
    return m__d;
}

void DT_LDATE_AND_TIME::LDT0(
        const std::vector<char>& _LDT0)
{
    m_LDT0 = _LDT0;
    m__d = 0;

}

void DT_LDATE_AND_TIME::LDT0(
        std::vector<char>&& _LDT0)
{
    m_LDT0 = std::move(_LDT0);
    m__d = 0;

}

const std::vector<char>& DT_LDATE_AND_TIME::LDT0() const
{
    bool b = false;

    switch (m__d)
    {
        case 0:
            b = true;
            break;
        default:
            break;
    }

    if (!b)
    {
        //throw BadParamException("This member has not been selected");
    }

    return m_LDT0;
}

std::vector<char>& DT_LDATE_AND_TIME::LDT0()
{
    bool b = false;

    switch (m__d)
    {
        case 0:
            b = true;
            break;
        default:
            break;
    }

    if (!b)
    {
        //throw BadParamException("This member has not been selected");
    }

    return m_LDT0;
}


void DT_LDATE_AND_TIME::LDT1(
        int64_t _LDT1)
{
    m_LDT1 = _LDT1;
    m__d = 127;

}

int64_t DT_LDATE_AND_TIME::LDT1() const
{
    bool b = true;

    switch (m__d)
    {
        case 0:
            b = false;
            break;
        default:
            break;
    }
    if (!b)
    {
        //throw BadParamException("This member has not been selected");
    }

    return m_LDT1;
}

int64_t& DT_LDATE_AND_TIME::LDT1()
{
    bool b = true;

    switch (m__d)
    {
        case 0:
            b = false;
            break;
        default:
            break;
    }
    if (!b)
    {
        //throw BadParamException("This member has not been selected");
    }

    return m_LDT1;
}




} // namespace DataTypes


} // namespace DSF
// Include auxiliary functions like for serializing/deserializing.
#include "dsf_define_datatypesCdrAux.ipp"

