// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file FCV.cpp
 * This source file contains the implementation of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "FCV.h"

#include "txcdr/Cdr.h"

#include <utility>


FCVType::FCVType()
{
}

FCVType::~FCVType()
{
}

FCVType::FCVType(
        const FCVType& x)
{
    m_flow = x.m_flow;
    m_temp = x.m_temp;
    m_press = x.m_press;
    m_isopen = x.m_isopen;
    m_openvalue = x.m_openvalue;
    m_healthlevel = x.m_healthlevel;
}

FCVType::FCVType(
        FCVType&& x) noexcept
{
    m_flow = x.m_flow;
    m_temp = x.m_temp;
    m_press = x.m_press;
    m_isopen = x.m_isopen;
    m_openvalue = x.m_openvalue;
    m_healthlevel = x.m_healthlevel;
}

FCVType& FCVType::operator =(
        const FCVType& x)
{

    m_flow = x.m_flow;
    m_temp = x.m_temp;
    m_press = x.m_press;
    m_isopen = x.m_isopen;
    m_openvalue = x.m_openvalue;
    m_healthlevel = x.m_healthlevel;
    return *this;
}

FCVType& FCVType::operator =(
        FCVType&& x) noexcept
{

    m_flow = x.m_flow;
    m_temp = x.m_temp;
    m_press = x.m_press;
    m_isopen = x.m_isopen;
    m_openvalue = x.m_openvalue;
    m_healthlevel = x.m_healthlevel;
    return *this;
}

bool FCVType::operator ==(
        const FCVType& x) const
{
    return (m_flow == x.m_flow &&
           m_temp == x.m_temp &&
           m_press == x.m_press &&
           m_isopen == x.m_isopen &&
           m_openvalue == x.m_openvalue &&
           m_healthlevel == x.m_healthlevel);
}

bool FCVType::operator !=(
        const FCVType& x) const
{
    return !(*this == x);
}

/*!
 * @brief This function sets a value in member flow
 * @param _flow New value for member flow
 */
void FCVType::flow(
        float _flow)
{
    m_flow = _flow;
}

/*!
 * @brief This function returns the value of member flow
 * @return Value of member flow
 */
float FCVType::flow() const
{
    return m_flow;
}

/*!
 * @brief This function returns a reference to member flow
 * @return Reference to member flow
 */
float& FCVType::flow()
{
    return m_flow;
}


/*!
 * @brief This function sets a value in member temp
 * @param _temp New value for member temp
 */
void FCVType::temp(
        float _temp)
{
    m_temp = _temp;
}

/*!
 * @brief This function returns the value of member temp
 * @return Value of member temp
 */
float FCVType::temp() const
{
    return m_temp;
}

/*!
 * @brief This function returns a reference to member temp
 * @return Reference to member temp
 */
float& FCVType::temp()
{
    return m_temp;
}


/*!
 * @brief This function sets a value in member press
 * @param _press New value for member press
 */
void FCVType::press(
        float _press)
{
    m_press = _press;
}

/*!
 * @brief This function returns the value of member press
 * @return Value of member press
 */
float FCVType::press() const
{
    return m_press;
}

/*!
 * @brief This function returns a reference to member press
 * @return Reference to member press
 */
float& FCVType::press()
{
    return m_press;
}


/*!
 * @brief This function sets a value in member isopen
 * @param _isopen New value for member isopen
 */
void FCVType::isopen(
        bool _isopen)
{
    m_isopen = _isopen;
}

/*!
 * @brief This function returns the value of member isopen
 * @return Value of member isopen
 */
bool FCVType::isopen() const
{
    return m_isopen;
}

/*!
 * @brief This function returns a reference to member isopen
 * @return Reference to member isopen
 */
bool& FCVType::isopen()
{
    return m_isopen;
}


/*!
 * @brief This function sets a value in member openvalue
 * @param _openvalue New value for member openvalue
 */
void FCVType::openvalue(
        float _openvalue)
{
    m_openvalue = _openvalue;
}

/*!
 * @brief This function returns the value of member openvalue
 * @return Value of member openvalue
 */
float FCVType::openvalue() const
{
    return m_openvalue;
}

/*!
 * @brief This function returns a reference to member openvalue
 * @return Reference to member openvalue
 */
float& FCVType::openvalue()
{
    return m_openvalue;
}


/*!
 * @brief This function sets a value in member healthlevel
 * @param _healthlevel New value for member healthlevel
 */
void FCVType::healthlevel(
        float _healthlevel)
{
    m_healthlevel = _healthlevel;
}

/*!
 * @brief This function returns the value of member healthlevel
 * @return Value of member healthlevel
 */
float FCVType::healthlevel() const
{
    return m_healthlevel;
}

/*!
 * @brief This function returns a reference to member healthlevel
 * @return Reference to member healthlevel
 */
float& FCVType::healthlevel()
{
    return m_healthlevel;
}


// Include auxiliary functions like for serializing/deserializing.
#include "FCVCdrAux.ipp"

