// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file FCV.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef _TX_DDS_GENERATED_FCV_H_
#define _TX_DDS_GENERATED_FCV_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <map>
#include <string>
#include <vector>

#include "txcdr/optional.h"



#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(FCV_SOURCE)
#define FCV_DllAPI __declspec( dllexport )
#else
#define FCV_DllAPI __declspec( dllimport )
#endif // FCV_SOURCE
#else
#define FCV_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define FCV_DllAPI
#endif // _WIN32

namespace BaoSky::Cdr {
class Cdr;
class CdrSizeCalculator;
} // namespace BaoSky::Cdr




/*!
 * @brief This class represents the structure FCVType defined by the user in the IDL file.
 * @ingroup FCV
 */
class FCVType
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport FCVType();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~FCVType();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object FCVType that will be copied.
     */
    eProsima_user_DllExport FCVType(
            const FCVType& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object FCVType that will be copied.
     */
    eProsima_user_DllExport FCVType(
            FCVType&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object FCVType that will be copied.
     */
    eProsima_user_DllExport FCVType& operator =(
            const FCVType& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object FCVType that will be copied.
     */
    eProsima_user_DllExport FCVType& operator =(
            FCVType&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x FCVType object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const FCVType& x) const;

    /*!
     * @brief Comparison operator.
     * @param x FCVType object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const FCVType& x) const;

    /*!
     * @brief This function sets a value in member flow
     * @param _flow New value for member flow
     */
    eProsima_user_DllExport void flow(
            float _flow);

    /*!
     * @brief This function returns the value of member flow
     * @return Value of member flow
     */
    eProsima_user_DllExport float flow() const;

    /*!
     * @brief This function returns a reference to member flow
     * @return Reference to member flow
     */
    eProsima_user_DllExport float& flow();


    /*!
     * @brief This function sets a value in member temp
     * @param _temp New value for member temp
     */
    eProsima_user_DllExport void temp(
            float _temp);

    /*!
     * @brief This function returns the value of member temp
     * @return Value of member temp
     */
    eProsima_user_DllExport float temp() const;

    /*!
     * @brief This function returns a reference to member temp
     * @return Reference to member temp
     */
    eProsima_user_DllExport float& temp();


    /*!
     * @brief This function sets a value in member press
     * @param _press New value for member press
     */
    eProsima_user_DllExport void press(
            float _press);

    /*!
     * @brief This function returns the value of member press
     * @return Value of member press
     */
    eProsima_user_DllExport float press() const;

    /*!
     * @brief This function returns a reference to member press
     * @return Reference to member press
     */
    eProsima_user_DllExport float& press();


    /*!
     * @brief This function sets a value in member isopen
     * @param _isopen New value for member isopen
     */
    eProsima_user_DllExport void isopen(
            bool _isopen);

    /*!
     * @brief This function returns the value of member isopen
     * @return Value of member isopen
     */
    eProsima_user_DllExport bool isopen() const;

    /*!
     * @brief This function returns a reference to member isopen
     * @return Reference to member isopen
     */
    eProsima_user_DllExport bool& isopen();


    /*!
     * @brief This function sets a value in member openvalue
     * @param _openvalue New value for member openvalue
     */
    eProsima_user_DllExport void openvalue(
            float _openvalue);

    /*!
     * @brief This function returns the value of member openvalue
     * @return Value of member openvalue
     */
    eProsima_user_DllExport float openvalue() const;

    /*!
     * @brief This function returns a reference to member openvalue
     * @return Reference to member openvalue
     */
    eProsima_user_DllExport float& openvalue();


    /*!
     * @brief This function sets a value in member healthlevel
     * @param _healthlevel New value for member healthlevel
     */
    eProsima_user_DllExport void healthlevel(
            float _healthlevel);

    /*!
     * @brief This function returns the value of member healthlevel
     * @return Value of member healthlevel
     */
    eProsima_user_DllExport float healthlevel() const;

    /*!
     * @brief This function returns a reference to member healthlevel
     * @return Reference to member healthlevel
     */
    eProsima_user_DllExport float& healthlevel();

private:

    float m_flow{0.0};
    float m_temp{0.0};
    float m_press{0.0};
    bool m_isopen{false};
    float m_openvalue{0.0};
    float m_healthlevel{0.0};

};

#endif // _TX_DDS_GENERATED_FCV_H_



