// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file FCVTypeObjectSupport.cxx
 * Source file containing the implementation to register the TypeObject representation of the described types in the IDL file
 *
 * This file was generated by the tool fastddsgen.
 */

#include "FCVTypeObjectSupport.hpp"

#include <mutex>
#include <string>

#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/domain/DomainParticipantFactory.hpp>
#include <fastdds/dds/log/Log.hpp>
#include <fastdds/dds/xtypes/common.hpp>
#include <fastdds/dds/xtypes/type_representation/ITypeObjectRegistry.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObject.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObjectUtils.hpp>

#include "FCV.hpp"


using namespace eprosima::fastdds::dds::xtypes;

// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_FCVType_type_identifier(
        TypeIdentifierPair& type_ids_FCVType)
{

    ReturnCode_t return_code_FCVType {eprosima::fastdds::dds::RETCODE_OK};
    return_code_FCVType =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "FCVType", type_ids_FCVType);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_FCVType)
    {
        StructTypeFlag struct_flags_FCVType = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::APPENDABLE,
                false, false);
        QualifiedTypeName type_name_FCVType = "FCVType";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_FCVType;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_FCVType;
        CompleteTypeDetail detail_FCVType = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_FCVType, ann_custom_FCVType, type_name_FCVType.to_string());
        CompleteStructHeader header_FCVType;
        header_FCVType = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_FCVType);
        CompleteStructMemberSeq member_seq_FCVType;
        {
            TypeIdentifierPair type_ids_flow;
            ReturnCode_t return_code_flow {eprosima::fastdds::dds::RETCODE_OK};
            return_code_flow =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_float", type_ids_flow);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_flow)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "flow Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_flow = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_flow = 0x00000000;
            bool common_flow_ec {false};
            CommonStructMember common_flow {TypeObjectUtils::build_common_struct_member(member_id_flow, member_flags_flow, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_flow, common_flow_ec))};
            if (!common_flow_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure flow member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_flow = "flow";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_flow;
            ann_custom_FCVType.reset();
            CompleteMemberDetail detail_flow = TypeObjectUtils::build_complete_member_detail(name_flow, member_ann_builtin_flow, ann_custom_FCVType);
            CompleteStructMember member_flow = TypeObjectUtils::build_complete_struct_member(common_flow, detail_flow);
            TypeObjectUtils::add_complete_struct_member(member_seq_FCVType, member_flow);
        }
        {
            TypeIdentifierPair type_ids_temp;
            ReturnCode_t return_code_temp {eprosima::fastdds::dds::RETCODE_OK};
            return_code_temp =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_float", type_ids_temp);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_temp)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "temp Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_temp = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_temp = 0x00000001;
            bool common_temp_ec {false};
            CommonStructMember common_temp {TypeObjectUtils::build_common_struct_member(member_id_temp, member_flags_temp, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_temp, common_temp_ec))};
            if (!common_temp_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure temp member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_temp = "temp";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_temp;
            ann_custom_FCVType.reset();
            CompleteMemberDetail detail_temp = TypeObjectUtils::build_complete_member_detail(name_temp, member_ann_builtin_temp, ann_custom_FCVType);
            CompleteStructMember member_temp = TypeObjectUtils::build_complete_struct_member(common_temp, detail_temp);
            TypeObjectUtils::add_complete_struct_member(member_seq_FCVType, member_temp);
        }
        {
            TypeIdentifierPair type_ids_press;
            ReturnCode_t return_code_press {eprosima::fastdds::dds::RETCODE_OK};
            return_code_press =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_float", type_ids_press);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_press)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "press Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_press = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_press = 0x00000002;
            bool common_press_ec {false};
            CommonStructMember common_press {TypeObjectUtils::build_common_struct_member(member_id_press, member_flags_press, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_press, common_press_ec))};
            if (!common_press_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure press member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_press = "press";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_press;
            ann_custom_FCVType.reset();
            CompleteMemberDetail detail_press = TypeObjectUtils::build_complete_member_detail(name_press, member_ann_builtin_press, ann_custom_FCVType);
            CompleteStructMember member_press = TypeObjectUtils::build_complete_struct_member(common_press, detail_press);
            TypeObjectUtils::add_complete_struct_member(member_seq_FCVType, member_press);
        }
        {
            TypeIdentifierPair type_ids_isopen;
            ReturnCode_t return_code_isopen {eprosima::fastdds::dds::RETCODE_OK};
            return_code_isopen =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_bool", type_ids_isopen);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_isopen)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "isopen Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_isopen = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_isopen = 0x00000003;
            bool common_isopen_ec {false};
            CommonStructMember common_isopen {TypeObjectUtils::build_common_struct_member(member_id_isopen, member_flags_isopen, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_isopen, common_isopen_ec))};
            if (!common_isopen_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure isopen member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_isopen = "isopen";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_isopen;
            ann_custom_FCVType.reset();
            CompleteMemberDetail detail_isopen = TypeObjectUtils::build_complete_member_detail(name_isopen, member_ann_builtin_isopen, ann_custom_FCVType);
            CompleteStructMember member_isopen = TypeObjectUtils::build_complete_struct_member(common_isopen, detail_isopen);
            TypeObjectUtils::add_complete_struct_member(member_seq_FCVType, member_isopen);
        }
        {
            TypeIdentifierPair type_ids_openvalue;
            ReturnCode_t return_code_openvalue {eprosima::fastdds::dds::RETCODE_OK};
            return_code_openvalue =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_float", type_ids_openvalue);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_openvalue)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "openvalue Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_openvalue = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_openvalue = 0x00000004;
            bool common_openvalue_ec {false};
            CommonStructMember common_openvalue {TypeObjectUtils::build_common_struct_member(member_id_openvalue, member_flags_openvalue, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_openvalue, common_openvalue_ec))};
            if (!common_openvalue_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure openvalue member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_openvalue = "openvalue";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_openvalue;
            ann_custom_FCVType.reset();
            CompleteMemberDetail detail_openvalue = TypeObjectUtils::build_complete_member_detail(name_openvalue, member_ann_builtin_openvalue, ann_custom_FCVType);
            CompleteStructMember member_openvalue = TypeObjectUtils::build_complete_struct_member(common_openvalue, detail_openvalue);
            TypeObjectUtils::add_complete_struct_member(member_seq_FCVType, member_openvalue);
        }
        {
            TypeIdentifierPair type_ids_healthlevel;
            ReturnCode_t return_code_healthlevel {eprosima::fastdds::dds::RETCODE_OK};
            return_code_healthlevel =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_float", type_ids_healthlevel);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_healthlevel)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "healthlevel Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_healthlevel = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_healthlevel = 0x00000005;
            bool common_healthlevel_ec {false};
            CommonStructMember common_healthlevel {TypeObjectUtils::build_common_struct_member(member_id_healthlevel, member_flags_healthlevel, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_healthlevel, common_healthlevel_ec))};
            if (!common_healthlevel_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure healthlevel member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_healthlevel = "healthlevel";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_healthlevel;
            ann_custom_FCVType.reset();
            CompleteMemberDetail detail_healthlevel = TypeObjectUtils::build_complete_member_detail(name_healthlevel, member_ann_builtin_healthlevel, ann_custom_FCVType);
            CompleteStructMember member_healthlevel = TypeObjectUtils::build_complete_struct_member(common_healthlevel, detail_healthlevel);
            TypeObjectUtils::add_complete_struct_member(member_seq_FCVType, member_healthlevel);
        }
        CompleteStructType struct_type_FCVType = TypeObjectUtils::build_complete_struct_type(struct_flags_FCVType, header_FCVType, member_seq_FCVType);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_FCVType, type_name_FCVType.to_string(), type_ids_FCVType))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "FCVType already registered in TypeObjectRegistry for a different type.");
        }
    }
}

