// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file dsf_define_node.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef FAST_DDS_GENERATED__DSF_NODE_DSF_DEFINE_NODE_HPP
#define FAST_DDS_GENERATED__DSF_NODE_DSF_DEFINE_NODE_HPP

#include <cstdint>
#include <string>
#include <utility>
#include <fastcdr/cdr/fixed_size_string.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include "dsf_define_datatypes.hpp"

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(DSF_DEFINE_NODE_SOURCE)
#define DSF_DEFINE_NODE_DllAPI __declspec( dllexport )
#else
#define DSF_DEFINE_NODE_DllAPI __declspec( dllimport )
#endif // DSF_DEFINE_NODE_SOURCE
#else
#define DSF_DEFINE_NODE_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define DSF_DEFINE_NODE_DllAPI
#endif // _WIN32

namespace DSF {

namespace Node {

const std::string NODE_BASICINFO_TOPIC_NAME = "dsf/node/basicInfo";
const std::string NODE_RUNTIMEINFO_TOPIC_NAME = "dsf/node/runtimeInfo";
const std::string BASICINFO_TYPE_NAME = "DSF::Node::BasicInfo";
const std::string RUNTIMEINFO_TYPE_NAME = "DSF::Node::RuntimeInfo";
/*!
 * @brief This class represents the structure BasicInfo defined by the user in the IDL file.
 * @ingroup dsf_define_node
 */
class BasicInfo
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport BasicInfo()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~BasicInfo()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object BasicInfo that will be copied.
     */
    eProsima_user_DllExport BasicInfo(
            const BasicInfo& x)
    {
                    m_name = x.m_name;

                    m_description = x.m_description;

                    m_version = x.m_version;

                    m_pubtime = x.m_pubtime;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object BasicInfo that will be copied.
     */
    eProsima_user_DllExport BasicInfo(
            BasicInfo&& x) noexcept
    {
        m_name = std::move(x.m_name);
        m_description = std::move(x.m_description);
        m_version = std::move(x.m_version);
        m_pubtime = std::move(x.m_pubtime);
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object BasicInfo that will be copied.
     */
    eProsima_user_DllExport BasicInfo& operator =(
            const BasicInfo& x)
    {

                    m_name = x.m_name;

                    m_description = x.m_description;

                    m_version = x.m_version;

                    m_pubtime = x.m_pubtime;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object BasicInfo that will be copied.
     */
    eProsima_user_DllExport BasicInfo& operator =(
            BasicInfo&& x) noexcept
    {

        m_name = std::move(x.m_name);
        m_description = std::move(x.m_description);
        m_version = std::move(x.m_version);
        m_pubtime = std::move(x.m_pubtime);
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x BasicInfo object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const BasicInfo& x) const
    {
        return (m_name == x.m_name &&
           m_description == x.m_description &&
           m_version == x.m_version &&
           m_pubtime == x.m_pubtime);
    }

    /*!
     * @brief Comparison operator.
     * @param x BasicInfo object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const BasicInfo& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function copies the value in member name
     * @param _name New value to be copied in member name
     */
    eProsima_user_DllExport void name(
            const std::string& _name)
    {
        m_name = _name;
    }

    /*!
     * @brief This function moves the value in member name
     * @param _name New value to be moved in member name
     */
    eProsima_user_DllExport void name(
            std::string&& _name)
    {
        m_name = std::move(_name);
    }

    /*!
     * @brief This function returns a constant reference to member name
     * @return Constant reference to member name
     */
    eProsima_user_DllExport const std::string& name() const
    {
        return m_name;
    }

    /*!
     * @brief This function returns a reference to member name
     * @return Reference to member name
     */
    eProsima_user_DllExport std::string& name()
    {
        return m_name;
    }


    /*!
     * @brief This function copies the value in member description
     * @param _description New value to be copied in member description
     */
    eProsima_user_DllExport void description(
            const std::string& _description)
    {
        m_description = _description;
    }

    /*!
     * @brief This function moves the value in member description
     * @param _description New value to be moved in member description
     */
    eProsima_user_DllExport void description(
            std::string&& _description)
    {
        m_description = std::move(_description);
    }

    /*!
     * @brief This function returns a constant reference to member description
     * @return Constant reference to member description
     */
    eProsima_user_DllExport const std::string& description() const
    {
        return m_description;
    }

    /*!
     * @brief This function returns a reference to member description
     * @return Reference to member description
     */
    eProsima_user_DllExport std::string& description()
    {
        return m_description;
    }


    /*!
     * @brief This function copies the value in member version
     * @param _version New value to be copied in member version
     */
    eProsima_user_DllExport void version(
            const std::string& _version)
    {
        m_version = _version;
    }

    /*!
     * @brief This function moves the value in member version
     * @param _version New value to be moved in member version
     */
    eProsima_user_DllExport void version(
            std::string&& _version)
    {
        m_version = std::move(_version);
    }

    /*!
     * @brief This function returns a constant reference to member version
     * @return Constant reference to member version
     */
    eProsima_user_DllExport const std::string& version() const
    {
        return m_version;
    }

    /*!
     * @brief This function returns a reference to member version
     * @return Reference to member version
     */
    eProsima_user_DllExport std::string& version()
    {
        return m_version;
    }


    /*!
     * @brief This function copies the value in member pubtime
     * @param _pubtime New value to be copied in member pubtime
     */
    eProsima_user_DllExport void pubtime(
            const DSF::Timespec& _pubtime)
    {
        m_pubtime = _pubtime;
    }

    /*!
     * @brief This function moves the value in member pubtime
     * @param _pubtime New value to be moved in member pubtime
     */
    eProsima_user_DllExport void pubtime(
            DSF::Timespec&& _pubtime)
    {
        m_pubtime = std::move(_pubtime);
    }

    /*!
     * @brief This function returns a constant reference to member pubtime
     * @return Constant reference to member pubtime
     */
    eProsima_user_DllExport const DSF::Timespec& pubtime() const
    {
        return m_pubtime;
    }

    /*!
     * @brief This function returns a reference to member pubtime
     * @return Reference to member pubtime
     */
    eProsima_user_DllExport DSF::Timespec& pubtime()
    {
        return m_pubtime;
    }



private:

    std::string m_name;
    std::string m_description;
    std::string m_version;
    DSF::Timespec m_pubtime;

};
/*!
 * @brief This class represents the structure RuntimeInfo defined by the user in the IDL file.
 * @ingroup dsf_define_node
 */
class RuntimeInfo
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport RuntimeInfo()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~RuntimeInfo()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object RuntimeInfo that will be copied.
     */
    eProsima_user_DllExport RuntimeInfo(
            const RuntimeInfo& x)
    {
                    m_processid = x.m_processid;

                    m_hostname = x.m_hostname;

                    m_exe_filepath = x.m_exe_filepath;

                    m_execution_timestamp = x.m_execution_timestamp;

                    m_username = x.m_username;

                    m_publicaddress = x.m_publicaddress;

                    m_properities = x.m_properities;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object RuntimeInfo that will be copied.
     */
    eProsima_user_DllExport RuntimeInfo(
            RuntimeInfo&& x) noexcept
    {
        m_processid = std::move(x.m_processid);
        m_hostname = std::move(x.m_hostname);
        m_exe_filepath = std::move(x.m_exe_filepath);
        m_execution_timestamp = std::move(x.m_execution_timestamp);
        m_username = std::move(x.m_username);
        m_publicaddress = std::move(x.m_publicaddress);
        m_properities = std::move(x.m_properities);
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object RuntimeInfo that will be copied.
     */
    eProsima_user_DllExport RuntimeInfo& operator =(
            const RuntimeInfo& x)
    {

                    m_processid = x.m_processid;

                    m_hostname = x.m_hostname;

                    m_exe_filepath = x.m_exe_filepath;

                    m_execution_timestamp = x.m_execution_timestamp;

                    m_username = x.m_username;

                    m_publicaddress = x.m_publicaddress;

                    m_properities = x.m_properities;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object RuntimeInfo that will be copied.
     */
    eProsima_user_DllExport RuntimeInfo& operator =(
            RuntimeInfo&& x) noexcept
    {

        m_processid = std::move(x.m_processid);
        m_hostname = std::move(x.m_hostname);
        m_exe_filepath = std::move(x.m_exe_filepath);
        m_execution_timestamp = std::move(x.m_execution_timestamp);
        m_username = std::move(x.m_username);
        m_publicaddress = std::move(x.m_publicaddress);
        m_properities = std::move(x.m_properities);
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x RuntimeInfo object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const RuntimeInfo& x) const
    {
        return (m_processid == x.m_processid &&
           m_hostname == x.m_hostname &&
           m_exe_filepath == x.m_exe_filepath &&
           m_execution_timestamp == x.m_execution_timestamp &&
           m_username == x.m_username &&
           m_publicaddress == x.m_publicaddress &&
           m_properities == x.m_properities);
    }

    /*!
     * @brief Comparison operator.
     * @param x RuntimeInfo object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const RuntimeInfo& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function copies the value in member processid
     * @param _processid New value to be copied in member processid
     */
    eProsima_user_DllExport void processid(
            const std::string& _processid)
    {
        m_processid = _processid;
    }

    /*!
     * @brief This function moves the value in member processid
     * @param _processid New value to be moved in member processid
     */
    eProsima_user_DllExport void processid(
            std::string&& _processid)
    {
        m_processid = std::move(_processid);
    }

    /*!
     * @brief This function returns a constant reference to member processid
     * @return Constant reference to member processid
     */
    eProsima_user_DllExport const std::string& processid() const
    {
        return m_processid;
    }

    /*!
     * @brief This function returns a reference to member processid
     * @return Reference to member processid
     */
    eProsima_user_DllExport std::string& processid()
    {
        return m_processid;
    }


    /*!
     * @brief This function copies the value in member hostname
     * @param _hostname New value to be copied in member hostname
     */
    eProsima_user_DllExport void hostname(
            const std::string& _hostname)
    {
        m_hostname = _hostname;
    }

    /*!
     * @brief This function moves the value in member hostname
     * @param _hostname New value to be moved in member hostname
     */
    eProsima_user_DllExport void hostname(
            std::string&& _hostname)
    {
        m_hostname = std::move(_hostname);
    }

    /*!
     * @brief This function returns a constant reference to member hostname
     * @return Constant reference to member hostname
     */
    eProsima_user_DllExport const std::string& hostname() const
    {
        return m_hostname;
    }

    /*!
     * @brief This function returns a reference to member hostname
     * @return Reference to member hostname
     */
    eProsima_user_DllExport std::string& hostname()
    {
        return m_hostname;
    }


    /*!
     * @brief This function copies the value in member exe_filepath
     * @param _exe_filepath New value to be copied in member exe_filepath
     */
    eProsima_user_DllExport void exe_filepath(
            const std::string& _exe_filepath)
    {
        m_exe_filepath = _exe_filepath;
    }

    /*!
     * @brief This function moves the value in member exe_filepath
     * @param _exe_filepath New value to be moved in member exe_filepath
     */
    eProsima_user_DllExport void exe_filepath(
            std::string&& _exe_filepath)
    {
        m_exe_filepath = std::move(_exe_filepath);
    }

    /*!
     * @brief This function returns a constant reference to member exe_filepath
     * @return Constant reference to member exe_filepath
     */
    eProsima_user_DllExport const std::string& exe_filepath() const
    {
        return m_exe_filepath;
    }

    /*!
     * @brief This function returns a reference to member exe_filepath
     * @return Reference to member exe_filepath
     */
    eProsima_user_DllExport std::string& exe_filepath()
    {
        return m_exe_filepath;
    }


    /*!
     * @brief This function copies the value in member execution_timestamp
     * @param _execution_timestamp New value to be copied in member execution_timestamp
     */
    eProsima_user_DllExport void execution_timestamp(
            const DSF::Timespec& _execution_timestamp)
    {
        m_execution_timestamp = _execution_timestamp;
    }

    /*!
     * @brief This function moves the value in member execution_timestamp
     * @param _execution_timestamp New value to be moved in member execution_timestamp
     */
    eProsima_user_DllExport void execution_timestamp(
            DSF::Timespec&& _execution_timestamp)
    {
        m_execution_timestamp = std::move(_execution_timestamp);
    }

    /*!
     * @brief This function returns a constant reference to member execution_timestamp
     * @return Constant reference to member execution_timestamp
     */
    eProsima_user_DllExport const DSF::Timespec& execution_timestamp() const
    {
        return m_execution_timestamp;
    }

    /*!
     * @brief This function returns a reference to member execution_timestamp
     * @return Reference to member execution_timestamp
     */
    eProsima_user_DllExport DSF::Timespec& execution_timestamp()
    {
        return m_execution_timestamp;
    }


    /*!
     * @brief This function copies the value in member username
     * @param _username New value to be copied in member username
     */
    eProsima_user_DllExport void username(
            const std::string& _username)
    {
        m_username = _username;
    }

    /*!
     * @brief This function moves the value in member username
     * @param _username New value to be moved in member username
     */
    eProsima_user_DllExport void username(
            std::string&& _username)
    {
        m_username = std::move(_username);
    }

    /*!
     * @brief This function returns a constant reference to member username
     * @return Constant reference to member username
     */
    eProsima_user_DllExport const std::string& username() const
    {
        return m_username;
    }

    /*!
     * @brief This function returns a reference to member username
     * @return Reference to member username
     */
    eProsima_user_DllExport std::string& username()
    {
        return m_username;
    }


    /*!
     * @brief This function copies the value in member publicaddress
     * @param _publicaddress New value to be copied in member publicaddress
     */
    eProsima_user_DllExport void publicaddress(
            const std::string& _publicaddress)
    {
        m_publicaddress = _publicaddress;
    }

    /*!
     * @brief This function moves the value in member publicaddress
     * @param _publicaddress New value to be moved in member publicaddress
     */
    eProsima_user_DllExport void publicaddress(
            std::string&& _publicaddress)
    {
        m_publicaddress = std::move(_publicaddress);
    }

    /*!
     * @brief This function returns a constant reference to member publicaddress
     * @return Constant reference to member publicaddress
     */
    eProsima_user_DllExport const std::string& publicaddress() const
    {
        return m_publicaddress;
    }

    /*!
     * @brief This function returns a reference to member publicaddress
     * @return Reference to member publicaddress
     */
    eProsima_user_DllExport std::string& publicaddress()
    {
        return m_publicaddress;
    }


    /*!
     * @brief This function copies the value in member properities
     * @param _properities New value to be copied in member properities
     */
    eProsima_user_DllExport void properities(
            const eprosima::fastcdr::optional<DSF::NamedValue>& _properities)
    {
        m_properities = _properities;
    }

    /*!
     * @brief This function moves the value in member properities
     * @param _properities New value to be moved in member properities
     */
    eProsima_user_DllExport void properities(
            eprosima::fastcdr::optional<DSF::NamedValue>&& _properities)
    {
        m_properities = std::move(_properities);
    }

    /*!
     * @brief This function returns a constant reference to member properities
     * @return Constant reference to member properities
     */
    eProsima_user_DllExport const eprosima::fastcdr::optional<DSF::NamedValue>& properities() const
    {
        return m_properities;
    }

    /*!
     * @brief This function returns a reference to member properities
     * @return Reference to member properities
     */
    eProsima_user_DllExport eprosima::fastcdr::optional<DSF::NamedValue>& properities()
    {
        return m_properities;
    }



private:

    std::string m_processid;
    std::string m_hostname;
    std::string m_exe_filepath;
    DSF::Timespec m_execution_timestamp;
    std::string m_username;
    std::string m_publicaddress;
    eprosima::fastcdr::optional<DSF::NamedValue> m_properities;

};
const std::string DSF_NODE_BASICINFO_NAME = "dsf.node.basicinfo.name";
const std::string DSF_NODE_BASICINFO_DESCRIPTION = "dsf.node.basicinfo.description";
const std::string DSF_NODE_BASICINFO_VERSION = "dsf.node.basicinfo.version";
const std::string DSF_NODE_BASICINFO_PUBTIME = "dsf.node.basicinfo.pubtime";
const std::string DSF_NODE_RUNTIMEINFO_PROCESSID = "dsf.node.runtimeinfo.processid";
const std::string DSF_NODE_RUNTIMEINFO_HOSTNAME = "dsf.node.runtimeinfo.hostname";
const std::string DSF_NODE_RUNTIMEINFO_EXE_FILEPATH = "dsf.node.runtimeinfo.exe_filepath";
const std::string DSF_NODE_RUNTIMEINFO_EXECUTION_TIMESTAMP = "dsf.node.runtimeinfo.execution_timestamp";
const std::string DSF_NODE_RUNTIMEINFO_USERNAME = "dsf.node.runtimeinfo.username";
const std::string DSF_NODE_RUNTIMEINFO_PUBLICADDRESS = "dsf.node.runtimeinfo.publicaddress";

} // namespace Node

} // namespace DSF

#endif // _FAST_DDS_GENERATED_DSF_NODE_DSF_DEFINE_NODE_HPP_


