// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file dsf_define_messagesPubSubTypes.cpp
 * This header file contains the implementation of the serialization functions.
 *
 * This file was generated by the tool fastddsgen.
 */

#include "dsf_define_messagesPubSubTypes.hpp"

#include <fastdds/dds/log/Log.hpp>
#include <fastdds/rtps/common/CdrSerialization.hpp>

#include "dsf_define_messagesCdrAux.hpp"
#include "dsf_define_messagesTypeObjectSupport.hpp"

using SerializedPayload_t = eprosima::fastdds::rtps::SerializedPayload_t;
using InstanceHandle_t = eprosima::fastdds::rtps::InstanceHandle_t;
using DataRepresentationId_t = eprosima::fastdds::dds::DataRepresentationId_t;

namespace DSF {
    namespace Message {
        EventPubSubType::EventPubSubType()
        {
            set_name("DSF::Message::Event");
            uint32_t type_size = DSF_Message_Event_max_cdr_typesize;
            type_size += static_cast<uint32_t>(eprosima::fastcdr::Cdr::alignment(type_size, 4)); /* possible submessage alignment */
            max_serialized_type_size = type_size + 4; /*encapsulation*/
            is_compute_key_provided = true;
            uint32_t key_length = DSF_Message_Event_max_key_cdr_typesize > 16 ? DSF_Message_Event_max_key_cdr_typesize : 16;
            key_buffer_ = reinterpret_cast<unsigned char*>(malloc(key_length));
            memset(key_buffer_, 0, key_length);
        }

        EventPubSubType::~EventPubSubType()
        {
            if (key_buffer_ != nullptr)
            {
                free(key_buffer_);
            }
        }

        bool EventPubSubType::serialize(
                const void* const data,
                SerializedPayload_t& payload,
                DataRepresentationId_t data_representation)
        {
            const Event* p_type = static_cast<const Event*>(data);

            // Object that manages the raw buffer.
            eprosima::fastcdr::FastBuffer fastbuffer(reinterpret_cast<char*>(payload.data), payload.max_size);
            // Object that serializes the data.
            eprosima::fastcdr::Cdr ser(fastbuffer, eprosima::fastcdr::Cdr::DEFAULT_ENDIAN,
                    data_representation == DataRepresentationId_t::XCDR_DATA_REPRESENTATION ?
                    eprosima::fastcdr::CdrVersion::XCDRv1 : eprosima::fastcdr::CdrVersion::XCDRv2);
            payload.encapsulation = ser.endianness() == eprosima::fastcdr::Cdr::BIG_ENDIANNESS ? CDR_BE : CDR_LE;
            ser.set_encoding_flag(
                data_representation == DataRepresentationId_t::XCDR_DATA_REPRESENTATION ?
                eprosima::fastcdr::EncodingAlgorithmFlag::PLAIN_CDR  :
                eprosima::fastcdr::EncodingAlgorithmFlag::DELIMIT_CDR2);

            try
            {
                // Serialize encapsulation
                ser.serialize_encapsulation();
                // Serialize the object.
                ser << *p_type;
                ser.set_dds_cdr_options({0,0});
            }
            catch (eprosima::fastcdr::exception::Exception& /*exception*/)
            {
                return false;
            }

            // Get the serialized length
            payload.length = static_cast<uint32_t>(ser.get_serialized_data_length());
            return true;
        }

        bool EventPubSubType::deserialize(
                SerializedPayload_t& payload,
                void* data)
        {
            try
            {
                // Convert DATA to pointer of your type
                Event* p_type = static_cast<Event*>(data);

                // Object that manages the raw buffer.
                eprosima::fastcdr::FastBuffer fastbuffer(reinterpret_cast<char*>(payload.data), payload.length);

                // Object that deserializes the data.
                eprosima::fastcdr::Cdr deser(fastbuffer, eprosima::fastcdr::Cdr::DEFAULT_ENDIAN);

                // Deserialize encapsulation.
                deser.read_encapsulation();
                payload.encapsulation = deser.endianness() == eprosima::fastcdr::Cdr::BIG_ENDIANNESS ? CDR_BE : CDR_LE;

                // Deserialize the object.
                deser >> *p_type;
            }
            catch (eprosima::fastcdr::exception::Exception& /*exception*/)
            {
                return false;
            }

            return true;
        }

        uint32_t EventPubSubType::calculate_serialized_size(
                const void* const data,
                DataRepresentationId_t data_representation)
        {
            try
            {
                eprosima::fastcdr::CdrSizeCalculator calculator(
                    data_representation == DataRepresentationId_t::XCDR_DATA_REPRESENTATION ?
                    eprosima::fastcdr::CdrVersion::XCDRv1 :eprosima::fastcdr::CdrVersion::XCDRv2);
                size_t current_alignment {0};
                return static_cast<uint32_t>(calculator.calculate_serialized_size(
                            *static_cast<const Event*>(data), current_alignment)) +
                        4u /*encapsulation*/;
            }
            catch (eprosima::fastcdr::exception::Exception& /*exception*/)
            {
                return 0;
            }
        }

        void* EventPubSubType::create_data()
        {
            return reinterpret_cast<void*>(new Event());
        }

        void EventPubSubType::delete_data(
                void* data)
        {
            delete(reinterpret_cast<Event*>(data));
        }

        bool EventPubSubType::compute_key(
                SerializedPayload_t& payload,
                InstanceHandle_t& handle,
                bool force_md5)
        {
            if (!is_compute_key_provided)
            {
                return false;
            }

            Event data;
            if (deserialize(payload, static_cast<void*>(&data)))
            {
                return compute_key(static_cast<void*>(&data), handle, force_md5);
            }

            return false;
        }

        bool EventPubSubType::compute_key(
                const void* const data,
                InstanceHandle_t& handle,
                bool force_md5)
        {
            if (!is_compute_key_provided)
            {
                return false;
            }

            const Event* p_type = static_cast<const Event*>(data);

            // Object that manages the raw buffer.
            eprosima::fastcdr::FastBuffer fastbuffer(reinterpret_cast<char*>(key_buffer_),
                    DSF_Message_Event_max_key_cdr_typesize);

            // Object that serializes the data.
            eprosima::fastcdr::Cdr ser(fastbuffer, eprosima::fastcdr::Cdr::BIG_ENDIANNESS, eprosima::fastcdr::CdrVersion::XCDRv2);
            ser.set_encoding_flag(eprosima::fastcdr::EncodingAlgorithmFlag::PLAIN_CDR2);
            eprosima::fastcdr::serialize_key(ser, *p_type);
            if (force_md5 || DSF_Message_Event_max_key_cdr_typesize > 16)
            {
                md5_.init();
                md5_.update(key_buffer_, static_cast<unsigned int>(ser.get_serialized_data_length()));
                md5_.finalize();
                for (uint8_t i = 0; i < 16; ++i)
                {
                    handle.value[i] = md5_.digest[i];
                }
            }
            else
            {
                for (uint8_t i = 0; i < 16; ++i)
                {
                    handle.value[i] = key_buffer_[i];
                }
            }
            return true;
        }

        void EventPubSubType::register_type_object_representation()
        {
            register_Event_type_identifier(type_identifiers_);
        }

        EventTransferPubSubType::EventTransferPubSubType()
        {
            set_name("DSF::Message::EventTransfer");
            uint32_t type_size = DSF_Message_EventTransfer_max_cdr_typesize;
            type_size += static_cast<uint32_t>(eprosima::fastcdr::Cdr::alignment(type_size, 4)); /* possible submessage alignment */
            max_serialized_type_size = type_size + 4; /*encapsulation*/
            is_compute_key_provided = true;
            uint32_t key_length = DSF_Message_EventTransfer_max_key_cdr_typesize > 16 ? DSF_Message_EventTransfer_max_key_cdr_typesize : 16;
            key_buffer_ = reinterpret_cast<unsigned char*>(malloc(key_length));
            memset(key_buffer_, 0, key_length);
        }

        EventTransferPubSubType::~EventTransferPubSubType()
        {
            if (key_buffer_ != nullptr)
            {
                free(key_buffer_);
            }
        }

        bool EventTransferPubSubType::serialize(
                const void* const data,
                SerializedPayload_t& payload,
                DataRepresentationId_t data_representation)
        {
            const EventTransfer* p_type = static_cast<const EventTransfer*>(data);

            // Object that manages the raw buffer.
            eprosima::fastcdr::FastBuffer fastbuffer(reinterpret_cast<char*>(payload.data), payload.max_size);
            // Object that serializes the data.
            eprosima::fastcdr::Cdr ser(fastbuffer, eprosima::fastcdr::Cdr::DEFAULT_ENDIAN,
                    data_representation == DataRepresentationId_t::XCDR_DATA_REPRESENTATION ?
                    eprosima::fastcdr::CdrVersion::XCDRv1 : eprosima::fastcdr::CdrVersion::XCDRv2);
            payload.encapsulation = ser.endianness() == eprosima::fastcdr::Cdr::BIG_ENDIANNESS ? CDR_BE : CDR_LE;
            ser.set_encoding_flag(
                data_representation == DataRepresentationId_t::XCDR_DATA_REPRESENTATION ?
                eprosima::fastcdr::EncodingAlgorithmFlag::PLAIN_CDR  :
                eprosima::fastcdr::EncodingAlgorithmFlag::DELIMIT_CDR2);

            try
            {
                // Serialize encapsulation
                ser.serialize_encapsulation();
                // Serialize the object.
                ser << *p_type;
                ser.set_dds_cdr_options({0,0});
            }
            catch (eprosima::fastcdr::exception::Exception& /*exception*/)
            {
                return false;
            }

            // Get the serialized length
            payload.length = static_cast<uint32_t>(ser.get_serialized_data_length());
            return true;
        }

        bool EventTransferPubSubType::deserialize(
                SerializedPayload_t& payload,
                void* data)
        {
            try
            {
                // Convert DATA to pointer of your type
                EventTransfer* p_type = static_cast<EventTransfer*>(data);

                // Object that manages the raw buffer.
                eprosima::fastcdr::FastBuffer fastbuffer(reinterpret_cast<char*>(payload.data), payload.length);

                // Object that deserializes the data.
                eprosima::fastcdr::Cdr deser(fastbuffer, eprosima::fastcdr::Cdr::DEFAULT_ENDIAN);

                // Deserialize encapsulation.
                deser.read_encapsulation();
                payload.encapsulation = deser.endianness() == eprosima::fastcdr::Cdr::BIG_ENDIANNESS ? CDR_BE : CDR_LE;

                // Deserialize the object.
                deser >> *p_type;
            }
            catch (eprosima::fastcdr::exception::Exception& /*exception*/)
            {
                return false;
            }

            return true;
        }

        uint32_t EventTransferPubSubType::calculate_serialized_size(
                const void* const data,
                DataRepresentationId_t data_representation)
        {
            try
            {
                eprosima::fastcdr::CdrSizeCalculator calculator(
                    data_representation == DataRepresentationId_t::XCDR_DATA_REPRESENTATION ?
                    eprosima::fastcdr::CdrVersion::XCDRv1 :eprosima::fastcdr::CdrVersion::XCDRv2);
                size_t current_alignment {0};
                return static_cast<uint32_t>(calculator.calculate_serialized_size(
                            *static_cast<const EventTransfer*>(data), current_alignment)) +
                        4u /*encapsulation*/;
            }
            catch (eprosima::fastcdr::exception::Exception& /*exception*/)
            {
                return 0;
            }
        }

        void* EventTransferPubSubType::create_data()
        {
            return reinterpret_cast<void*>(new EventTransfer());
        }

        void EventTransferPubSubType::delete_data(
                void* data)
        {
            delete(reinterpret_cast<EventTransfer*>(data));
        }

        bool EventTransferPubSubType::compute_key(
                SerializedPayload_t& payload,
                InstanceHandle_t& handle,
                bool force_md5)
        {
            if (!is_compute_key_provided)
            {
                return false;
            }

            EventTransfer data;
            if (deserialize(payload, static_cast<void*>(&data)))
            {
                return compute_key(static_cast<void*>(&data), handle, force_md5);
            }

            return false;
        }

        bool EventTransferPubSubType::compute_key(
                const void* const data,
                InstanceHandle_t& handle,
                bool force_md5)
        {
            if (!is_compute_key_provided)
            {
                return false;
            }

            const EventTransfer* p_type = static_cast<const EventTransfer*>(data);

            // Object that manages the raw buffer.
            eprosima::fastcdr::FastBuffer fastbuffer(reinterpret_cast<char*>(key_buffer_),
                    DSF_Message_EventTransfer_max_key_cdr_typesize);

            // Object that serializes the data.
            eprosima::fastcdr::Cdr ser(fastbuffer, eprosima::fastcdr::Cdr::BIG_ENDIANNESS, eprosima::fastcdr::CdrVersion::XCDRv2);
            ser.set_encoding_flag(eprosima::fastcdr::EncodingAlgorithmFlag::PLAIN_CDR2);
            eprosima::fastcdr::serialize_key(ser, *p_type);
            if (force_md5 || DSF_Message_EventTransfer_max_key_cdr_typesize > 16)
            {
                md5_.init();
                md5_.update(key_buffer_, static_cast<unsigned int>(ser.get_serialized_data_length()));
                md5_.finalize();
                for (uint8_t i = 0; i < 16; ++i)
                {
                    handle.value[i] = md5_.digest[i];
                }
            }
            else
            {
                for (uint8_t i = 0; i < 16; ++i)
                {
                    handle.value[i] = key_buffer_[i];
                }
            }
            return true;
        }

        void EventTransferPubSubType::register_type_object_representation()
        {
            register_EventTransfer_type_identifier(type_identifiers_);
        }

        NamedBlobPubSubType::NamedBlobPubSubType()
        {
            set_name("DSF::Message::NamedBlob");
            uint32_t type_size = DSF_Message_NamedBlob_max_cdr_typesize;
            type_size += static_cast<uint32_t>(eprosima::fastcdr::Cdr::alignment(type_size, 4)); /* possible submessage alignment */
            max_serialized_type_size = type_size + 4; /*encapsulation*/
            is_compute_key_provided = false;
            uint32_t key_length = DSF_Message_NamedBlob_max_key_cdr_typesize > 16 ? DSF_Message_NamedBlob_max_key_cdr_typesize : 16;
            key_buffer_ = reinterpret_cast<unsigned char*>(malloc(key_length));
            memset(key_buffer_, 0, key_length);
        }

        NamedBlobPubSubType::~NamedBlobPubSubType()
        {
            if (key_buffer_ != nullptr)
            {
                free(key_buffer_);
            }
        }

        bool NamedBlobPubSubType::serialize(
                const void* const data,
                SerializedPayload_t& payload,
                DataRepresentationId_t data_representation)
        {
            const NamedBlob* p_type = static_cast<const NamedBlob*>(data);

            // Object that manages the raw buffer.
            eprosima::fastcdr::FastBuffer fastbuffer(reinterpret_cast<char*>(payload.data), payload.max_size);
            // Object that serializes the data.
            eprosima::fastcdr::Cdr ser(fastbuffer, eprosima::fastcdr::Cdr::DEFAULT_ENDIAN,
                    data_representation == DataRepresentationId_t::XCDR_DATA_REPRESENTATION ?
                    eprosima::fastcdr::CdrVersion::XCDRv1 : eprosima::fastcdr::CdrVersion::XCDRv2);
            payload.encapsulation = ser.endianness() == eprosima::fastcdr::Cdr::BIG_ENDIANNESS ? CDR_BE : CDR_LE;
            ser.set_encoding_flag(
                data_representation == DataRepresentationId_t::XCDR_DATA_REPRESENTATION ?
                eprosima::fastcdr::EncodingAlgorithmFlag::PLAIN_CDR  :
                eprosima::fastcdr::EncodingAlgorithmFlag::DELIMIT_CDR2);

            try
            {
                // Serialize encapsulation
                ser.serialize_encapsulation();
                // Serialize the object.
                ser << *p_type;
                ser.set_dds_cdr_options({0,0});
            }
            catch (eprosima::fastcdr::exception::Exception& /*exception*/)
            {
                return false;
            }

            // Get the serialized length
            payload.length = static_cast<uint32_t>(ser.get_serialized_data_length());
            return true;
        }

        bool NamedBlobPubSubType::deserialize(
                SerializedPayload_t& payload,
                void* data)
        {
            try
            {
                // Convert DATA to pointer of your type
                NamedBlob* p_type = static_cast<NamedBlob*>(data);

                // Object that manages the raw buffer.
                eprosima::fastcdr::FastBuffer fastbuffer(reinterpret_cast<char*>(payload.data), payload.length);

                // Object that deserializes the data.
                eprosima::fastcdr::Cdr deser(fastbuffer, eprosima::fastcdr::Cdr::DEFAULT_ENDIAN);

                // Deserialize encapsulation.
                deser.read_encapsulation();
                payload.encapsulation = deser.endianness() == eprosima::fastcdr::Cdr::BIG_ENDIANNESS ? CDR_BE : CDR_LE;

                // Deserialize the object.
                deser >> *p_type;
            }
            catch (eprosima::fastcdr::exception::Exception& /*exception*/)
            {
                return false;
            }

            return true;
        }

        uint32_t NamedBlobPubSubType::calculate_serialized_size(
                const void* const data,
                DataRepresentationId_t data_representation)
        {
            try
            {
                eprosima::fastcdr::CdrSizeCalculator calculator(
                    data_representation == DataRepresentationId_t::XCDR_DATA_REPRESENTATION ?
                    eprosima::fastcdr::CdrVersion::XCDRv1 :eprosima::fastcdr::CdrVersion::XCDRv2);
                size_t current_alignment {0};
                return static_cast<uint32_t>(calculator.calculate_serialized_size(
                            *static_cast<const NamedBlob*>(data), current_alignment)) +
                        4u /*encapsulation*/;
            }
            catch (eprosima::fastcdr::exception::Exception& /*exception*/)
            {
                return 0;
            }
        }

        void* NamedBlobPubSubType::create_data()
        {
            return reinterpret_cast<void*>(new NamedBlob());
        }

        void NamedBlobPubSubType::delete_data(
                void* data)
        {
            delete(reinterpret_cast<NamedBlob*>(data));
        }

        bool NamedBlobPubSubType::compute_key(
                SerializedPayload_t& payload,
                InstanceHandle_t& handle,
                bool force_md5)
        {
            if (!is_compute_key_provided)
            {
                return false;
            }

            NamedBlob data;
            if (deserialize(payload, static_cast<void*>(&data)))
            {
                return compute_key(static_cast<void*>(&data), handle, force_md5);
            }

            return false;
        }

        bool NamedBlobPubSubType::compute_key(
                const void* const data,
                InstanceHandle_t& handle,
                bool force_md5)
        {
            if (!is_compute_key_provided)
            {
                return false;
            }

            const NamedBlob* p_type = static_cast<const NamedBlob*>(data);

            // Object that manages the raw buffer.
            eprosima::fastcdr::FastBuffer fastbuffer(reinterpret_cast<char*>(key_buffer_),
                    DSF_Message_NamedBlob_max_key_cdr_typesize);

            // Object that serializes the data.
            eprosima::fastcdr::Cdr ser(fastbuffer, eprosima::fastcdr::Cdr::BIG_ENDIANNESS, eprosima::fastcdr::CdrVersion::XCDRv2);
            ser.set_encoding_flag(eprosima::fastcdr::EncodingAlgorithmFlag::PLAIN_CDR2);
            eprosima::fastcdr::serialize_key(ser, *p_type);
            if (force_md5 || DSF_Message_NamedBlob_max_key_cdr_typesize > 16)
            {
                md5_.init();
                md5_.update(key_buffer_, static_cast<unsigned int>(ser.get_serialized_data_length()));
                md5_.finalize();
                for (uint8_t i = 0; i < 16; ++i)
                {
                    handle.value[i] = md5_.digest[i];
                }
            }
            else
            {
                for (uint8_t i = 0; i < 16; ++i)
                {
                    handle.value[i] = key_buffer_[i];
                }
            }
            return true;
        }

        void NamedBlobPubSubType::register_type_object_representation()
        {
            register_NamedBlob_type_identifier(type_identifiers_);
        }

        ControlVarPubSubType::ControlVarPubSubType()
        {
            set_name("DSF::Message::ControlVar");
            uint32_t type_size = DSF_Message_ControlVar_max_cdr_typesize;
            type_size += static_cast<uint32_t>(eprosima::fastcdr::Cdr::alignment(type_size, 4)); /* possible submessage alignment */
            max_serialized_type_size = type_size + 4; /*encapsulation*/
            is_compute_key_provided = false;
            uint32_t key_length = DSF_Message_ControlVar_max_key_cdr_typesize > 16 ? DSF_Message_ControlVar_max_key_cdr_typesize : 16;
            key_buffer_ = reinterpret_cast<unsigned char*>(malloc(key_length));
            memset(key_buffer_, 0, key_length);
        }

        ControlVarPubSubType::~ControlVarPubSubType()
        {
            if (key_buffer_ != nullptr)
            {
                free(key_buffer_);
            }
        }

        bool ControlVarPubSubType::serialize(
                const void* const data,
                SerializedPayload_t& payload,
                DataRepresentationId_t data_representation)
        {
            const ControlVar* p_type = static_cast<const ControlVar*>(data);

            // Object that manages the raw buffer.
            eprosima::fastcdr::FastBuffer fastbuffer(reinterpret_cast<char*>(payload.data), payload.max_size);
            // Object that serializes the data.
            eprosima::fastcdr::Cdr ser(fastbuffer, eprosima::fastcdr::Cdr::DEFAULT_ENDIAN,
                    data_representation == DataRepresentationId_t::XCDR_DATA_REPRESENTATION ?
                    eprosima::fastcdr::CdrVersion::XCDRv1 : eprosima::fastcdr::CdrVersion::XCDRv2);
            payload.encapsulation = ser.endianness() == eprosima::fastcdr::Cdr::BIG_ENDIANNESS ? CDR_BE : CDR_LE;
            ser.set_encoding_flag(
                data_representation == DataRepresentationId_t::XCDR_DATA_REPRESENTATION ?
                eprosima::fastcdr::EncodingAlgorithmFlag::PLAIN_CDR  :
                eprosima::fastcdr::EncodingAlgorithmFlag::DELIMIT_CDR2);

            try
            {
                // Serialize encapsulation
                ser.serialize_encapsulation();
                // Serialize the object.
                ser << *p_type;
                ser.set_dds_cdr_options({0,0});
            }
            catch (eprosima::fastcdr::exception::Exception& /*exception*/)
            {
                return false;
            }

            // Get the serialized length
            payload.length = static_cast<uint32_t>(ser.get_serialized_data_length());
            return true;
        }

        bool ControlVarPubSubType::deserialize(
                SerializedPayload_t& payload,
                void* data)
        {
            try
            {
                // Convert DATA to pointer of your type
                ControlVar* p_type = static_cast<ControlVar*>(data);

                // Object that manages the raw buffer.
                eprosima::fastcdr::FastBuffer fastbuffer(reinterpret_cast<char*>(payload.data), payload.length);

                // Object that deserializes the data.
                eprosima::fastcdr::Cdr deser(fastbuffer, eprosima::fastcdr::Cdr::DEFAULT_ENDIAN);

                // Deserialize encapsulation.
                deser.read_encapsulation();
                payload.encapsulation = deser.endianness() == eprosima::fastcdr::Cdr::BIG_ENDIANNESS ? CDR_BE : CDR_LE;

                // Deserialize the object.
                deser >> *p_type;
            }
            catch (eprosima::fastcdr::exception::Exception& /*exception*/)
            {
                return false;
            }

            return true;
        }

        uint32_t ControlVarPubSubType::calculate_serialized_size(
                const void* const data,
                DataRepresentationId_t data_representation)
        {
            try
            {
                eprosima::fastcdr::CdrSizeCalculator calculator(
                    data_representation == DataRepresentationId_t::XCDR_DATA_REPRESENTATION ?
                    eprosima::fastcdr::CdrVersion::XCDRv1 :eprosima::fastcdr::CdrVersion::XCDRv2);
                size_t current_alignment {0};
                return static_cast<uint32_t>(calculator.calculate_serialized_size(
                            *static_cast<const ControlVar*>(data), current_alignment)) +
                        4u /*encapsulation*/;
            }
            catch (eprosima::fastcdr::exception::Exception& /*exception*/)
            {
                return 0;
            }
        }

        void* ControlVarPubSubType::create_data()
        {
            return reinterpret_cast<void*>(new ControlVar());
        }

        void ControlVarPubSubType::delete_data(
                void* data)
        {
            delete(reinterpret_cast<ControlVar*>(data));
        }

        bool ControlVarPubSubType::compute_key(
                SerializedPayload_t& payload,
                InstanceHandle_t& handle,
                bool force_md5)
        {
            if (!is_compute_key_provided)
            {
                return false;
            }

            ControlVar data;
            if (deserialize(payload, static_cast<void*>(&data)))
            {
                return compute_key(static_cast<void*>(&data), handle, force_md5);
            }

            return false;
        }

        bool ControlVarPubSubType::compute_key(
                const void* const data,
                InstanceHandle_t& handle,
                bool force_md5)
        {
            if (!is_compute_key_provided)
            {
                return false;
            }

            const ControlVar* p_type = static_cast<const ControlVar*>(data);

            // Object that manages the raw buffer.
            eprosima::fastcdr::FastBuffer fastbuffer(reinterpret_cast<char*>(key_buffer_),
                    DSF_Message_ControlVar_max_key_cdr_typesize);

            // Object that serializes the data.
            eprosima::fastcdr::Cdr ser(fastbuffer, eprosima::fastcdr::Cdr::BIG_ENDIANNESS, eprosima::fastcdr::CdrVersion::XCDRv2);
            ser.set_encoding_flag(eprosima::fastcdr::EncodingAlgorithmFlag::PLAIN_CDR2);
            eprosima::fastcdr::serialize_key(ser, *p_type);
            if (force_md5 || DSF_Message_ControlVar_max_key_cdr_typesize > 16)
            {
                md5_.init();
                md5_.update(key_buffer_, static_cast<unsigned int>(ser.get_serialized_data_length()));
                md5_.finalize();
                for (uint8_t i = 0; i < 16; ++i)
                {
                    handle.value[i] = md5_.digest[i];
                }
            }
            else
            {
                for (uint8_t i = 0; i < 16; ++i)
                {
                    handle.value[i] = key_buffer_[i];
                }
            }
            return true;
        }

        void ControlVarPubSubType::register_type_object_representation()
        {
            register_ControlVar_type_identifier(type_identifiers_);
        }

        ControlPubSubType::ControlPubSubType()
        {
            set_name("DSF::Message::Control");
            uint32_t type_size = DSF_Message_Control_max_cdr_typesize;
            type_size += static_cast<uint32_t>(eprosima::fastcdr::Cdr::alignment(type_size, 4)); /* possible submessage alignment */
            max_serialized_type_size = type_size + 4; /*encapsulation*/
            is_compute_key_provided = true;
            uint32_t key_length = DSF_Message_Control_max_key_cdr_typesize > 16 ? DSF_Message_Control_max_key_cdr_typesize : 16;
            key_buffer_ = reinterpret_cast<unsigned char*>(malloc(key_length));
            memset(key_buffer_, 0, key_length);
        }

        ControlPubSubType::~ControlPubSubType()
        {
            if (key_buffer_ != nullptr)
            {
                free(key_buffer_);
            }
        }

        bool ControlPubSubType::serialize(
                const void* const data,
                SerializedPayload_t& payload,
                DataRepresentationId_t data_representation)
        {
            const Control* p_type = static_cast<const Control*>(data);

            // Object that manages the raw buffer.
            eprosima::fastcdr::FastBuffer fastbuffer(reinterpret_cast<char*>(payload.data), payload.max_size);
            // Object that serializes the data.
            eprosima::fastcdr::Cdr ser(fastbuffer, eprosima::fastcdr::Cdr::DEFAULT_ENDIAN,
                    data_representation == DataRepresentationId_t::XCDR_DATA_REPRESENTATION ?
                    eprosima::fastcdr::CdrVersion::XCDRv1 : eprosima::fastcdr::CdrVersion::XCDRv2);
            payload.encapsulation = ser.endianness() == eprosima::fastcdr::Cdr::BIG_ENDIANNESS ? CDR_BE : CDR_LE;
            ser.set_encoding_flag(
                data_representation == DataRepresentationId_t::XCDR_DATA_REPRESENTATION ?
                eprosima::fastcdr::EncodingAlgorithmFlag::PLAIN_CDR  :
                eprosima::fastcdr::EncodingAlgorithmFlag::DELIMIT_CDR2);

            try
            {
                // Serialize encapsulation
                ser.serialize_encapsulation();
                // Serialize the object.
                ser << *p_type;
                ser.set_dds_cdr_options({0,0});
            }
            catch (eprosima::fastcdr::exception::Exception& /*exception*/)
            {
                return false;
            }

            // Get the serialized length
            payload.length = static_cast<uint32_t>(ser.get_serialized_data_length());
            return true;
        }

        bool ControlPubSubType::deserialize(
                SerializedPayload_t& payload,
                void* data)
        {
            try
            {
                // Convert DATA to pointer of your type
                Control* p_type = static_cast<Control*>(data);

                // Object that manages the raw buffer.
                eprosima::fastcdr::FastBuffer fastbuffer(reinterpret_cast<char*>(payload.data), payload.length);

                // Object that deserializes the data.
                eprosima::fastcdr::Cdr deser(fastbuffer, eprosima::fastcdr::Cdr::DEFAULT_ENDIAN);

                // Deserialize encapsulation.
                deser.read_encapsulation();
                payload.encapsulation = deser.endianness() == eprosima::fastcdr::Cdr::BIG_ENDIANNESS ? CDR_BE : CDR_LE;

                // Deserialize the object.
                deser >> *p_type;
            }
            catch (eprosima::fastcdr::exception::Exception& /*exception*/)
            {
                return false;
            }

            return true;
        }

        uint32_t ControlPubSubType::calculate_serialized_size(
                const void* const data,
                DataRepresentationId_t data_representation)
        {
            try
            {
                eprosima::fastcdr::CdrSizeCalculator calculator(
                    data_representation == DataRepresentationId_t::XCDR_DATA_REPRESENTATION ?
                    eprosima::fastcdr::CdrVersion::XCDRv1 :eprosima::fastcdr::CdrVersion::XCDRv2);
                size_t current_alignment {0};
                return static_cast<uint32_t>(calculator.calculate_serialized_size(
                            *static_cast<const Control*>(data), current_alignment)) +
                        4u /*encapsulation*/;
            }
            catch (eprosima::fastcdr::exception::Exception& /*exception*/)
            {
                return 0;
            }
        }

        void* ControlPubSubType::create_data()
        {
            return reinterpret_cast<void*>(new Control());
        }

        void ControlPubSubType::delete_data(
                void* data)
        {
            delete(reinterpret_cast<Control*>(data));
        }

        bool ControlPubSubType::compute_key(
                SerializedPayload_t& payload,
                InstanceHandle_t& handle,
                bool force_md5)
        {
            if (!is_compute_key_provided)
            {
                return false;
            }

            Control data;
            if (deserialize(payload, static_cast<void*>(&data)))
            {
                return compute_key(static_cast<void*>(&data), handle, force_md5);
            }

            return false;
        }

        bool ControlPubSubType::compute_key(
                const void* const data,
                InstanceHandle_t& handle,
                bool force_md5)
        {
            if (!is_compute_key_provided)
            {
                return false;
            }

            const Control* p_type = static_cast<const Control*>(data);

            // Object that manages the raw buffer.
            eprosima::fastcdr::FastBuffer fastbuffer(reinterpret_cast<char*>(key_buffer_),
                    DSF_Message_Control_max_key_cdr_typesize);

            // Object that serializes the data.
            eprosima::fastcdr::Cdr ser(fastbuffer, eprosima::fastcdr::Cdr::BIG_ENDIANNESS, eprosima::fastcdr::CdrVersion::XCDRv2);
            ser.set_encoding_flag(eprosima::fastcdr::EncodingAlgorithmFlag::PLAIN_CDR2);
            eprosima::fastcdr::serialize_key(ser, *p_type);
            if (force_md5 || DSF_Message_Control_max_key_cdr_typesize > 16)
            {
                md5_.init();
                md5_.update(key_buffer_, static_cast<unsigned int>(ser.get_serialized_data_length()));
                md5_.finalize();
                for (uint8_t i = 0; i < 16; ++i)
                {
                    handle.value[i] = md5_.digest[i];
                }
            }
            else
            {
                for (uint8_t i = 0; i < 16; ++i)
                {
                    handle.value[i] = key_buffer_[i];
                }
            }
            return true;
        }

        void ControlPubSubType::register_type_object_representation()
        {
            register_Control_type_identifier(type_identifiers_);
        }

        SubTableRegisterPubSubType::SubTableRegisterPubSubType()
        {
            set_name("DSF::Message::SubTableRegister");
            uint32_t type_size = DSF_Message_SubTableRegister_max_cdr_typesize;
            type_size += static_cast<uint32_t>(eprosima::fastcdr::Cdr::alignment(type_size, 4)); /* possible submessage alignment */
            max_serialized_type_size = type_size + 4; /*encapsulation*/
            is_compute_key_provided = false;
            uint32_t key_length = DSF_Message_SubTableRegister_max_key_cdr_typesize > 16 ? DSF_Message_SubTableRegister_max_key_cdr_typesize : 16;
            key_buffer_ = reinterpret_cast<unsigned char*>(malloc(key_length));
            memset(key_buffer_, 0, key_length);
        }

        SubTableRegisterPubSubType::~SubTableRegisterPubSubType()
        {
            if (key_buffer_ != nullptr)
            {
                free(key_buffer_);
            }
        }

        bool SubTableRegisterPubSubType::serialize(
                const void* const data,
                SerializedPayload_t& payload,
                DataRepresentationId_t data_representation)
        {
            const SubTableRegister* p_type = static_cast<const SubTableRegister*>(data);

            // Object that manages the raw buffer.
            eprosima::fastcdr::FastBuffer fastbuffer(reinterpret_cast<char*>(payload.data), payload.max_size);
            // Object that serializes the data.
            eprosima::fastcdr::Cdr ser(fastbuffer, eprosima::fastcdr::Cdr::DEFAULT_ENDIAN,
                    data_representation == DataRepresentationId_t::XCDR_DATA_REPRESENTATION ?
                    eprosima::fastcdr::CdrVersion::XCDRv1 : eprosima::fastcdr::CdrVersion::XCDRv2);
            payload.encapsulation = ser.endianness() == eprosima::fastcdr::Cdr::BIG_ENDIANNESS ? CDR_BE : CDR_LE;
            ser.set_encoding_flag(
                data_representation == DataRepresentationId_t::XCDR_DATA_REPRESENTATION ?
                eprosima::fastcdr::EncodingAlgorithmFlag::PLAIN_CDR  :
                eprosima::fastcdr::EncodingAlgorithmFlag::DELIMIT_CDR2);

            try
            {
                // Serialize encapsulation
                ser.serialize_encapsulation();
                // Serialize the object.
                ser << *p_type;
                ser.set_dds_cdr_options({0,0});
            }
            catch (eprosima::fastcdr::exception::Exception& /*exception*/)
            {
                return false;
            }

            // Get the serialized length
            payload.length = static_cast<uint32_t>(ser.get_serialized_data_length());
            return true;
        }

        bool SubTableRegisterPubSubType::deserialize(
                SerializedPayload_t& payload,
                void* data)
        {
            try
            {
                // Convert DATA to pointer of your type
                SubTableRegister* p_type = static_cast<SubTableRegister*>(data);

                // Object that manages the raw buffer.
                eprosima::fastcdr::FastBuffer fastbuffer(reinterpret_cast<char*>(payload.data), payload.length);

                // Object that deserializes the data.
                eprosima::fastcdr::Cdr deser(fastbuffer, eprosima::fastcdr::Cdr::DEFAULT_ENDIAN);

                // Deserialize encapsulation.
                deser.read_encapsulation();
                payload.encapsulation = deser.endianness() == eprosima::fastcdr::Cdr::BIG_ENDIANNESS ? CDR_BE : CDR_LE;

                // Deserialize the object.
                deser >> *p_type;
            }
            catch (eprosima::fastcdr::exception::Exception& /*exception*/)
            {
                return false;
            }

            return true;
        }

        uint32_t SubTableRegisterPubSubType::calculate_serialized_size(
                const void* const data,
                DataRepresentationId_t data_representation)
        {
            try
            {
                eprosima::fastcdr::CdrSizeCalculator calculator(
                    data_representation == DataRepresentationId_t::XCDR_DATA_REPRESENTATION ?
                    eprosima::fastcdr::CdrVersion::XCDRv1 :eprosima::fastcdr::CdrVersion::XCDRv2);
                size_t current_alignment {0};
                return static_cast<uint32_t>(calculator.calculate_serialized_size(
                            *static_cast<const SubTableRegister*>(data), current_alignment)) +
                        4u /*encapsulation*/;
            }
            catch (eprosima::fastcdr::exception::Exception& /*exception*/)
            {
                return 0;
            }
        }

        void* SubTableRegisterPubSubType::create_data()
        {
            return reinterpret_cast<void*>(new SubTableRegister());
        }

        void SubTableRegisterPubSubType::delete_data(
                void* data)
        {
            delete(reinterpret_cast<SubTableRegister*>(data));
        }

        bool SubTableRegisterPubSubType::compute_key(
                SerializedPayload_t& payload,
                InstanceHandle_t& handle,
                bool force_md5)
        {
            if (!is_compute_key_provided)
            {
                return false;
            }

            SubTableRegister data;
            if (deserialize(payload, static_cast<void*>(&data)))
            {
                return compute_key(static_cast<void*>(&data), handle, force_md5);
            }

            return false;
        }

        bool SubTableRegisterPubSubType::compute_key(
                const void* const data,
                InstanceHandle_t& handle,
                bool force_md5)
        {
            if (!is_compute_key_provided)
            {
                return false;
            }

            const SubTableRegister* p_type = static_cast<const SubTableRegister*>(data);

            // Object that manages the raw buffer.
            eprosima::fastcdr::FastBuffer fastbuffer(reinterpret_cast<char*>(key_buffer_),
                    DSF_Message_SubTableRegister_max_key_cdr_typesize);

            // Object that serializes the data.
            eprosima::fastcdr::Cdr ser(fastbuffer, eprosima::fastcdr::Cdr::BIG_ENDIANNESS, eprosima::fastcdr::CdrVersion::XCDRv2);
            ser.set_encoding_flag(eprosima::fastcdr::EncodingAlgorithmFlag::PLAIN_CDR2);
            eprosima::fastcdr::serialize_key(ser, *p_type);
            if (force_md5 || DSF_Message_SubTableRegister_max_key_cdr_typesize > 16)
            {
                md5_.init();
                md5_.update(key_buffer_, static_cast<unsigned int>(ser.get_serialized_data_length()));
                md5_.finalize();
                for (uint8_t i = 0; i < 16; ++i)
                {
                    handle.value[i] = md5_.digest[i];
                }
            }
            else
            {
                for (uint8_t i = 0; i < 16; ++i)
                {
                    handle.value[i] = key_buffer_[i];
                }
            }
            return true;
        }

        void SubTableRegisterPubSubType::register_type_object_representation()
        {
            register_SubTableRegister_type_identifier(type_identifiers_);
        }

        SubTableUnregisterPubSubType::SubTableUnregisterPubSubType()
        {
            set_name("DSF::Message::SubTableUnregister");
            uint32_t type_size = DSF_Message_SubTableUnregister_max_cdr_typesize;
            type_size += static_cast<uint32_t>(eprosima::fastcdr::Cdr::alignment(type_size, 4)); /* possible submessage alignment */
            max_serialized_type_size = type_size + 4; /*encapsulation*/
            is_compute_key_provided = false;
            uint32_t key_length = DSF_Message_SubTableUnregister_max_key_cdr_typesize > 16 ? DSF_Message_SubTableUnregister_max_key_cdr_typesize : 16;
            key_buffer_ = reinterpret_cast<unsigned char*>(malloc(key_length));
            memset(key_buffer_, 0, key_length);
        }

        SubTableUnregisterPubSubType::~SubTableUnregisterPubSubType()
        {
            if (key_buffer_ != nullptr)
            {
                free(key_buffer_);
            }
        }

        bool SubTableUnregisterPubSubType::serialize(
                const void* const data,
                SerializedPayload_t& payload,
                DataRepresentationId_t data_representation)
        {
            const SubTableUnregister* p_type = static_cast<const SubTableUnregister*>(data);

            // Object that manages the raw buffer.
            eprosima::fastcdr::FastBuffer fastbuffer(reinterpret_cast<char*>(payload.data), payload.max_size);
            // Object that serializes the data.
            eprosima::fastcdr::Cdr ser(fastbuffer, eprosima::fastcdr::Cdr::DEFAULT_ENDIAN,
                    data_representation == DataRepresentationId_t::XCDR_DATA_REPRESENTATION ?
                    eprosima::fastcdr::CdrVersion::XCDRv1 : eprosima::fastcdr::CdrVersion::XCDRv2);
            payload.encapsulation = ser.endianness() == eprosima::fastcdr::Cdr::BIG_ENDIANNESS ? CDR_BE : CDR_LE;
            ser.set_encoding_flag(
                data_representation == DataRepresentationId_t::XCDR_DATA_REPRESENTATION ?
                eprosima::fastcdr::EncodingAlgorithmFlag::PLAIN_CDR  :
                eprosima::fastcdr::EncodingAlgorithmFlag::DELIMIT_CDR2);

            try
            {
                // Serialize encapsulation
                ser.serialize_encapsulation();
                // Serialize the object.
                ser << *p_type;
                ser.set_dds_cdr_options({0,0});
            }
            catch (eprosima::fastcdr::exception::Exception& /*exception*/)
            {
                return false;
            }

            // Get the serialized length
            payload.length = static_cast<uint32_t>(ser.get_serialized_data_length());
            return true;
        }

        bool SubTableUnregisterPubSubType::deserialize(
                SerializedPayload_t& payload,
                void* data)
        {
            try
            {
                // Convert DATA to pointer of your type
                SubTableUnregister* p_type = static_cast<SubTableUnregister*>(data);

                // Object that manages the raw buffer.
                eprosima::fastcdr::FastBuffer fastbuffer(reinterpret_cast<char*>(payload.data), payload.length);

                // Object that deserializes the data.
                eprosima::fastcdr::Cdr deser(fastbuffer, eprosima::fastcdr::Cdr::DEFAULT_ENDIAN);

                // Deserialize encapsulation.
                deser.read_encapsulation();
                payload.encapsulation = deser.endianness() == eprosima::fastcdr::Cdr::BIG_ENDIANNESS ? CDR_BE : CDR_LE;

                // Deserialize the object.
                deser >> *p_type;
            }
            catch (eprosima::fastcdr::exception::Exception& /*exception*/)
            {
                return false;
            }

            return true;
        }

        uint32_t SubTableUnregisterPubSubType::calculate_serialized_size(
                const void* const data,
                DataRepresentationId_t data_representation)
        {
            try
            {
                eprosima::fastcdr::CdrSizeCalculator calculator(
                    data_representation == DataRepresentationId_t::XCDR_DATA_REPRESENTATION ?
                    eprosima::fastcdr::CdrVersion::XCDRv1 :eprosima::fastcdr::CdrVersion::XCDRv2);
                size_t current_alignment {0};
                return static_cast<uint32_t>(calculator.calculate_serialized_size(
                            *static_cast<const SubTableUnregister*>(data), current_alignment)) +
                        4u /*encapsulation*/;
            }
            catch (eprosima::fastcdr::exception::Exception& /*exception*/)
            {
                return 0;
            }
        }

        void* SubTableUnregisterPubSubType::create_data()
        {
            return reinterpret_cast<void*>(new SubTableUnregister());
        }

        void SubTableUnregisterPubSubType::delete_data(
                void* data)
        {
            delete(reinterpret_cast<SubTableUnregister*>(data));
        }

        bool SubTableUnregisterPubSubType::compute_key(
                SerializedPayload_t& payload,
                InstanceHandle_t& handle,
                bool force_md5)
        {
            if (!is_compute_key_provided)
            {
                return false;
            }

            SubTableUnregister data;
            if (deserialize(payload, static_cast<void*>(&data)))
            {
                return compute_key(static_cast<void*>(&data), handle, force_md5);
            }

            return false;
        }

        bool SubTableUnregisterPubSubType::compute_key(
                const void* const data,
                InstanceHandle_t& handle,
                bool force_md5)
        {
            if (!is_compute_key_provided)
            {
                return false;
            }

            const SubTableUnregister* p_type = static_cast<const SubTableUnregister*>(data);

            // Object that manages the raw buffer.
            eprosima::fastcdr::FastBuffer fastbuffer(reinterpret_cast<char*>(key_buffer_),
                    DSF_Message_SubTableUnregister_max_key_cdr_typesize);

            // Object that serializes the data.
            eprosima::fastcdr::Cdr ser(fastbuffer, eprosima::fastcdr::Cdr::BIG_ENDIANNESS, eprosima::fastcdr::CdrVersion::XCDRv2);
            ser.set_encoding_flag(eprosima::fastcdr::EncodingAlgorithmFlag::PLAIN_CDR2);
            eprosima::fastcdr::serialize_key(ser, *p_type);
            if (force_md5 || DSF_Message_SubTableUnregister_max_key_cdr_typesize > 16)
            {
                md5_.init();
                md5_.update(key_buffer_, static_cast<unsigned int>(ser.get_serialized_data_length()));
                md5_.finalize();
                for (uint8_t i = 0; i < 16; ++i)
                {
                    handle.value[i] = md5_.digest[i];
                }
            }
            else
            {
                for (uint8_t i = 0; i < 16; ++i)
                {
                    handle.value[i] = key_buffer_[i];
                }
            }
            return true;
        }

        void SubTableUnregisterPubSubType::register_type_object_representation()
        {
            register_SubTableUnregister_type_identifier(type_identifiers_);
        }

        AlarmPubSubType::AlarmPubSubType()
        {
            set_name("DSF::Message::Alarm");
            uint32_t type_size = DSF_Message_Alarm_max_cdr_typesize;
            type_size += static_cast<uint32_t>(eprosima::fastcdr::Cdr::alignment(type_size, 4)); /* possible submessage alignment */
            max_serialized_type_size = type_size + 4; /*encapsulation*/
            is_compute_key_provided = true;
            uint32_t key_length = DSF_Message_Alarm_max_key_cdr_typesize > 16 ? DSF_Message_Alarm_max_key_cdr_typesize : 16;
            key_buffer_ = reinterpret_cast<unsigned char*>(malloc(key_length));
            memset(key_buffer_, 0, key_length);
        }

        AlarmPubSubType::~AlarmPubSubType()
        {
            if (key_buffer_ != nullptr)
            {
                free(key_buffer_);
            }
        }

        bool AlarmPubSubType::serialize(
                const void* const data,
                SerializedPayload_t& payload,
                DataRepresentationId_t data_representation)
        {
            const Alarm* p_type = static_cast<const Alarm*>(data);

            // Object that manages the raw buffer.
            eprosima::fastcdr::FastBuffer fastbuffer(reinterpret_cast<char*>(payload.data), payload.max_size);
            // Object that serializes the data.
            eprosima::fastcdr::Cdr ser(fastbuffer, eprosima::fastcdr::Cdr::DEFAULT_ENDIAN,
                    data_representation == DataRepresentationId_t::XCDR_DATA_REPRESENTATION ?
                    eprosima::fastcdr::CdrVersion::XCDRv1 : eprosima::fastcdr::CdrVersion::XCDRv2);
            payload.encapsulation = ser.endianness() == eprosima::fastcdr::Cdr::BIG_ENDIANNESS ? CDR_BE : CDR_LE;
            ser.set_encoding_flag(
                data_representation == DataRepresentationId_t::XCDR_DATA_REPRESENTATION ?
                eprosima::fastcdr::EncodingAlgorithmFlag::PLAIN_CDR  :
                eprosima::fastcdr::EncodingAlgorithmFlag::DELIMIT_CDR2);

            try
            {
                // Serialize encapsulation
                ser.serialize_encapsulation();
                // Serialize the object.
                ser << *p_type;
                ser.set_dds_cdr_options({0,0});
            }
            catch (eprosima::fastcdr::exception::Exception& /*exception*/)
            {
                return false;
            }

            // Get the serialized length
            payload.length = static_cast<uint32_t>(ser.get_serialized_data_length());
            return true;
        }

        bool AlarmPubSubType::deserialize(
                SerializedPayload_t& payload,
                void* data)
        {
            try
            {
                // Convert DATA to pointer of your type
                Alarm* p_type = static_cast<Alarm*>(data);

                // Object that manages the raw buffer.
                eprosima::fastcdr::FastBuffer fastbuffer(reinterpret_cast<char*>(payload.data), payload.length);

                // Object that deserializes the data.
                eprosima::fastcdr::Cdr deser(fastbuffer, eprosima::fastcdr::Cdr::DEFAULT_ENDIAN);

                // Deserialize encapsulation.
                deser.read_encapsulation();
                payload.encapsulation = deser.endianness() == eprosima::fastcdr::Cdr::BIG_ENDIANNESS ? CDR_BE : CDR_LE;

                // Deserialize the object.
                deser >> *p_type;
            }
            catch (eprosima::fastcdr::exception::Exception& /*exception*/)
            {
                return false;
            }

            return true;
        }

        uint32_t AlarmPubSubType::calculate_serialized_size(
                const void* const data,
                DataRepresentationId_t data_representation)
        {
            try
            {
                eprosima::fastcdr::CdrSizeCalculator calculator(
                    data_representation == DataRepresentationId_t::XCDR_DATA_REPRESENTATION ?
                    eprosima::fastcdr::CdrVersion::XCDRv1 :eprosima::fastcdr::CdrVersion::XCDRv2);
                size_t current_alignment {0};
                return static_cast<uint32_t>(calculator.calculate_serialized_size(
                            *static_cast<const Alarm*>(data), current_alignment)) +
                        4u /*encapsulation*/;
            }
            catch (eprosima::fastcdr::exception::Exception& /*exception*/)
            {
                return 0;
            }
        }

        void* AlarmPubSubType::create_data()
        {
            return reinterpret_cast<void*>(new Alarm());
        }

        void AlarmPubSubType::delete_data(
                void* data)
        {
            delete(reinterpret_cast<Alarm*>(data));
        }

        bool AlarmPubSubType::compute_key(
                SerializedPayload_t& payload,
                InstanceHandle_t& handle,
                bool force_md5)
        {
            if (!is_compute_key_provided)
            {
                return false;
            }

            Alarm data;
            if (deserialize(payload, static_cast<void*>(&data)))
            {
                return compute_key(static_cast<void*>(&data), handle, force_md5);
            }

            return false;
        }

        bool AlarmPubSubType::compute_key(
                const void* const data,
                InstanceHandle_t& handle,
                bool force_md5)
        {
            if (!is_compute_key_provided)
            {
                return false;
            }

            const Alarm* p_type = static_cast<const Alarm*>(data);

            // Object that manages the raw buffer.
            eprosima::fastcdr::FastBuffer fastbuffer(reinterpret_cast<char*>(key_buffer_),
                    DSF_Message_Alarm_max_key_cdr_typesize);

            // Object that serializes the data.
            eprosima::fastcdr::Cdr ser(fastbuffer, eprosima::fastcdr::Cdr::BIG_ENDIANNESS, eprosima::fastcdr::CdrVersion::XCDRv2);
            ser.set_encoding_flag(eprosima::fastcdr::EncodingAlgorithmFlag::PLAIN_CDR2);
            eprosima::fastcdr::serialize_key(ser, *p_type);
            if (force_md5 || DSF_Message_Alarm_max_key_cdr_typesize > 16)
            {
                md5_.init();
                md5_.update(key_buffer_, static_cast<unsigned int>(ser.get_serialized_data_length()));
                md5_.finalize();
                for (uint8_t i = 0; i < 16; ++i)
                {
                    handle.value[i] = md5_.digest[i];
                }
            }
            else
            {
                for (uint8_t i = 0; i < 16; ++i)
                {
                    handle.value[i] = key_buffer_[i];
                }
            }
            return true;
        }

        void AlarmPubSubType::register_type_object_representation()
        {
            register_Alarm_type_identifier(type_identifiers_);
        }

        NamedRetcodePubSubType::NamedRetcodePubSubType()
        {
            set_name("DSF::Message::NamedRetcode");
            uint32_t type_size = DSF_Message_NamedRetcode_max_cdr_typesize;
            type_size += static_cast<uint32_t>(eprosima::fastcdr::Cdr::alignment(type_size, 4)); /* possible submessage alignment */
            max_serialized_type_size = type_size + 4; /*encapsulation*/
            is_compute_key_provided = false;
            uint32_t key_length = DSF_Message_NamedRetcode_max_key_cdr_typesize > 16 ? DSF_Message_NamedRetcode_max_key_cdr_typesize : 16;
            key_buffer_ = reinterpret_cast<unsigned char*>(malloc(key_length));
            memset(key_buffer_, 0, key_length);
        }

        NamedRetcodePubSubType::~NamedRetcodePubSubType()
        {
            if (key_buffer_ != nullptr)
            {
                free(key_buffer_);
            }
        }

        bool NamedRetcodePubSubType::serialize(
                const void* const data,
                SerializedPayload_t& payload,
                DataRepresentationId_t data_representation)
        {
            const NamedRetcode* p_type = static_cast<const NamedRetcode*>(data);

            // Object that manages the raw buffer.
            eprosima::fastcdr::FastBuffer fastbuffer(reinterpret_cast<char*>(payload.data), payload.max_size);
            // Object that serializes the data.
            eprosima::fastcdr::Cdr ser(fastbuffer, eprosima::fastcdr::Cdr::DEFAULT_ENDIAN,
                    data_representation == DataRepresentationId_t::XCDR_DATA_REPRESENTATION ?
                    eprosima::fastcdr::CdrVersion::XCDRv1 : eprosima::fastcdr::CdrVersion::XCDRv2);
            payload.encapsulation = ser.endianness() == eprosima::fastcdr::Cdr::BIG_ENDIANNESS ? CDR_BE : CDR_LE;
            ser.set_encoding_flag(
                data_representation == DataRepresentationId_t::XCDR_DATA_REPRESENTATION ?
                eprosima::fastcdr::EncodingAlgorithmFlag::PLAIN_CDR  :
                eprosima::fastcdr::EncodingAlgorithmFlag::DELIMIT_CDR2);

            try
            {
                // Serialize encapsulation
                ser.serialize_encapsulation();
                // Serialize the object.
                ser << *p_type;
                ser.set_dds_cdr_options({0,0});
            }
            catch (eprosima::fastcdr::exception::Exception& /*exception*/)
            {
                return false;
            }

            // Get the serialized length
            payload.length = static_cast<uint32_t>(ser.get_serialized_data_length());
            return true;
        }

        bool NamedRetcodePubSubType::deserialize(
                SerializedPayload_t& payload,
                void* data)
        {
            try
            {
                // Convert DATA to pointer of your type
                NamedRetcode* p_type = static_cast<NamedRetcode*>(data);

                // Object that manages the raw buffer.
                eprosima::fastcdr::FastBuffer fastbuffer(reinterpret_cast<char*>(payload.data), payload.length);

                // Object that deserializes the data.
                eprosima::fastcdr::Cdr deser(fastbuffer, eprosima::fastcdr::Cdr::DEFAULT_ENDIAN);

                // Deserialize encapsulation.
                deser.read_encapsulation();
                payload.encapsulation = deser.endianness() == eprosima::fastcdr::Cdr::BIG_ENDIANNESS ? CDR_BE : CDR_LE;

                // Deserialize the object.
                deser >> *p_type;
            }
            catch (eprosima::fastcdr::exception::Exception& /*exception*/)
            {
                return false;
            }

            return true;
        }

        uint32_t NamedRetcodePubSubType::calculate_serialized_size(
                const void* const data,
                DataRepresentationId_t data_representation)
        {
            try
            {
                eprosima::fastcdr::CdrSizeCalculator calculator(
                    data_representation == DataRepresentationId_t::XCDR_DATA_REPRESENTATION ?
                    eprosima::fastcdr::CdrVersion::XCDRv1 :eprosima::fastcdr::CdrVersion::XCDRv2);
                size_t current_alignment {0};
                return static_cast<uint32_t>(calculator.calculate_serialized_size(
                            *static_cast<const NamedRetcode*>(data), current_alignment)) +
                        4u /*encapsulation*/;
            }
            catch (eprosima::fastcdr::exception::Exception& /*exception*/)
            {
                return 0;
            }
        }

        void* NamedRetcodePubSubType::create_data()
        {
            return reinterpret_cast<void*>(new NamedRetcode());
        }

        void NamedRetcodePubSubType::delete_data(
                void* data)
        {
            delete(reinterpret_cast<NamedRetcode*>(data));
        }

        bool NamedRetcodePubSubType::compute_key(
                SerializedPayload_t& payload,
                InstanceHandle_t& handle,
                bool force_md5)
        {
            if (!is_compute_key_provided)
            {
                return false;
            }

            NamedRetcode data;
            if (deserialize(payload, static_cast<void*>(&data)))
            {
                return compute_key(static_cast<void*>(&data), handle, force_md5);
            }

            return false;
        }

        bool NamedRetcodePubSubType::compute_key(
                const void* const data,
                InstanceHandle_t& handle,
                bool force_md5)
        {
            if (!is_compute_key_provided)
            {
                return false;
            }

            const NamedRetcode* p_type = static_cast<const NamedRetcode*>(data);

            // Object that manages the raw buffer.
            eprosima::fastcdr::FastBuffer fastbuffer(reinterpret_cast<char*>(key_buffer_),
                    DSF_Message_NamedRetcode_max_key_cdr_typesize);

            // Object that serializes the data.
            eprosima::fastcdr::Cdr ser(fastbuffer, eprosima::fastcdr::Cdr::BIG_ENDIANNESS, eprosima::fastcdr::CdrVersion::XCDRv2);
            ser.set_encoding_flag(eprosima::fastcdr::EncodingAlgorithmFlag::PLAIN_CDR2);
            eprosima::fastcdr::serialize_key(ser, *p_type);
            if (force_md5 || DSF_Message_NamedRetcode_max_key_cdr_typesize > 16)
            {
                md5_.init();
                md5_.update(key_buffer_, static_cast<unsigned int>(ser.get_serialized_data_length()));
                md5_.finalize();
                for (uint8_t i = 0; i < 16; ++i)
                {
                    handle.value[i] = md5_.digest[i];
                }
            }
            else
            {
                for (uint8_t i = 0; i < 16; ++i)
                {
                    handle.value[i] = key_buffer_[i];
                }
            }
            return true;
        }

        void NamedRetcodePubSubType::register_type_object_representation()
        {
            register_NamedRetcode_type_identifier(type_identifiers_);
        }

        CommandResponsePubSubType::CommandResponsePubSubType()
        {
            set_name("DSF::Message::CommandResponse");
            uint32_t type_size = DSF_Message_CommandResponse_max_cdr_typesize;
            type_size += static_cast<uint32_t>(eprosima::fastcdr::Cdr::alignment(type_size, 4)); /* possible submessage alignment */
            max_serialized_type_size = type_size + 4; /*encapsulation*/
            is_compute_key_provided = true;
            uint32_t key_length = DSF_Message_CommandResponse_max_key_cdr_typesize > 16 ? DSF_Message_CommandResponse_max_key_cdr_typesize : 16;
            key_buffer_ = reinterpret_cast<unsigned char*>(malloc(key_length));
            memset(key_buffer_, 0, key_length);
        }

        CommandResponsePubSubType::~CommandResponsePubSubType()
        {
            if (key_buffer_ != nullptr)
            {
                free(key_buffer_);
            }
        }

        bool CommandResponsePubSubType::serialize(
                const void* const data,
                SerializedPayload_t& payload,
                DataRepresentationId_t data_representation)
        {
            const CommandResponse* p_type = static_cast<const CommandResponse*>(data);

            // Object that manages the raw buffer.
            eprosima::fastcdr::FastBuffer fastbuffer(reinterpret_cast<char*>(payload.data), payload.max_size);
            // Object that serializes the data.
            eprosima::fastcdr::Cdr ser(fastbuffer, eprosima::fastcdr::Cdr::DEFAULT_ENDIAN,
                    data_representation == DataRepresentationId_t::XCDR_DATA_REPRESENTATION ?
                    eprosima::fastcdr::CdrVersion::XCDRv1 : eprosima::fastcdr::CdrVersion::XCDRv2);
            payload.encapsulation = ser.endianness() == eprosima::fastcdr::Cdr::BIG_ENDIANNESS ? CDR_BE : CDR_LE;
            ser.set_encoding_flag(
                data_representation == DataRepresentationId_t::XCDR_DATA_REPRESENTATION ?
                eprosima::fastcdr::EncodingAlgorithmFlag::PLAIN_CDR  :
                eprosima::fastcdr::EncodingAlgorithmFlag::DELIMIT_CDR2);

            try
            {
                // Serialize encapsulation
                ser.serialize_encapsulation();
                // Serialize the object.
                ser << *p_type;
                ser.set_dds_cdr_options({0,0});
            }
            catch (eprosima::fastcdr::exception::Exception& /*exception*/)
            {
                return false;
            }

            // Get the serialized length
            payload.length = static_cast<uint32_t>(ser.get_serialized_data_length());
            return true;
        }

        bool CommandResponsePubSubType::deserialize(
                SerializedPayload_t& payload,
                void* data)
        {
            try
            {
                // Convert DATA to pointer of your type
                CommandResponse* p_type = static_cast<CommandResponse*>(data);

                // Object that manages the raw buffer.
                eprosima::fastcdr::FastBuffer fastbuffer(reinterpret_cast<char*>(payload.data), payload.length);

                // Object that deserializes the data.
                eprosima::fastcdr::Cdr deser(fastbuffer, eprosima::fastcdr::Cdr::DEFAULT_ENDIAN);

                // Deserialize encapsulation.
                deser.read_encapsulation();
                payload.encapsulation = deser.endianness() == eprosima::fastcdr::Cdr::BIG_ENDIANNESS ? CDR_BE : CDR_LE;

                // Deserialize the object.
                deser >> *p_type;
            }
            catch (eprosima::fastcdr::exception::Exception& /*exception*/)
            {
                return false;
            }

            return true;
        }

        uint32_t CommandResponsePubSubType::calculate_serialized_size(
                const void* const data,
                DataRepresentationId_t data_representation)
        {
            try
            {
                eprosima::fastcdr::CdrSizeCalculator calculator(
                    data_representation == DataRepresentationId_t::XCDR_DATA_REPRESENTATION ?
                    eprosima::fastcdr::CdrVersion::XCDRv1 :eprosima::fastcdr::CdrVersion::XCDRv2);
                size_t current_alignment {0};
                return static_cast<uint32_t>(calculator.calculate_serialized_size(
                            *static_cast<const CommandResponse*>(data), current_alignment)) +
                        4u /*encapsulation*/;
            }
            catch (eprosima::fastcdr::exception::Exception& /*exception*/)
            {
                return 0;
            }
        }

        void* CommandResponsePubSubType::create_data()
        {
            return reinterpret_cast<void*>(new CommandResponse());
        }

        void CommandResponsePubSubType::delete_data(
                void* data)
        {
            delete(reinterpret_cast<CommandResponse*>(data));
        }

        bool CommandResponsePubSubType::compute_key(
                SerializedPayload_t& payload,
                InstanceHandle_t& handle,
                bool force_md5)
        {
            if (!is_compute_key_provided)
            {
                return false;
            }

            CommandResponse data;
            if (deserialize(payload, static_cast<void*>(&data)))
            {
                return compute_key(static_cast<void*>(&data), handle, force_md5);
            }

            return false;
        }

        bool CommandResponsePubSubType::compute_key(
                const void* const data,
                InstanceHandle_t& handle,
                bool force_md5)
        {
            if (!is_compute_key_provided)
            {
                return false;
            }

            const CommandResponse* p_type = static_cast<const CommandResponse*>(data);

            // Object that manages the raw buffer.
            eprosima::fastcdr::FastBuffer fastbuffer(reinterpret_cast<char*>(key_buffer_),
                    DSF_Message_CommandResponse_max_key_cdr_typesize);

            // Object that serializes the data.
            eprosima::fastcdr::Cdr ser(fastbuffer, eprosima::fastcdr::Cdr::BIG_ENDIANNESS, eprosima::fastcdr::CdrVersion::XCDRv2);
            ser.set_encoding_flag(eprosima::fastcdr::EncodingAlgorithmFlag::PLAIN_CDR2);
            eprosima::fastcdr::serialize_key(ser, *p_type);
            if (force_md5 || DSF_Message_CommandResponse_max_key_cdr_typesize > 16)
            {
                md5_.init();
                md5_.update(key_buffer_, static_cast<unsigned int>(ser.get_serialized_data_length()));
                md5_.finalize();
                for (uint8_t i = 0; i < 16; ++i)
                {
                    handle.value[i] = md5_.digest[i];
                }
            }
            else
            {
                for (uint8_t i = 0; i < 16; ++i)
                {
                    handle.value[i] = key_buffer_[i];
                }
            }
            return true;
        }

        void CommandResponsePubSubType::register_type_object_representation()
        {
            register_CommandResponse_type_identifier(type_identifiers_);
        }

    } // namespace Message

} // namespace DSF


// Include auxiliary functions like for serializing/deserializing.
#include "dsf_define_messagesCdrAux.ipp"
