// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file dsf_define_messagesCdrAux.hpp
 * This source file contains some definitions of CDR related functions.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef FAST_DDS_GENERATED__DSF_MESSAGE_DSF_DEFINE_MESSAGESCDRAUX_HPP
#define FAST_DDS_GENERATED__DSF_MESSAGE_DSF_DEFINE_MESSAGESCDRAUX_HPP

#include "dsf_define_messages.hpp"

constexpr uint32_t DSF_Message_ControlVar_max_cdr_typesize {2584UL};
constexpr uint32_t DSF_Message_ControlVar_max_key_cdr_typesize {0UL};




constexpr uint32_t DSF_Message_NamedBlob_max_cdr_typesize {2316UL};
constexpr uint32_t DSF_Message_NamedBlob_max_key_cdr_typesize {0UL};

constexpr uint32_t DSF_Message_EventTransfer_max_cdr_typesize {4008UL};
constexpr uint32_t DSF_Message_EventTransfer_max_key_cdr_typesize {4UL};







constexpr uint32_t DSF_Message_Event_max_cdr_typesize {544UL};
constexpr uint32_t DSF_Message_Event_max_key_cdr_typesize {4UL};





constexpr uint32_t DSF_Message_Alarm_max_cdr_typesize {1132UL};
constexpr uint32_t DSF_Message_Alarm_max_key_cdr_typesize {4UL};





constexpr uint32_t DSF_Message_SubTableRegister_max_cdr_typesize {796UL};
constexpr uint32_t DSF_Message_SubTableRegister_max_key_cdr_typesize {0UL};

constexpr uint32_t DSF_Message_SubTableUnregister_max_cdr_typesize {796UL};
constexpr uint32_t DSF_Message_SubTableUnregister_max_key_cdr_typesize {0UL};


constexpr uint32_t DSF_Message_NamedRetcode_max_cdr_typesize {532UL};
constexpr uint32_t DSF_Message_NamedRetcode_max_key_cdr_typesize {0UL};

constexpr uint32_t DSF_Message_Control_max_cdr_typesize {568UL};
constexpr uint32_t DSF_Message_Control_max_key_cdr_typesize {16UL};





constexpr uint32_t DSF_Message_CommandResponse_max_cdr_typesize {1920UL};
constexpr uint32_t DSF_Message_CommandResponse_max_key_cdr_typesize {16UL};






namespace eprosima {
namespace fastcdr {

class Cdr;
class CdrSizeCalculator;

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const DSF::Message::Event& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const DSF::Message::EventTransfer& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const DSF::Message::NamedBlob& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const DSF::Message::ControlVar& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const DSF::Message::Control& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const DSF::Message::SubTableRegister& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const DSF::Message::SubTableUnregister& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const DSF::Message::Alarm& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const DSF::Message::NamedRetcode& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const DSF::Message::CommandResponse& data);


} // namespace fastcdr
} // namespace eprosima

#endif // FAST_DDS_GENERATED__DSF_MESSAGE_DSF_DEFINE_MESSAGESCDRAUX_HPP

