// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file PerformanceTestTypeObjectSupport.cxx
 * Source file containing the implementation to register the TypeObject representation of the described types in the IDL file
 *
 * This file was generated by the tool fastddsgen.
 */

#include "PerformanceTestTypeObjectSupport.hpp"

#include <mutex>
#include <string>

#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/domain/DomainParticipantFactory.hpp>
#include <fastdds/dds/log/Log.hpp>
#include <fastdds/dds/xtypes/common.hpp>
#include <fastdds/dds/xtypes/type_representation/ITypeObjectRegistry.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObject.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObjectUtils.hpp>

#include "PerformanceTest.hpp"


using namespace eprosima::fastdds::dds::xtypes;

namespace PerformanceTest {
// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_TestMessage_type_identifier(
        TypeIdentifierPair& type_ids_TestMessage)
{

    ReturnCode_t return_code_TestMessage {eprosima::fastdds::dds::RETCODE_OK};
    return_code_TestMessage =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "PerformanceTest::TestMessage", type_ids_TestMessage);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_TestMessage)
    {
        StructTypeFlag struct_flags_TestMessage = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::APPENDABLE,
                false, false);
        QualifiedTypeName type_name_TestMessage = "PerformanceTest::TestMessage";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_TestMessage;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_TestMessage;
        CompleteTypeDetail detail_TestMessage = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_TestMessage, ann_custom_TestMessage, type_name_TestMessage.to_string());
        CompleteStructHeader header_TestMessage;
        header_TestMessage = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_TestMessage);
        CompleteStructMemberSeq member_seq_TestMessage;
        {
            TypeIdentifierPair type_ids_seq_num;
            ReturnCode_t return_code_seq_num {eprosima::fastdds::dds::RETCODE_OK};
            return_code_seq_num =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_uint32_t", type_ids_seq_num);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_seq_num)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "seq_num Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_seq_num = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_seq_num = 0x00000000;
            bool common_seq_num_ec {false};
            CommonStructMember common_seq_num {TypeObjectUtils::build_common_struct_member(member_id_seq_num, member_flags_seq_num, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_seq_num, common_seq_num_ec))};
            if (!common_seq_num_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure seq_num member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_seq_num = "seq_num";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_seq_num;
            ann_custom_TestMessage.reset();
            CompleteMemberDetail detail_seq_num = TypeObjectUtils::build_complete_member_detail(name_seq_num, member_ann_builtin_seq_num, ann_custom_TestMessage);
            CompleteStructMember member_seq_num = TypeObjectUtils::build_complete_struct_member(common_seq_num, detail_seq_num);
            TypeObjectUtils::add_complete_struct_member(member_seq_TestMessage, member_seq_num);
        }
        {
            TypeIdentifierPair type_ids_timestamp;
            ReturnCode_t return_code_timestamp {eprosima::fastdds::dds::RETCODE_OK};
            return_code_timestamp =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_uint64_t", type_ids_timestamp);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_timestamp)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "timestamp Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_timestamp = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_timestamp = 0x00000001;
            bool common_timestamp_ec {false};
            CommonStructMember common_timestamp {TypeObjectUtils::build_common_struct_member(member_id_timestamp, member_flags_timestamp, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_timestamp, common_timestamp_ec))};
            if (!common_timestamp_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure timestamp member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_timestamp = "timestamp";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_timestamp;
            ann_custom_TestMessage.reset();
            CompleteMemberDetail detail_timestamp = TypeObjectUtils::build_complete_member_detail(name_timestamp, member_ann_builtin_timestamp, ann_custom_TestMessage);
            CompleteStructMember member_timestamp = TypeObjectUtils::build_complete_struct_member(common_timestamp, detail_timestamp);
            TypeObjectUtils::add_complete_struct_member(member_seq_TestMessage, member_timestamp);
        }
        {
            TypeIdentifierPair type_ids_message_type;
            ReturnCode_t return_code_message_type {eprosima::fastdds::dds::RETCODE_OK};
            return_code_message_type =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_string_unbounded", type_ids_message_type);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_message_type)
            {
                {
                    SBound bound = 0;
                    StringSTypeDefn string_sdefn = TypeObjectUtils::build_string_s_type_defn(bound);
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_string_type_identifier(string_sdefn,
                            "anonymous_string_unbounded", type_ids_message_type))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_string_unbounded already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_message_type = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_message_type = 0x00000002;
            bool common_message_type_ec {false};
            CommonStructMember common_message_type {TypeObjectUtils::build_common_struct_member(member_id_message_type, member_flags_message_type, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_message_type, common_message_type_ec))};
            if (!common_message_type_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure message_type member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_message_type = "message_type";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_message_type;
            ann_custom_TestMessage.reset();
            CompleteMemberDetail detail_message_type = TypeObjectUtils::build_complete_member_detail(name_message_type, member_ann_builtin_message_type, ann_custom_TestMessage);
            CompleteStructMember member_message_type = TypeObjectUtils::build_complete_struct_member(common_message_type, detail_message_type);
            TypeObjectUtils::add_complete_struct_member(member_seq_TestMessage, member_message_type);
        }
        {
            TypeIdentifierPair type_ids_payload;
            ReturnCode_t return_code_payload {eprosima::fastdds::dds::RETCODE_OK};
            return_code_payload =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_sequence_byte_unbounded", type_ids_payload);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_payload)
            {
                return_code_payload =
                    eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                    "_byte", type_ids_payload);

                if (eprosima::fastdds::dds::RETCODE_OK != return_code_payload)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "Sequence element TypeIdentifier unknown to TypeObjectRegistry.");
                    return;
                }
                bool element_identifier_anonymous_sequence_byte_unbounded_ec {false};
                TypeIdentifier* element_identifier_anonymous_sequence_byte_unbounded {new TypeIdentifier(TypeObjectUtils::retrieve_complete_type_identifier(type_ids_payload, element_identifier_anonymous_sequence_byte_unbounded_ec))};
                if (!element_identifier_anonymous_sequence_byte_unbounded_ec)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Sequence element TypeIdentifier inconsistent.");
                    return;
                }
                EquivalenceKind equiv_kind_anonymous_sequence_byte_unbounded = EK_COMPLETE;
                if (TK_NONE == type_ids_payload.type_identifier2()._d())
                {
                    equiv_kind_anonymous_sequence_byte_unbounded = EK_BOTH;
                }
                CollectionElementFlag element_flags_anonymous_sequence_byte_unbounded = 0;
                PlainCollectionHeader header_anonymous_sequence_byte_unbounded = TypeObjectUtils::build_plain_collection_header(equiv_kind_anonymous_sequence_byte_unbounded, element_flags_anonymous_sequence_byte_unbounded);
                {
                    SBound bound = 0;
                    PlainSequenceSElemDefn seq_sdefn = TypeObjectUtils::build_plain_sequence_s_elem_defn(header_anonymous_sequence_byte_unbounded, bound,
                                eprosima::fastcdr::external<TypeIdentifier>(element_identifier_anonymous_sequence_byte_unbounded));
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_sequence_type_identifier(seq_sdefn, "anonymous_sequence_byte_unbounded", type_ids_payload))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_sequence_byte_unbounded already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_payload = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_payload = 0x00000003;
            bool common_payload_ec {false};
            CommonStructMember common_payload {TypeObjectUtils::build_common_struct_member(member_id_payload, member_flags_payload, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_payload, common_payload_ec))};
            if (!common_payload_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure payload member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_payload = "payload";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_payload;
            ann_custom_TestMessage.reset();
            CompleteMemberDetail detail_payload = TypeObjectUtils::build_complete_member_detail(name_payload, member_ann_builtin_payload, ann_custom_TestMessage);
            CompleteStructMember member_payload = TypeObjectUtils::build_complete_struct_member(common_payload, detail_payload);
            TypeObjectUtils::add_complete_struct_member(member_seq_TestMessage, member_payload);
        }
        CompleteStructType struct_type_TestMessage = TypeObjectUtils::build_complete_struct_type(struct_flags_TestMessage, header_TestMessage, member_seq_TestMessage);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_TestMessage, type_name_TestMessage.to_string(), type_ids_TestMessage))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "PerformanceTest::TestMessage already registered in TypeObjectRegistry for a different type.");
        }
    }
}

} // namespace PerformanceTest

