// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file dsf_define_messages.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef _TX_DDS_GENERATED_DSF_MESSAGE_DSF_DEFINE_MESSAGES_H_
#define _TX_DDS_GENERATED_DSF_MESSAGE_DSF_DEFINE_MESSAGES_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <map>
#include <string>
#include <vector>

#include "txcdr/optional.h"

#include <txcdr/optional.h>

#include "dsf_define_node.h"


#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(DSF_DEFINE_MESSAGES_SOURCE)
#define DSF_DEFINE_MESSAGES_DllAPI __declspec( dllexport )
#else
#define DSF_DEFINE_MESSAGES_DllAPI __declspec( dllimport )
#endif // DSF_DEFINE_MESSAGES_SOURCE
#else
#define DSF_DEFINE_MESSAGES_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define DSF_DEFINE_MESSAGES_DllAPI
#endif // _WIN32

namespace BaoSky::Cdr {
class Cdr;
class CdrSizeCalculator;
} // namespace BaoSky::Cdr




namespace DSF {

namespace Message {

const std::string MESSAGE_COMMAND_REQUEST_CONTROL_TOPIC_NAME = "dsf/message/commandRequest/control";
const std::string MESSAGE_COMMAND_RESPONSE_CONTROL_TOPIC_NAME = "dsf/message/commandResponse/control";
const std::string MESSAGE_COMMAND_REQUEST_ALARM_TOPIC_NAME = "dsf/message/commandRequest/alarm";
const std::string MESSAGE_COMMAND_RESPONSE_ALARM_TOPIC_NAME = "dsf/message/commandResponse/alarm";
const std::string MESSAGE_COMMAND_REQUEST_EVENT_DEFINE_TOPIC_NAME = "dsf/message/commandRequest/event/define";
const std::string MESSAGE_COMMAND_REQUEST_EVENT_SYSTEM_TOPIC_NAME = "dsf/message/commandRequest/event/system";
const std::string MESSAGE_COMMAND_REQUEST_EVENT_RESOURCE_TOPIC_NAME = "dsf/message/commandRequest/event/resource";
const std::string MESSAGE_COMMAND_REQUEST_EVENT_SECURITY_TOPIC_NAME = "dsf/message/commandRequest/event/security";
const std::string MESSAGE_COMMAND_REQUEST_EVENT_NETWORK_TOPIC_NAME = "dsf/message/commandRequest/event/network";
const std::string MESSAGE_COMMAND_REQUEST_EVENT_PROGRESS_TOPIC_NAME = "dsf/message/commandRequest/event/progress";
const std::string MESSAGE_COMMAND_REQUEST_EVENT_VAR_TOPIC_NAME = "dsf/message/commandRequest/event/var";
const std::string MESSAGE_COMMAND_REQUEST_EVENT_APPLICATION_TOPIC_NAME = "dsf/message/commandRequest/event/application";
const std::string MESSAGE_COMMAND_REQUEST_EVENT_OTHER_TOPIC_NAME = "dsf/message/commandRequest/event/other";
const std::string MESSAGE_COMMAND_REQUEST_SUB_TABLE_REGISTER_TOPIC_NAME = "dsf/message/commandRequest/subTableRegister";
const std::string MESSAGE_COMMAND_RESPONSE_SUB_TABLE_REGISTER_TOPIC_NAME = "dsf/message/commandResponse/subTableRegister";
const std::string MESSAGE_COMMAND_REQUEST_SUB_TABLE_UNREGISTER_TOPIC_NAME = "dsf/message/commandRequest/subTableUnregister";
const std::string MESSAGE_COMMAND_RESPONSE_SUB_TABLE_UNREGISTER_TOPIC_NAME = "dsf/message/commandResponse/subTableUnregister";
const std::string MESSAGE_COMMAND_REQUEST_TYPE_NAME = "DSF::Message::CommandRequest";
const std::string MESSAGE_COMMAND_RESPONSE_TYPE_NAME = "DSF::Message::CommandResponse";
/*!
 * @brief This class represents the enumeration EventCategory defined by the user in the IDL file.
 * @ingroup dsf_define_messages
 */
enum EventCategory : uint32_t
{
    SYSTEM,
    RESOURCE,
    SECURITY,
    NETWORK,
    PROGRESS,
    VAR,
    APPLICATION,
    OTHER
};
/*!
 * @brief This class represents the enumeration MSGTYPE defined by the user in the IDL file.
 * @ingroup dsf_define_messages
 */
enum MSGTYPE : uint32_t
{
    CONTROL,
    EVENT,
    ALARM,
    SUB_TABLE_REGISTER,
    SUB_TABLE_UNREGISTER
};
/*!
 * @brief This class represents the structure Event defined by the user in the IDL file.
 * @ingroup dsf_define_messages
 */
class Event
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport Event();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~Event();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object Event that will be copied.
     */
    eProsima_user_DllExport Event(
            const Event& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object Event that will be copied.
     */
    eProsima_user_DllExport Event(
            Event&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object Event that will be copied.
     */
    eProsima_user_DllExport Event& operator =(
            const Event& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object Event that will be copied.
     */
    eProsima_user_DllExport Event& operator =(
            Event&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x Event object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const Event& x) const;

    /*!
     * @brief Comparison operator.
     * @param x Event object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const Event& x) const;

    /*!
     * @brief This function sets a value in member eventCode
     * @param _eventCode New value for member eventCode
     */
    eProsima_user_DllExport void eventCode(
            int32_t _eventCode);

    /*!
     * @brief This function returns the value of member eventCode
     * @return Value of member eventCode
     */
    eProsima_user_DllExport int32_t eventCode() const;

    /*!
     * @brief This function returns a reference to member eventCode
     * @return Reference to member eventCode
     */
    eProsima_user_DllExport int32_t& eventCode();


    /*!
     * @brief This function copies the value in member payloadType
     * @param _payloadType New value to be copied in member payloadType
     */
    eProsima_user_DllExport void payloadType(
            const std::string& _payloadType);

    /*!
     * @brief This function moves the value in member payloadType
     * @param _payloadType New value to be moved in member payloadType
     */
    eProsima_user_DllExport void payloadType(
            std::string&& _payloadType);

    /*!
     * @brief This function returns a constant reference to member payloadType
     * @return Constant reference to member payloadType
     */
    eProsima_user_DllExport const std::string& payloadType() const;

    /*!
     * @brief This function returns a reference to member payloadType
     * @return Reference to member payloadType
     */
    eProsima_user_DllExport std::string& payloadType();


    /*!
     * @brief This function copies the value in member description
     * @param _description New value to be copied in member description
     */
    eProsima_user_DllExport void description(
            const std::string& _description);

    /*!
     * @brief This function moves the value in member description
     * @param _description New value to be moved in member description
     */
    eProsima_user_DllExport void description(
            std::string&& _description);

    /*!
     * @brief This function returns a constant reference to member description
     * @return Constant reference to member description
     */
    eProsima_user_DllExport const std::string& description() const;

    /*!
     * @brief This function returns a reference to member description
     * @return Reference to member description
     */
    eProsima_user_DllExport std::string& description();


    /*!
     * @brief This function sets a value in member category
     * @param _category New value for member category
     */
    eProsima_user_DllExport void category(
            EventCategory _category);

    /*!
     * @brief This function returns the value of member category
     * @return Value of member category
     */
    eProsima_user_DllExport EventCategory category() const;

    /*!
     * @brief This function returns a reference to member category
     * @return Reference to member category
     */
    eProsima_user_DllExport EventCategory& category();


    /*!
     * @brief This function copies the value in member createTime
     * @param _createTime New value to be copied in member createTime
     */
    eProsima_user_DllExport void createTime(
            const DSF::Timespec& _createTime);

    /*!
     * @brief This function moves the value in member createTime
     * @param _createTime New value to be moved in member createTime
     */
    eProsima_user_DllExport void createTime(
            DSF::Timespec&& _createTime);

    /*!
     * @brief This function returns a constant reference to member createTime
     * @return Constant reference to member createTime
     */
    eProsima_user_DllExport const DSF::Timespec& createTime() const;

    /*!
     * @brief This function returns a reference to member createTime
     * @return Reference to member createTime
     */
    eProsima_user_DllExport DSF::Timespec& createTime();


    /*!
     * @brief This function sets a value in member msgType
     * @param _msgType New value for member msgType
     */
    eProsima_user_DllExport void msgType(
            MSGTYPE _msgType);

    /*!
     * @brief This function returns the value of member msgType
     * @return Value of member msgType
     */
    eProsima_user_DllExport MSGTYPE msgType() const;

    /*!
     * @brief This function returns a reference to member msgType
     * @return Reference to member msgType
     */
    eProsima_user_DllExport MSGTYPE& msgType();

private:

    int32_t m_eventCode{0};
    std::string m_payloadType;
    std::string m_description;
    EventCategory m_category{EventCategory::SYSTEM};
    DSF::Timespec m_createTime;
    MSGTYPE m_msgType{MSGTYPE::CONTROL};

};
/*!
 * @brief This class represents the structure EventTransfer defined by the user in the IDL file.
 * @ingroup dsf_define_messages
 */
class EventTransfer
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport EventTransfer();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~EventTransfer();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object EventTransfer that will be copied.
     */
    eProsima_user_DllExport EventTransfer(
            const EventTransfer& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object EventTransfer that will be copied.
     */
    eProsima_user_DllExport EventTransfer(
            EventTransfer&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object EventTransfer that will be copied.
     */
    eProsima_user_DllExport EventTransfer& operator =(
            const EventTransfer& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object EventTransfer that will be copied.
     */
    eProsima_user_DllExport EventTransfer& operator =(
            EventTransfer&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x EventTransfer object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const EventTransfer& x) const;

    /*!
     * @brief Comparison operator.
     * @param x EventTransfer object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const EventTransfer& x) const;

    /*!
     * @brief This function sets a value in member eventCode
     * @param _eventCode New value for member eventCode
     */
    eProsima_user_DllExport void eventCode(
            int32_t _eventCode);

    /*!
     * @brief This function returns the value of member eventCode
     * @return Value of member eventCode
     */
    eProsima_user_DllExport int32_t eventCode() const;

    /*!
     * @brief This function returns a reference to member eventCode
     * @return Reference to member eventCode
     */
    eProsima_user_DllExport int32_t& eventCode();


    /*!
     * @brief This function copies the value in member srcNode
     * @param _srcNode New value to be copied in member srcNode
     */
    eProsima_user_DllExport void srcNode(
            const std::string& _srcNode);

    /*!
     * @brief This function moves the value in member srcNode
     * @param _srcNode New value to be moved in member srcNode
     */
    eProsima_user_DllExport void srcNode(
            std::string&& _srcNode);

    /*!
     * @brief This function returns a constant reference to member srcNode
     * @return Constant reference to member srcNode
     */
    eProsima_user_DllExport const std::string& srcNode() const;

    /*!
     * @brief This function returns a reference to member srcNode
     * @return Reference to member srcNode
     */
    eProsima_user_DllExport std::string& srcNode();


    /*!
     * @brief This function sets a value in member seqNum
     * @param _seqNum New value for member seqNum
     */
    eProsima_user_DllExport void seqNum(
            int32_t _seqNum);

    /*!
     * @brief This function returns the value of member seqNum
     * @return Value of member seqNum
     */
    eProsima_user_DllExport int32_t seqNum() const;

    /*!
     * @brief This function returns a reference to member seqNum
     * @return Reference to member seqNum
     */
    eProsima_user_DllExport int32_t& seqNum();


    /*!
     * @brief This function copies the value in member sourceTime
     * @param _sourceTime New value to be copied in member sourceTime
     */
    eProsima_user_DllExport void sourceTime(
            const DSF::Timespec& _sourceTime);

    /*!
     * @brief This function moves the value in member sourceTime
     * @param _sourceTime New value to be moved in member sourceTime
     */
    eProsima_user_DllExport void sourceTime(
            DSF::Timespec&& _sourceTime);

    /*!
     * @brief This function returns a constant reference to member sourceTime
     * @return Constant reference to member sourceTime
     */
    eProsima_user_DllExport const DSF::Timespec& sourceTime() const;

    /*!
     * @brief This function returns a reference to member sourceTime
     * @return Reference to member sourceTime
     */
    eProsima_user_DllExport DSF::Timespec& sourceTime();


    /*!
     * @brief This function copies the value in member sendTime
     * @param _sendTime New value to be copied in member sendTime
     */
    eProsima_user_DllExport void sendTime(
            const DSF::Timespec& _sendTime);

    /*!
     * @brief This function moves the value in member sendTime
     * @param _sendTime New value to be moved in member sendTime
     */
    eProsima_user_DllExport void sendTime(
            DSF::Timespec&& _sendTime);

    /*!
     * @brief This function returns a constant reference to member sendTime
     * @return Constant reference to member sendTime
     */
    eProsima_user_DllExport const DSF::Timespec& sendTime() const;

    /*!
     * @brief This function returns a reference to member sendTime
     * @return Reference to member sendTime
     */
    eProsima_user_DllExport DSF::Timespec& sendTime();


    /*!
     * @brief This function copies the value in member payloadData
     * @param _payloadData New value to be copied in member payloadData
     */
    eProsima_user_DllExport void payloadData(
            const DSF::DT_BLOB& _payloadData);

    /*!
     * @brief This function moves the value in member payloadData
     * @param _payloadData New value to be moved in member payloadData
     */
    eProsima_user_DllExport void payloadData(
            DSF::DT_BLOB&& _payloadData);

    /*!
     * @brief This function returns a constant reference to member payloadData
     * @return Constant reference to member payloadData
     */
    eProsima_user_DllExport const DSF::DT_BLOB& payloadData() const;

    /*!
     * @brief This function returns a reference to member payloadData
     * @return Reference to member payloadData
     */
    eProsima_user_DllExport DSF::DT_BLOB& payloadData();


    /*!
     * @brief This function sets a value in member payloadBlobType
     * @param _payloadBlobType New value for member payloadBlobType
     */
    eProsima_user_DllExport void payloadBlobType(
            int32_t _payloadBlobType);

    /*!
     * @brief This function returns the value of member payloadBlobType
     * @return Value of member payloadBlobType
     */
    eProsima_user_DllExport int32_t payloadBlobType() const;

    /*!
     * @brief This function returns a reference to member payloadBlobType
     * @return Reference to member payloadBlobType
     */
    eProsima_user_DllExport int32_t& payloadBlobType();


    /*!
     * @brief This function copies the value in member nodeInfo
     * @param _nodeInfo New value to be copied in member nodeInfo
     */
    eProsima_user_DllExport void nodeInfo(
            const BaoSky::Cdr::optional<DSF::Node::RuntimeInfo>& _nodeInfo);

    /*!
     * @brief This function moves the value in member nodeInfo
     * @param _nodeInfo New value to be moved in member nodeInfo
     */
    eProsima_user_DllExport void nodeInfo(
            BaoSky::Cdr::optional<DSF::Node::RuntimeInfo>&& _nodeInfo);

    /*!
     * @brief This function returns a constant reference to member nodeInfo
     * @return Constant reference to member nodeInfo
     */
    eProsima_user_DllExport const BaoSky::Cdr::optional<DSF::Node::RuntimeInfo>& nodeInfo() const;

    /*!
     * @brief This function returns a reference to member nodeInfo
     * @return Reference to member nodeInfo
     */
    eProsima_user_DllExport BaoSky::Cdr::optional<DSF::Node::RuntimeInfo>& nodeInfo();


    /*!
     * @brief This function copies the value in member relatedVars
     * @param _relatedVars New value to be copied in member relatedVars
     */
    eProsima_user_DllExport void relatedVars(
            const BaoSky::Cdr::optional<std::vector<std::string>>& _relatedVars);

    /*!
     * @brief This function moves the value in member relatedVars
     * @param _relatedVars New value to be moved in member relatedVars
     */
    eProsima_user_DllExport void relatedVars(
            BaoSky::Cdr::optional<std::vector<std::string>>&& _relatedVars);

    /*!
     * @brief This function returns a constant reference to member relatedVars
     * @return Constant reference to member relatedVars
     */
    eProsima_user_DllExport const BaoSky::Cdr::optional<std::vector<std::string>>& relatedVars() const;

    /*!
     * @brief This function returns a reference to member relatedVars
     * @return Reference to member relatedVars
     */
    eProsima_user_DllExport BaoSky::Cdr::optional<std::vector<std::string>>& relatedVars();


    /*!
     * @brief This function copies the value in member relatedNodes
     * @param _relatedNodes New value to be copied in member relatedNodes
     */
    eProsima_user_DllExport void relatedNodes(
            const BaoSky::Cdr::optional<std::vector<std::string>>& _relatedNodes);

    /*!
     * @brief This function moves the value in member relatedNodes
     * @param _relatedNodes New value to be moved in member relatedNodes
     */
    eProsima_user_DllExport void relatedNodes(
            BaoSky::Cdr::optional<std::vector<std::string>>&& _relatedNodes);

    /*!
     * @brief This function returns a constant reference to member relatedNodes
     * @return Constant reference to member relatedNodes
     */
    eProsima_user_DllExport const BaoSky::Cdr::optional<std::vector<std::string>>& relatedNodes() const;

    /*!
     * @brief This function returns a reference to member relatedNodes
     * @return Reference to member relatedNodes
     */
    eProsima_user_DllExport BaoSky::Cdr::optional<std::vector<std::string>>& relatedNodes();

private:

    int32_t m_eventCode{0};
    std::string m_srcNode;
    int32_t m_seqNum{0};
    DSF::Timespec m_sourceTime;
    DSF::Timespec m_sendTime;
    DSF::DT_BLOB m_payloadData;
    int32_t m_payloadBlobType{2};
    BaoSky::Cdr::optional<DSF::Node::RuntimeInfo> m_nodeInfo;
    BaoSky::Cdr::optional<std::vector<std::string>> m_relatedVars;
    BaoSky::Cdr::optional<std::vector<std::string>> m_relatedNodes;

};
/*!
 * @brief This class represents the enumeration CONTROL_VAR_TYPE defined by the user in the IDL file.
 * @ingroup dsf_define_messages
 */
enum CONTROL_VAR_TYPE : uint32_t
{
    STR,
    BLOB
};
/*!
 * @brief This class represents the structure NamedBlob defined by the user in the IDL file.
 * @ingroup dsf_define_messages
 */
class NamedBlob
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport NamedBlob();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~NamedBlob();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object NamedBlob that will be copied.
     */
    eProsima_user_DllExport NamedBlob(
            const NamedBlob& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object NamedBlob that will be copied.
     */
    eProsima_user_DllExport NamedBlob(
            NamedBlob&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object NamedBlob that will be copied.
     */
    eProsima_user_DllExport NamedBlob& operator =(
            const NamedBlob& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object NamedBlob that will be copied.
     */
    eProsima_user_DllExport NamedBlob& operator =(
            NamedBlob&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x NamedBlob object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const NamedBlob& x) const;

    /*!
     * @brief Comparison operator.
     * @param x NamedBlob object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const NamedBlob& x) const;

    /*!
     * @brief This function copies the value in member name
     * @param _name New value to be copied in member name
     */
    eProsima_user_DllExport void name(
            const std::string& _name);

    /*!
     * @brief This function moves the value in member name
     * @param _name New value to be moved in member name
     */
    eProsima_user_DllExport void name(
            std::string&& _name);

    /*!
     * @brief This function returns a constant reference to member name
     * @return Constant reference to member name
     */
    eProsima_user_DllExport const std::string& name() const;

    /*!
     * @brief This function returns a reference to member name
     * @return Reference to member name
     */
    eProsima_user_DllExport std::string& name();


    /*!
     * @brief This function copies the value in member blob
     * @param _blob New value to be copied in member blob
     */
    eProsima_user_DllExport void blob(
            const DSF::DT_BLOB& _blob);

    /*!
     * @brief This function moves the value in member blob
     * @param _blob New value to be moved in member blob
     */
    eProsima_user_DllExport void blob(
            DSF::DT_BLOB&& _blob);

    /*!
     * @brief This function returns a constant reference to member blob
     * @return Constant reference to member blob
     */
    eProsima_user_DllExport const DSF::DT_BLOB& blob() const;

    /*!
     * @brief This function returns a reference to member blob
     * @return Reference to member blob
     */
    eProsima_user_DllExport DSF::DT_BLOB& blob();

private:

    std::string m_name;
    DSF::DT_BLOB m_blob;

};
/*!
 * @brief This class represents the structure ControlVar defined by the user in the IDL file.
 * @ingroup dsf_define_messages
 */
class ControlVar
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport ControlVar();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~ControlVar();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object ControlVar that will be copied.
     */
    eProsima_user_DllExport ControlVar(
            const ControlVar& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object ControlVar that will be copied.
     */
    eProsima_user_DllExport ControlVar(
            ControlVar&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object ControlVar that will be copied.
     */
    eProsima_user_DllExport ControlVar& operator =(
            const ControlVar& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object ControlVar that will be copied.
     */
    eProsima_user_DllExport ControlVar& operator =(
            ControlVar&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x ControlVar object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const ControlVar& x) const;

    /*!
     * @brief Comparison operator.
     * @param x ControlVar object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const ControlVar& x) const;

    /*!
     * @brief This function copies the value in member nodeName
     * @param _nodeName New value to be copied in member nodeName
     */
    eProsima_user_DllExport void nodeName(
            const std::string& _nodeName);

    /*!
     * @brief This function moves the value in member nodeName
     * @param _nodeName New value to be moved in member nodeName
     */
    eProsima_user_DllExport void nodeName(
            std::string&& _nodeName);

    /*!
     * @brief This function returns a constant reference to member nodeName
     * @return Constant reference to member nodeName
     */
    eProsima_user_DllExport const std::string& nodeName() const;

    /*!
     * @brief This function returns a reference to member nodeName
     * @return Reference to member nodeName
     */
    eProsima_user_DllExport std::string& nodeName();


    /*!
     * @brief This function sets a value in member type
     * @param _type New value for member type
     */
    eProsima_user_DllExport void type(
            CONTROL_VAR_TYPE _type);

    /*!
     * @brief This function returns the value of member type
     * @return Value of member type
     */
    eProsima_user_DllExport CONTROL_VAR_TYPE type() const;

    /*!
     * @brief This function returns a reference to member type
     * @return Reference to member type
     */
    eProsima_user_DllExport CONTROL_VAR_TYPE& type();


    /*!
     * @brief This function copies the value in member namedValue
     * @param _namedValue New value to be copied in member namedValue
     */
    eProsima_user_DllExport void namedValue(
            const NamedBlob& _namedValue);

    /*!
     * @brief This function moves the value in member namedValue
     * @param _namedValue New value to be moved in member namedValue
     */
    eProsima_user_DllExport void namedValue(
            NamedBlob&& _namedValue);

    /*!
     * @brief This function returns a constant reference to member namedValue
     * @return Constant reference to member namedValue
     */
    eProsima_user_DllExport const NamedBlob& namedValue() const;

    /*!
     * @brief This function returns a reference to member namedValue
     * @return Reference to member namedValue
     */
    eProsima_user_DllExport NamedBlob& namedValue();

private:

    std::string m_nodeName;
    CONTROL_VAR_TYPE m_type{CONTROL_VAR_TYPE::STR};
    NamedBlob m_namedValue;

};
/*!
 * @brief This class represents the structure Control defined by the user in the IDL file.
 * @ingroup dsf_define_messages
 */
class Control
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport Control();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~Control();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object Control that will be copied.
     */
    eProsima_user_DllExport Control(
            const Control& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object Control that will be copied.
     */
    eProsima_user_DllExport Control(
            Control&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object Control that will be copied.
     */
    eProsima_user_DllExport Control& operator =(
            const Control& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object Control that will be copied.
     */
    eProsima_user_DllExport Control& operator =(
            Control&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x Control object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const Control& x) const;

    /*!
     * @brief Comparison operator.
     * @param x Control object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const Control& x) const;

    /*!
     * @brief This function copies the value in member messageId
     * @param _messageId New value to be copied in member messageId
     */
    eProsima_user_DllExport void messageId(
            const DSF::GUID_t& _messageId);

    /*!
     * @brief This function moves the value in member messageId
     * @param _messageId New value to be moved in member messageId
     */
    eProsima_user_DllExport void messageId(
            DSF::GUID_t&& _messageId);

    /*!
     * @brief This function returns a constant reference to member messageId
     * @return Constant reference to member messageId
     */
    eProsima_user_DllExport const DSF::GUID_t& messageId() const;

    /*!
     * @brief This function returns a reference to member messageId
     * @return Reference to member messageId
     */
    eProsima_user_DllExport DSF::GUID_t& messageId();


    /*!
     * @brief This function copies the value in member currentTime
     * @param _currentTime New value to be copied in member currentTime
     */
    eProsima_user_DllExport void currentTime(
            const DSF::Timespec& _currentTime);

    /*!
     * @brief This function moves the value in member currentTime
     * @param _currentTime New value to be moved in member currentTime
     */
    eProsima_user_DllExport void currentTime(
            DSF::Timespec&& _currentTime);

    /*!
     * @brief This function returns a constant reference to member currentTime
     * @return Constant reference to member currentTime
     */
    eProsima_user_DllExport const DSF::Timespec& currentTime() const;

    /*!
     * @brief This function returns a reference to member currentTime
     * @return Reference to member currentTime
     */
    eProsima_user_DllExport DSF::Timespec& currentTime();


    /*!
     * @brief This function sets a value in member msgType
     * @param _msgType New value for member msgType
     */
    eProsima_user_DllExport void msgType(
            MSGTYPE _msgType);

    /*!
     * @brief This function returns the value of member msgType
     * @return Value of member msgType
     */
    eProsima_user_DllExport MSGTYPE msgType() const;

    /*!
     * @brief This function returns a reference to member msgType
     * @return Reference to member msgType
     */
    eProsima_user_DllExport MSGTYPE& msgType();


    /*!
     * @brief This function copies the value in member vars
     * @param _vars New value to be copied in member vars
     */
    eProsima_user_DllExport void vars(
            const std::vector<ControlVar>& _vars);

    /*!
     * @brief This function moves the value in member vars
     * @param _vars New value to be moved in member vars
     */
    eProsima_user_DllExport void vars(
            std::vector<ControlVar>&& _vars);

    /*!
     * @brief This function returns a constant reference to member vars
     * @return Constant reference to member vars
     */
    eProsima_user_DllExport const std::vector<ControlVar>& vars() const;

    /*!
     * @brief This function returns a reference to member vars
     * @return Reference to member vars
     */
    eProsima_user_DllExport std::vector<ControlVar>& vars();


    /*!
     * @brief This function copies the value in member srcNode
     * @param _srcNode New value to be copied in member srcNode
     */
    eProsima_user_DllExport void srcNode(
            const std::string& _srcNode);

    /*!
     * @brief This function moves the value in member srcNode
     * @param _srcNode New value to be moved in member srcNode
     */
    eProsima_user_DllExport void srcNode(
            std::string&& _srcNode);

    /*!
     * @brief This function returns a constant reference to member srcNode
     * @return Constant reference to member srcNode
     */
    eProsima_user_DllExport const std::string& srcNode() const;

    /*!
     * @brief This function returns a reference to member srcNode
     * @return Reference to member srcNode
     */
    eProsima_user_DllExport std::string& srcNode();


    /*!
     * @brief This function copies the value in member write_tokens
     * @param _write_tokens New value to be copied in member write_tokens
     */
    eProsima_user_DllExport void write_tokens(
            const std::vector<std::string>& _write_tokens);

    /*!
     * @brief This function moves the value in member write_tokens
     * @param _write_tokens New value to be moved in member write_tokens
     */
    eProsima_user_DllExport void write_tokens(
            std::vector<std::string>&& _write_tokens);

    /*!
     * @brief This function returns a constant reference to member write_tokens
     * @return Constant reference to member write_tokens
     */
    eProsima_user_DllExport const std::vector<std::string>& write_tokens() const;

    /*!
     * @brief This function returns a reference to member write_tokens
     * @return Reference to member write_tokens
     */
    eProsima_user_DllExport std::vector<std::string>& write_tokens();


    /*!
     * @brief This function copies the value in member user
     * @param _user New value to be copied in member user
     */
    eProsima_user_DllExport void user(
            const std::string& _user);

    /*!
     * @brief This function moves the value in member user
     * @param _user New value to be moved in member user
     */
    eProsima_user_DllExport void user(
            std::string&& _user);

    /*!
     * @brief This function returns a constant reference to member user
     * @return Constant reference to member user
     */
    eProsima_user_DllExport const std::string& user() const;

    /*!
     * @brief This function returns a reference to member user
     * @return Reference to member user
     */
    eProsima_user_DllExport std::string& user();

private:

    DSF::GUID_t m_messageId{0};
    DSF::Timespec m_currentTime;
    MSGTYPE m_msgType{MSGTYPE::CONTROL};
    std::vector<ControlVar> m_vars;
    std::string m_srcNode;
    std::vector<std::string> m_write_tokens;
    std::string m_user;

};
/*!
 * @brief This class represents the structure SubTableRegister defined by the user in the IDL file.
 * @ingroup dsf_define_messages
 */
class SubTableRegister
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport SubTableRegister();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~SubTableRegister();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object SubTableRegister that will be copied.
     */
    eProsima_user_DllExport SubTableRegister(
            const SubTableRegister& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object SubTableRegister that will be copied.
     */
    eProsima_user_DllExport SubTableRegister(
            SubTableRegister&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object SubTableRegister that will be copied.
     */
    eProsima_user_DllExport SubTableRegister& operator =(
            const SubTableRegister& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object SubTableRegister that will be copied.
     */
    eProsima_user_DllExport SubTableRegister& operator =(
            SubTableRegister&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x SubTableRegister object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const SubTableRegister& x) const;

    /*!
     * @brief Comparison operator.
     * @param x SubTableRegister object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const SubTableRegister& x) const;

    /*!
     * @brief This function sets a value in member msgType
     * @param _msgType New value for member msgType
     */
    eProsima_user_DllExport void msgType(
            MSGTYPE _msgType);

    /*!
     * @brief This function returns the value of member msgType
     * @return Value of member msgType
     */
    eProsima_user_DllExport MSGTYPE msgType() const;

    /*!
     * @brief This function returns a reference to member msgType
     * @return Reference to member msgType
     */
    eProsima_user_DllExport MSGTYPE& msgType();


    /*!
     * @brief This function copies the value in member varFreqs
     * @param _varFreqs New value to be copied in member varFreqs
     */
    eProsima_user_DllExport void varFreqs(
            const std::vector<DSF::NamedValue>& _varFreqs);

    /*!
     * @brief This function moves the value in member varFreqs
     * @param _varFreqs New value to be moved in member varFreqs
     */
    eProsima_user_DllExport void varFreqs(
            std::vector<DSF::NamedValue>&& _varFreqs);

    /*!
     * @brief This function returns a constant reference to member varFreqs
     * @return Constant reference to member varFreqs
     */
    eProsima_user_DllExport const std::vector<DSF::NamedValue>& varFreqs() const;

    /*!
     * @brief This function returns a reference to member varFreqs
     * @return Reference to member varFreqs
     */
    eProsima_user_DllExport std::vector<DSF::NamedValue>& varFreqs();


    /*!
     * @brief This function copies the value in member tableName
     * @param _tableName New value to be copied in member tableName
     */
    eProsima_user_DllExport void tableName(
            const std::string& _tableName);

    /*!
     * @brief This function moves the value in member tableName
     * @param _tableName New value to be moved in member tableName
     */
    eProsima_user_DllExport void tableName(
            std::string&& _tableName);

    /*!
     * @brief This function returns a constant reference to member tableName
     * @return Constant reference to member tableName
     */
    eProsima_user_DllExport const std::string& tableName() const;

    /*!
     * @brief This function returns a reference to member tableName
     * @return Reference to member tableName
     */
    eProsima_user_DllExport std::string& tableName();


    /*!
     * @brief This function copies the value in member nodeName
     * @param _nodeName New value to be copied in member nodeName
     */
    eProsima_user_DllExport void nodeName(
            const std::string& _nodeName);

    /*!
     * @brief This function moves the value in member nodeName
     * @param _nodeName New value to be moved in member nodeName
     */
    eProsima_user_DllExport void nodeName(
            std::string&& _nodeName);

    /*!
     * @brief This function returns a constant reference to member nodeName
     * @return Constant reference to member nodeName
     */
    eProsima_user_DllExport const std::string& nodeName() const;

    /*!
     * @brief This function returns a reference to member nodeName
     * @return Reference to member nodeName
     */
    eProsima_user_DllExport std::string& nodeName();


    /*!
     * @brief This function copies the value in member user
     * @param _user New value to be copied in member user
     */
    eProsima_user_DllExport void user(
            const std::string& _user);

    /*!
     * @brief This function moves the value in member user
     * @param _user New value to be moved in member user
     */
    eProsima_user_DllExport void user(
            std::string&& _user);

    /*!
     * @brief This function returns a constant reference to member user
     * @return Constant reference to member user
     */
    eProsima_user_DllExport const std::string& user() const;

    /*!
     * @brief This function returns a reference to member user
     * @return Reference to member user
     */
    eProsima_user_DllExport std::string& user();

private:

    MSGTYPE m_msgType{MSGTYPE::CONTROL};
    std::vector<DSF::NamedValue> m_varFreqs;
    std::string m_tableName;
    std::string m_nodeName;
    std::string m_user;

};
/*!
 * @brief This class represents the structure SubTableUnregister defined by the user in the IDL file.
 * @ingroup dsf_define_messages
 */
class SubTableUnregister
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport SubTableUnregister();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~SubTableUnregister();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object SubTableUnregister that will be copied.
     */
    eProsima_user_DllExport SubTableUnregister(
            const SubTableUnregister& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object SubTableUnregister that will be copied.
     */
    eProsima_user_DllExport SubTableUnregister(
            SubTableUnregister&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object SubTableUnregister that will be copied.
     */
    eProsima_user_DllExport SubTableUnregister& operator =(
            const SubTableUnregister& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object SubTableUnregister that will be copied.
     */
    eProsima_user_DllExport SubTableUnregister& operator =(
            SubTableUnregister&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x SubTableUnregister object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const SubTableUnregister& x) const;

    /*!
     * @brief Comparison operator.
     * @param x SubTableUnregister object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const SubTableUnregister& x) const;

    /*!
     * @brief This function sets a value in member msgType
     * @param _msgType New value for member msgType
     */
    eProsima_user_DllExport void msgType(
            MSGTYPE _msgType);

    /*!
     * @brief This function returns the value of member msgType
     * @return Value of member msgType
     */
    eProsima_user_DllExport MSGTYPE msgType() const;

    /*!
     * @brief This function returns a reference to member msgType
     * @return Reference to member msgType
     */
    eProsima_user_DllExport MSGTYPE& msgType();


    /*!
     * @brief This function copies the value in member varNames
     * @param _varNames New value to be copied in member varNames
     */
    eProsima_user_DllExport void varNames(
            const std::vector<std::string>& _varNames);

    /*!
     * @brief This function moves the value in member varNames
     * @param _varNames New value to be moved in member varNames
     */
    eProsima_user_DllExport void varNames(
            std::vector<std::string>&& _varNames);

    /*!
     * @brief This function returns a constant reference to member varNames
     * @return Constant reference to member varNames
     */
    eProsima_user_DllExport const std::vector<std::string>& varNames() const;

    /*!
     * @brief This function returns a reference to member varNames
     * @return Reference to member varNames
     */
    eProsima_user_DllExport std::vector<std::string>& varNames();


    /*!
     * @brief This function copies the value in member tableName
     * @param _tableName New value to be copied in member tableName
     */
    eProsima_user_DllExport void tableName(
            const std::string& _tableName);

    /*!
     * @brief This function moves the value in member tableName
     * @param _tableName New value to be moved in member tableName
     */
    eProsima_user_DllExport void tableName(
            std::string&& _tableName);

    /*!
     * @brief This function returns a constant reference to member tableName
     * @return Constant reference to member tableName
     */
    eProsima_user_DllExport const std::string& tableName() const;

    /*!
     * @brief This function returns a reference to member tableName
     * @return Reference to member tableName
     */
    eProsima_user_DllExport std::string& tableName();


    /*!
     * @brief This function copies the value in member nodeName
     * @param _nodeName New value to be copied in member nodeName
     */
    eProsima_user_DllExport void nodeName(
            const std::string& _nodeName);

    /*!
     * @brief This function moves the value in member nodeName
     * @param _nodeName New value to be moved in member nodeName
     */
    eProsima_user_DllExport void nodeName(
            std::string&& _nodeName);

    /*!
     * @brief This function returns a constant reference to member nodeName
     * @return Constant reference to member nodeName
     */
    eProsima_user_DllExport const std::string& nodeName() const;

    /*!
     * @brief This function returns a reference to member nodeName
     * @return Reference to member nodeName
     */
    eProsima_user_DllExport std::string& nodeName();


    /*!
     * @brief This function copies the value in member user
     * @param _user New value to be copied in member user
     */
    eProsima_user_DllExport void user(
            const std::string& _user);

    /*!
     * @brief This function moves the value in member user
     * @param _user New value to be moved in member user
     */
    eProsima_user_DllExport void user(
            std::string&& _user);

    /*!
     * @brief This function returns a constant reference to member user
     * @return Constant reference to member user
     */
    eProsima_user_DllExport const std::string& user() const;

    /*!
     * @brief This function returns a reference to member user
     * @return Reference to member user
     */
    eProsima_user_DllExport std::string& user();

private:

    MSGTYPE m_msgType{MSGTYPE::CONTROL};
    std::vector<std::string> m_varNames;
    std::string m_tableName;
    std::string m_nodeName;
    std::string m_user;

};
/*!
 * @brief This class represents the structure Alarm defined by the user in the IDL file.
 * @ingroup dsf_define_messages
 */
class Alarm : public Event
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport Alarm();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~Alarm();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object Alarm that will be copied.
     */
    eProsima_user_DllExport Alarm(
            const Alarm& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object Alarm that will be copied.
     */
    eProsima_user_DllExport Alarm(
            Alarm&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object Alarm that will be copied.
     */
    eProsima_user_DllExport Alarm& operator =(
            const Alarm& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object Alarm that will be copied.
     */
    eProsima_user_DllExport Alarm& operator =(
            Alarm&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x Alarm object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const Alarm& x) const;

    /*!
     * @brief Comparison operator.
     * @param x Alarm object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const Alarm& x) const;

    /*!
     * @brief This function sets a value in member priority
     * @param _priority New value for member priority
     */
    eProsima_user_DllExport void priority(
            uint8_t _priority);

    /*!
     * @brief This function returns the value of member priority
     * @return Value of member priority
     */
    eProsima_user_DllExport uint8_t priority() const;

    /*!
     * @brief This function returns a reference to member priority
     * @return Reference to member priority
     */
    eProsima_user_DllExport uint8_t& priority();


    /*!
     * @brief This function sets a value in member status
     * @param _status New value for member status
     */
    eProsima_user_DllExport void status(
            uint8_t _status);

    /*!
     * @brief This function returns the value of member status
     * @return Value of member status
     */
    eProsima_user_DllExport uint8_t status() const;

    /*!
     * @brief This function returns a reference to member status
     * @return Reference to member status
     */
    eProsima_user_DllExport uint8_t& status();


    /*!
     * @brief This function copies the value in member tmConfirm
     * @param _tmConfirm New value to be copied in member tmConfirm
     */
    eProsima_user_DllExport void tmConfirm(
            const BaoSky::Cdr::optional<DSF::Timespec>& _tmConfirm);

    /*!
     * @brief This function moves the value in member tmConfirm
     * @param _tmConfirm New value to be moved in member tmConfirm
     */
    eProsima_user_DllExport void tmConfirm(
            BaoSky::Cdr::optional<DSF::Timespec>&& _tmConfirm);

    /*!
     * @brief This function returns a constant reference to member tmConfirm
     * @return Constant reference to member tmConfirm
     */
    eProsima_user_DllExport const BaoSky::Cdr::optional<DSF::Timespec>& tmConfirm() const;

    /*!
     * @brief This function returns a reference to member tmConfirm
     * @return Reference to member tmConfirm
     */
    eProsima_user_DllExport BaoSky::Cdr::optional<DSF::Timespec>& tmConfirm();


    /*!
     * @brief This function copies the value in member confirmPerson
     * @param _confirmPerson New value to be copied in member confirmPerson
     */
    eProsima_user_DllExport void confirmPerson(
            const BaoSky::Cdr::optional<std::string>& _confirmPerson);

    /*!
     * @brief This function moves the value in member confirmPerson
     * @param _confirmPerson New value to be moved in member confirmPerson
     */
    eProsima_user_DllExport void confirmPerson(
            BaoSky::Cdr::optional<std::string>&& _confirmPerson);

    /*!
     * @brief This function returns a constant reference to member confirmPerson
     * @return Constant reference to member confirmPerson
     */
    eProsima_user_DllExport const BaoSky::Cdr::optional<std::string>& confirmPerson() const;

    /*!
     * @brief This function returns a reference to member confirmPerson
     * @return Reference to member confirmPerson
     */
    eProsima_user_DllExport BaoSky::Cdr::optional<std::string>& confirmPerson();


    /*!
     * @brief This function copies the value in member tmRecovery
     * @param _tmRecovery New value to be copied in member tmRecovery
     */
    eProsima_user_DllExport void tmRecovery(
            const BaoSky::Cdr::optional<DSF::Timespec>& _tmRecovery);

    /*!
     * @brief This function moves the value in member tmRecovery
     * @param _tmRecovery New value to be moved in member tmRecovery
     */
    eProsima_user_DllExport void tmRecovery(
            BaoSky::Cdr::optional<DSF::Timespec>&& _tmRecovery);

    /*!
     * @brief This function returns a constant reference to member tmRecovery
     * @return Constant reference to member tmRecovery
     */
    eProsima_user_DllExport const BaoSky::Cdr::optional<DSF::Timespec>& tmRecovery() const;

    /*!
     * @brief This function returns a reference to member tmRecovery
     * @return Reference to member tmRecovery
     */
    eProsima_user_DllExport BaoSky::Cdr::optional<DSF::Timespec>& tmRecovery();


    /*!
     * @brief This function copies the value in member recoveryNamedValue
     * @param _recoveryNamedValue New value to be copied in member recoveryNamedValue
     */
    eProsima_user_DllExport void recoveryNamedValue(
            const BaoSky::Cdr::optional<std::string>& _recoveryNamedValue);

    /*!
     * @brief This function moves the value in member recoveryNamedValue
     * @param _recoveryNamedValue New value to be moved in member recoveryNamedValue
     */
    eProsima_user_DllExport void recoveryNamedValue(
            BaoSky::Cdr::optional<std::string>&& _recoveryNamedValue);

    /*!
     * @brief This function returns a constant reference to member recoveryNamedValue
     * @return Constant reference to member recoveryNamedValue
     */
    eProsima_user_DllExport const BaoSky::Cdr::optional<std::string>& recoveryNamedValue() const;

    /*!
     * @brief This function returns a reference to member recoveryNamedValue
     * @return Reference to member recoveryNamedValue
     */
    eProsima_user_DllExport BaoSky::Cdr::optional<std::string>& recoveryNamedValue();

private:

    uint8_t m_priority{1};
    uint8_t m_status{0};
    BaoSky::Cdr::optional<DSF::Timespec> m_tmConfirm;
    BaoSky::Cdr::optional<std::string> m_confirmPerson;
    BaoSky::Cdr::optional<DSF::Timespec> m_tmRecovery;
    BaoSky::Cdr::optional<std::string> m_recoveryNamedValue;

};
/*!
 * @brief This class represents the enumeration CommandResponseRetcode defined by the user in the IDL file.
 * @ingroup dsf_define_messages
 */
enum CommandResponseRetcode : uint32_t
{
    OK_RETCODE,
    ERROR_RETCODE
};
/*!
 * @brief This class represents the structure NamedRetcode defined by the user in the IDL file.
 * @ingroup dsf_define_messages
 */
class NamedRetcode
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport NamedRetcode();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~NamedRetcode();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object NamedRetcode that will be copied.
     */
    eProsima_user_DllExport NamedRetcode(
            const NamedRetcode& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object NamedRetcode that will be copied.
     */
    eProsima_user_DllExport NamedRetcode(
            NamedRetcode&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object NamedRetcode that will be copied.
     */
    eProsima_user_DllExport NamedRetcode& operator =(
            const NamedRetcode& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object NamedRetcode that will be copied.
     */
    eProsima_user_DllExport NamedRetcode& operator =(
            NamedRetcode&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x NamedRetcode object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const NamedRetcode& x) const;

    /*!
     * @brief Comparison operator.
     * @param x NamedRetcode object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const NamedRetcode& x) const;

    /*!
     * @brief This function copies the value in member nodeName
     * @param _nodeName New value to be copied in member nodeName
     */
    eProsima_user_DllExport void nodeName(
            const std::string& _nodeName);

    /*!
     * @brief This function moves the value in member nodeName
     * @param _nodeName New value to be moved in member nodeName
     */
    eProsima_user_DllExport void nodeName(
            std::string&& _nodeName);

    /*!
     * @brief This function returns a constant reference to member nodeName
     * @return Constant reference to member nodeName
     */
    eProsima_user_DllExport const std::string& nodeName() const;

    /*!
     * @brief This function returns a reference to member nodeName
     * @return Reference to member nodeName
     */
    eProsima_user_DllExport std::string& nodeName();


    /*!
     * @brief This function copies the value in member name
     * @param _name New value to be copied in member name
     */
    eProsima_user_DllExport void name(
            const std::string& _name);

    /*!
     * @brief This function moves the value in member name
     * @param _name New value to be moved in member name
     */
    eProsima_user_DllExport void name(
            std::string&& _name);

    /*!
     * @brief This function returns a constant reference to member name
     * @return Constant reference to member name
     */
    eProsima_user_DllExport const std::string& name() const;

    /*!
     * @brief This function returns a reference to member name
     * @return Reference to member name
     */
    eProsima_user_DllExport std::string& name();


    /*!
     * @brief This function sets a value in member retcode
     * @param _retcode New value for member retcode
     */
    eProsima_user_DllExport void retcode(
            CommandResponseRetcode _retcode);

    /*!
     * @brief This function returns the value of member retcode
     * @return Value of member retcode
     */
    eProsima_user_DllExport CommandResponseRetcode retcode() const;

    /*!
     * @brief This function returns a reference to member retcode
     * @return Reference to member retcode
     */
    eProsima_user_DllExport CommandResponseRetcode& retcode();


    /*!
     * @brief This function sets a value in member nativeRetcode
     * @param _nativeRetcode New value for member nativeRetcode
     */
    eProsima_user_DllExport void nativeRetcode(
            int32_t _nativeRetcode);

    /*!
     * @brief This function returns the value of member nativeRetcode
     * @return Value of member nativeRetcode
     */
    eProsima_user_DllExport int32_t nativeRetcode() const;

    /*!
     * @brief This function returns a reference to member nativeRetcode
     * @return Reference to member nativeRetcode
     */
    eProsima_user_DllExport int32_t& nativeRetcode();

private:

    std::string m_nodeName;
    std::string m_name;
    CommandResponseRetcode m_retcode{CommandResponseRetcode::OK_RETCODE};
    int32_t m_nativeRetcode{0};

};
/*!
 * @brief This class represents the union CommandRequest defined by the user in the IDL file.
 * @ingroup dsf_define_messages
 */
class CommandRequest
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport CommandRequest();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~CommandRequest();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object CommandRequest that will be copied.
     */
    eProsima_user_DllExport CommandRequest(
            const CommandRequest& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object CommandRequest that will be copied.
     */
    eProsima_user_DllExport CommandRequest(
            CommandRequest&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object CommandRequest that will be copied.
     */
    eProsima_user_DllExport CommandRequest& operator =(
            const CommandRequest& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object CommandRequest that will be copied.
     */
    eProsima_user_DllExport CommandRequest& operator =(
            CommandRequest&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x CommandRequest object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const CommandRequest& x) const;

    /*!
     * @brief Comparison operator.
     * @param x CommandRequest object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const CommandRequest& x) const;

    /*!
     * @brief This function sets the discriminator value.
     * @param __d New value for the discriminator.
     * @exception eprosima::fastcdr::BadParamException This exception is thrown if the new value doesn't correspond to the selected union member.
     */
    eProsima_user_DllExport void _d(
            MSGTYPE __d);

    /*!
     * @brief This function returns the value of the discriminator.
     * @return Value of the discriminator
     */
    eProsima_user_DllExport MSGTYPE _d() const;

    /*!
     * @brief This function returns a reference to the discriminator.
     * @return Reference to the discriminator.
     */
    eProsima_user_DllExport MSGTYPE& _d();

    /*!
     * @brief This function copies the value in member controlMsg
     * @param _controlMsg New value to be copied in member controlMsg
     */
    eProsima_user_DllExport void controlMsg(
            const Control& _controlMsg);

    /*!
     * @brief This function moves the value in member controlMsg
     * @param _controlMsg New value to be moved in member controlMsg
     */
    eProsima_user_DllExport void controlMsg(
            Control&& _controlMsg);

    /*!
     * @brief This function returns a constant reference to member controlMsg
     * @return Constant reference to member controlMsg
     * @exception eprosima::fastcdr::BadParamException This exception is thrown if the requested union member is not the current selection.
     */
    eProsima_user_DllExport const Control& controlMsg() const;

    /*!
     * @brief This function returns a reference to member controlMsg
     * @return Reference to member controlMsg
     * @exception eprosima::fastcdr::BadParamException This exception is thrown if the requested union member is not the current selection.
     */
    eProsima_user_DllExport Control& controlMsg();


    /*!
     * @brief This function copies the value in member eventMsg
     * @param _eventMsg New value to be copied in member eventMsg
     */
    eProsima_user_DllExport void eventMsg(
            const Event& _eventMsg);

    /*!
     * @brief This function moves the value in member eventMsg
     * @param _eventMsg New value to be moved in member eventMsg
     */
    eProsima_user_DllExport void eventMsg(
            Event&& _eventMsg);

    /*!
     * @brief This function returns a constant reference to member eventMsg
     * @return Constant reference to member eventMsg
     * @exception eprosima::fastcdr::BadParamException This exception is thrown if the requested union member is not the current selection.
     */
    eProsima_user_DllExport const Event& eventMsg() const;

    /*!
     * @brief This function returns a reference to member eventMsg
     * @return Reference to member eventMsg
     * @exception eprosima::fastcdr::BadParamException This exception is thrown if the requested union member is not the current selection.
     */
    eProsima_user_DllExport Event& eventMsg();


    /*!
     * @brief This function copies the value in member alarmMsg
     * @param _alarmMsg New value to be copied in member alarmMsg
     */
    eProsima_user_DllExport void alarmMsg(
            const Alarm& _alarmMsg);

    /*!
     * @brief This function moves the value in member alarmMsg
     * @param _alarmMsg New value to be moved in member alarmMsg
     */
    eProsima_user_DllExport void alarmMsg(
            Alarm&& _alarmMsg);

    /*!
     * @brief This function returns a constant reference to member alarmMsg
     * @return Constant reference to member alarmMsg
     * @exception eprosima::fastcdr::BadParamException This exception is thrown if the requested union member is not the current selection.
     */
    eProsima_user_DllExport const Alarm& alarmMsg() const;

    /*!
     * @brief This function returns a reference to member alarmMsg
     * @return Reference to member alarmMsg
     * @exception eprosima::fastcdr::BadParamException This exception is thrown if the requested union member is not the current selection.
     */
    eProsima_user_DllExport Alarm& alarmMsg();

private:

    MSGTYPE m__d;

    Control m_controlMsg;
    Event m_eventMsg;
    Alarm m_alarmMsg;
};
/*!
 * @brief This class represents the structure CommandResponse defined by the user in the IDL file.
 * @ingroup dsf_define_messages
 */
class CommandResponse
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport CommandResponse();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~CommandResponse();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object CommandResponse that will be copied.
     */
    eProsima_user_DllExport CommandResponse(
            const CommandResponse& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object CommandResponse that will be copied.
     */
    eProsima_user_DllExport CommandResponse(
            CommandResponse&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object CommandResponse that will be copied.
     */
    eProsima_user_DllExport CommandResponse& operator =(
            const CommandResponse& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object CommandResponse that will be copied.
     */
    eProsima_user_DllExport CommandResponse& operator =(
            CommandResponse&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x CommandResponse object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const CommandResponse& x) const;

    /*!
     * @brief Comparison operator.
     * @param x CommandResponse object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const CommandResponse& x) const;

    /*!
     * @brief This function copies the value in member messageId
     * @param _messageId New value to be copied in member messageId
     */
    eProsima_user_DllExport void messageId(
            const DSF::GUID_t& _messageId);

    /*!
     * @brief This function moves the value in member messageId
     * @param _messageId New value to be moved in member messageId
     */
    eProsima_user_DllExport void messageId(
            DSF::GUID_t&& _messageId);

    /*!
     * @brief This function returns a constant reference to member messageId
     * @return Constant reference to member messageId
     */
    eProsima_user_DllExport const DSF::GUID_t& messageId() const;

    /*!
     * @brief This function returns a reference to member messageId
     * @return Reference to member messageId
     */
    eProsima_user_DllExport DSF::GUID_t& messageId();


    /*!
     * @brief This function copies the value in member nodeInfo
     * @param _nodeInfo New value to be copied in member nodeInfo
     */
    eProsima_user_DllExport void nodeInfo(
            const BaoSky::Cdr::optional<DSF::Node::RuntimeInfo>& _nodeInfo);

    /*!
     * @brief This function moves the value in member nodeInfo
     * @param _nodeInfo New value to be moved in member nodeInfo
     */
    eProsima_user_DllExport void nodeInfo(
            BaoSky::Cdr::optional<DSF::Node::RuntimeInfo>&& _nodeInfo);

    /*!
     * @brief This function returns a constant reference to member nodeInfo
     * @return Constant reference to member nodeInfo
     */
    eProsima_user_DllExport const BaoSky::Cdr::optional<DSF::Node::RuntimeInfo>& nodeInfo() const;

    /*!
     * @brief This function returns a reference to member nodeInfo
     * @return Reference to member nodeInfo
     */
    eProsima_user_DllExport BaoSky::Cdr::optional<DSF::Node::RuntimeInfo>& nodeInfo();


    /*!
     * @brief This function sets a value in member retCode
     * @param _retCode New value for member retCode
     */
    eProsima_user_DllExport void retCode(
            CommandResponseRetcode _retCode);

    /*!
     * @brief This function returns the value of member retCode
     * @return Value of member retCode
     */
    eProsima_user_DllExport CommandResponseRetcode retCode() const;

    /*!
     * @brief This function returns a reference to member retCode
     * @return Reference to member retCode
     */
    eProsima_user_DllExport CommandResponseRetcode& retCode();


    /*!
     * @brief This function sets a value in member nativeRetcode
     * @param _nativeRetcode New value for member nativeRetcode
     */
    eProsima_user_DllExport void nativeRetcode(
            int32_t _nativeRetcode);

    /*!
     * @brief This function returns the value of member nativeRetcode
     * @return Value of member nativeRetcode
     */
    eProsima_user_DllExport int32_t nativeRetcode() const;

    /*!
     * @brief This function returns a reference to member nativeRetcode
     * @return Reference to member nativeRetcode
     */
    eProsima_user_DllExport int32_t& nativeRetcode();


    /*!
     * @brief This function copies the value in member statusVMessage
     * @param _statusVMessage New value to be copied in member statusVMessage
     */
    eProsima_user_DllExport void statusVMessage(
            const std::string& _statusVMessage);

    /*!
     * @brief This function moves the value in member statusVMessage
     * @param _statusVMessage New value to be moved in member statusVMessage
     */
    eProsima_user_DllExport void statusVMessage(
            std::string&& _statusVMessage);

    /*!
     * @brief This function returns a constant reference to member statusVMessage
     * @return Constant reference to member statusVMessage
     */
    eProsima_user_DllExport const std::string& statusVMessage() const;

    /*!
     * @brief This function returns a reference to member statusVMessage
     * @return Reference to member statusVMessage
     */
    eProsima_user_DllExport std::string& statusVMessage();


    /*!
     * @brief This function copies the value in member controlRet
     * @param _controlRet New value to be copied in member controlRet
     */
    eProsima_user_DllExport void controlRet(
            const std::vector<NamedRetcode>& _controlRet);

    /*!
     * @brief This function moves the value in member controlRet
     * @param _controlRet New value to be moved in member controlRet
     */
    eProsima_user_DllExport void controlRet(
            std::vector<NamedRetcode>&& _controlRet);

    /*!
     * @brief This function returns a constant reference to member controlRet
     * @return Constant reference to member controlRet
     */
    eProsima_user_DllExport const std::vector<NamedRetcode>& controlRet() const;

    /*!
     * @brief This function returns a reference to member controlRet
     * @return Reference to member controlRet
     */
    eProsima_user_DllExport std::vector<NamedRetcode>& controlRet();

private:

    DSF::GUID_t m_messageId{0};
    BaoSky::Cdr::optional<DSF::Node::RuntimeInfo> m_nodeInfo;
    CommandResponseRetcode m_retCode{CommandResponseRetcode::OK_RETCODE};
    int32_t m_nativeRetcode{0};
    std::string m_statusVMessage;
    std::vector<NamedRetcode> m_controlRet;

};

} // namespace Message

} // namespace DSF

#endif // _TX_DDS_GENERATED_DSF_MESSAGE_DSF_DEFINE_MESSAGES_H_



