// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file dsf_define_modelPubSubTypes.cpp
 * This header file contains the implementation of the serialization functions.
 *
 * This file was generated by the tool fastddsgen.
 */

#include "txdds/RTPS/common/SerializedPayload.h"

#include "txcdr/Cdr.h"
#include "txcdr/CdrSizeCalculator.h"
#include "txcdr/SerializeCdr.h"
#include "txcdr/DeserializeCdr.h"

#include "dsf_define_modelPubSubTypes.h"
#include "dsf_define_modelCdrAux.hpp"

using SerializedPayload = BaoSky::rtps::SerializedPayload;
using InstanceHandle = BaoSky::rtps::InstanceHandle;

namespace DSF {
    namespace Model {
        DefinePubSubType::DefinePubSubType()
        {
            SetName("DSF::Model::Define");
            uint32_t type_size = DSF_Model_Define_max_cdr_typesize;

            type_size += static_cast<uint32_t>(BaoSky::Cdr::Cdr::Alignment(type_size, 4)); /* possible submessage alignment */
            mTypeSize = type_size + 4;

        }

        DefinePubSubType::~DefinePubSubType()
        {
        }

        bool DefinePubSubType::Serialize(
            void *data,
            SerializedPayload *payload)
        {
            Define *p_type = static_cast<Define *>(data);

            // Object that manages the raw buffer.
            BaoSky::Cdr::TXBuffer buffer(reinterpret_cast<char*>(payload->data), payload->max_size);
            // Object that serializes the data.
            BaoSky::Cdr::SerializeCdr ser(buffer, BaoSky::Cdr::Cdr::DEFAULT_ENDIAN, BaoSky::Cdr::CdrVersion::XCDRv1);
            payload->mIdentifier = BaoSky::Cdr::Cdr::DEFAULT_ENDIAN == BaoSky::Cdr::Endianness::BIG_ENDIANNESS ? CDR_BE : CDR_LE;

            // Serialize encapsulation
            ser.SerializeEncapsulation();
            // Serialize the object.
            ser.Serialize(*p_type);

            // Get the serialized length
            payload->length = static_cast<uint32_t>(ser.GetSerializedDataLength());
            return true;
        }

        bool DefinePubSubType::Deserialize(
            SerializedPayload* payload,
            void* data)
        {
            // Convert DATA to pointer of your type
            Define *p_type = static_cast<Define *>(data);

            // Object that manages the raw buffer.
            BaoSky::Cdr::TXBuffer buffer(reinterpret_cast<char*>(payload->data), payload->length);

            // Object that deserializes the data.
            BaoSky::Cdr::DeserializeCdr deser(buffer, BaoSky::Cdr::Cdr::DEFAULT_ENDIAN, BaoSky::Cdr::CdrVersion::XCDRv1);

            // Deserialize encapsulation.
            deser.DeserializeEncapsulation();
            payload->mIdentifier = BaoSky::Cdr::Cdr::DEFAULT_ENDIAN == BaoSky::Cdr::Endianness::BIG_ENDIANNESS ? CDR_BE : CDR_LE;

            // Deserialize the object.
            deser.Deserialize(*p_type);

            return true;
        }

        std::function<uint32_t()> DefinePubSubType::GetSerializedSizeProvider(
            void* data)
        {
            return [data]() -> uint32_t
            {
                BaoSky::Cdr::CdrSizeCalculator calculator(BaoSky::Cdr::CdrVersion::XCDRv1);
                size_t current_alignment{0};
                return static_cast<uint32_t>(calculator.CalculateSerializedSize(
                           *static_cast<Define *>(data), current_alignment)) +
                       4u /*encapsulation*/;
            };
        }

        void* DefinePubSubType::CreateData()
        {
            return reinterpret_cast<void*>(new Define());
        }

        void DefinePubSubType::DeleteData(
            void* data)
        {
            delete(reinterpret_cast<Define *>(data));
        }

        bool DefinePubSubType::GetKey(
            void* data,
            InstanceHandle* handle,
            bool force_md5)
        {
            // TODO key relate
            return true;
        }

        UndefinePubSubType::UndefinePubSubType()
        {
            SetName("DSF::Model::Undefine");
            uint32_t type_size = DSF_Model_Undefine_max_cdr_typesize;

            type_size += static_cast<uint32_t>(BaoSky::Cdr::Cdr::Alignment(type_size, 4)); /* possible submessage alignment */
            mTypeSize = type_size + 4;

        }

        UndefinePubSubType::~UndefinePubSubType()
        {
        }

        bool UndefinePubSubType::Serialize(
            void *data,
            SerializedPayload *payload)
        {
            Undefine *p_type = static_cast<Undefine *>(data);

            // Object that manages the raw buffer.
            BaoSky::Cdr::TXBuffer buffer(reinterpret_cast<char*>(payload->data), payload->max_size);
            // Object that serializes the data.
            BaoSky::Cdr::SerializeCdr ser(buffer, BaoSky::Cdr::Cdr::DEFAULT_ENDIAN, BaoSky::Cdr::CdrVersion::XCDRv1);
            payload->mIdentifier = BaoSky::Cdr::Cdr::DEFAULT_ENDIAN == BaoSky::Cdr::Endianness::BIG_ENDIANNESS ? CDR_BE : CDR_LE;

            // Serialize encapsulation
            ser.SerializeEncapsulation();
            // Serialize the object.
            ser.Serialize(*p_type);

            // Get the serialized length
            payload->length = static_cast<uint32_t>(ser.GetSerializedDataLength());
            return true;
        }

        bool UndefinePubSubType::Deserialize(
            SerializedPayload* payload,
            void* data)
        {
            // Convert DATA to pointer of your type
            Undefine *p_type = static_cast<Undefine *>(data);

            // Object that manages the raw buffer.
            BaoSky::Cdr::TXBuffer buffer(reinterpret_cast<char*>(payload->data), payload->length);

            // Object that deserializes the data.
            BaoSky::Cdr::DeserializeCdr deser(buffer, BaoSky::Cdr::Cdr::DEFAULT_ENDIAN, BaoSky::Cdr::CdrVersion::XCDRv1);

            // Deserialize encapsulation.
            deser.DeserializeEncapsulation();
            payload->mIdentifier = BaoSky::Cdr::Cdr::DEFAULT_ENDIAN == BaoSky::Cdr::Endianness::BIG_ENDIANNESS ? CDR_BE : CDR_LE;

            // Deserialize the object.
            deser.Deserialize(*p_type);

            return true;
        }

        std::function<uint32_t()> UndefinePubSubType::GetSerializedSizeProvider(
            void* data)
        {
            return [data]() -> uint32_t
            {
                BaoSky::Cdr::CdrSizeCalculator calculator(BaoSky::Cdr::CdrVersion::XCDRv1);
                size_t current_alignment{0};
                return static_cast<uint32_t>(calculator.CalculateSerializedSize(
                           *static_cast<Undefine *>(data), current_alignment)) +
                       4u /*encapsulation*/;
            };
        }

        void* UndefinePubSubType::CreateData()
        {
            return reinterpret_cast<void*>(new Undefine());
        }

        void UndefinePubSubType::DeleteData(
            void* data)
        {
            delete(reinterpret_cast<Undefine *>(data));
        }

        bool UndefinePubSubType::GetKey(
            void* data,
            InstanceHandle* handle,
            bool force_md5)
        {
            // TODO key relate
            return true;
        }

        ModelRequestEnvelopePubSubType::ModelRequestEnvelopePubSubType()
        {
            SetName("DSF::Model::ModelRequestEnvelope");
            uint32_t type_size = DSF_Model_ModelRequestEnvelope_max_cdr_typesize;

            type_size += static_cast<uint32_t>(BaoSky::Cdr::Cdr::Alignment(type_size, 4)); /* possible submessage alignment */
            mTypeSize = type_size + 4;

        }

        ModelRequestEnvelopePubSubType::~ModelRequestEnvelopePubSubType()
        {
        }

        bool ModelRequestEnvelopePubSubType::Serialize(
            void *data,
            SerializedPayload *payload)
        {
            ModelRequestEnvelope *p_type = static_cast<ModelRequestEnvelope *>(data);

            // Object that manages the raw buffer.
            BaoSky::Cdr::TXBuffer buffer(reinterpret_cast<char*>(payload->data), payload->max_size);
            // Object that serializes the data.
            BaoSky::Cdr::SerializeCdr ser(buffer, BaoSky::Cdr::Cdr::DEFAULT_ENDIAN, BaoSky::Cdr::CdrVersion::XCDRv1);
            payload->mIdentifier = BaoSky::Cdr::Cdr::DEFAULT_ENDIAN == BaoSky::Cdr::Endianness::BIG_ENDIANNESS ? CDR_BE : CDR_LE;

            // Serialize encapsulation
            ser.SerializeEncapsulation();
            // Serialize the object.
            ser.Serialize(*p_type);

            // Get the serialized length
            payload->length = static_cast<uint32_t>(ser.GetSerializedDataLength());
            return true;
        }

        bool ModelRequestEnvelopePubSubType::Deserialize(
            SerializedPayload* payload,
            void* data)
        {
            // Convert DATA to pointer of your type
            ModelRequestEnvelope *p_type = static_cast<ModelRequestEnvelope *>(data);

            // Object that manages the raw buffer.
            BaoSky::Cdr::TXBuffer buffer(reinterpret_cast<char*>(payload->data), payload->length);

            // Object that deserializes the data.
            BaoSky::Cdr::DeserializeCdr deser(buffer, BaoSky::Cdr::Cdr::DEFAULT_ENDIAN, BaoSky::Cdr::CdrVersion::XCDRv1);

            // Deserialize encapsulation.
            deser.DeserializeEncapsulation();
            payload->mIdentifier = BaoSky::Cdr::Cdr::DEFAULT_ENDIAN == BaoSky::Cdr::Endianness::BIG_ENDIANNESS ? CDR_BE : CDR_LE;

            // Deserialize the object.
            deser.Deserialize(*p_type);

            return true;
        }

        std::function<uint32_t()> ModelRequestEnvelopePubSubType::GetSerializedSizeProvider(
            void* data)
        {
            return [data]() -> uint32_t
            {
                BaoSky::Cdr::CdrSizeCalculator calculator(BaoSky::Cdr::CdrVersion::XCDRv1);
                size_t current_alignment{0};
                return static_cast<uint32_t>(calculator.CalculateSerializedSize(
                           *static_cast<ModelRequestEnvelope *>(data), current_alignment)) +
                       4u /*encapsulation*/;
            };
        }

        void* ModelRequestEnvelopePubSubType::CreateData()
        {
            return reinterpret_cast<void*>(new ModelRequestEnvelope());
        }

        void ModelRequestEnvelopePubSubType::DeleteData(
            void* data)
        {
            delete(reinterpret_cast<ModelRequestEnvelope *>(data));
        }

        bool ModelRequestEnvelopePubSubType::GetKey(
            void* data,
            InstanceHandle* handle,
            bool force_md5)
        {
            // TODO key relate
            return true;
        }


    } //End of namespace Model


} //End of namespace DSF

