// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file FCVCdrAux.hpp
 * This source file contains some definitions of CDR related functions.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef _DDS_GENERATED_FCVCDRAUX_HPP_
#define _DDS_GENERATED_FCVCDRAUX_HPP_

#include "FCV.h"

constexpr uint32_t FCVType_max_cdr_typesize {28UL};
constexpr uint32_t FCVType_max_key_cdr_typesize {0UL};


namespace BaoSky
{
    namespace Cdr
    {

        class Cdr;
        class SerializeCdr;
        class CdrSizeCalculator;

        void SerializeKey(
            BaoSky::Cdr::SerializeCdr &scdr,
            const FCVType &data);

    };
};


#endif // _DDS_GENERATED_FCVCDRAUX_HPP_

