// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file FCVPubSubTypes.cpp
 * This header file contains the implementation of the serialization functions.
 *
 * This file was generated by the tool fastddsgen.
 */

#include "txdds/RTPS/common/SerializedPayload.h"

#include "txcdr/Cdr.h"
#include "txcdr/CdrSizeCalculator.h"
#include "txcdr/SerializeCdr.h"
#include "txcdr/DeserializeCdr.h"

#include "FCVPubSubTypes.h"
#include "FCVCdrAux.hpp"

using SerializedPayload = BaoSky::rtps::SerializedPayload;
using InstanceHandle = BaoSky::rtps::InstanceHandle;

FCVTypePubSubType::FCVTypePubSubType()
{
    SetName("FCVType");
    uint32_t type_size = FCVType_max_cdr_typesize;

    type_size += static_cast<uint32_t>(BaoSky::Cdr::Cdr::Alignment(type_size, 4)); /* possible submessage alignment */
    mTypeSize = type_size + 4;

    mIsGetKeyDefined = false;

    uint32_t keyLength = FCVType_max_key_cdr_typesize > 16 ? FCVType_max_key_cdr_typesize : 16;
    mKeyBuffer = reinterpret_cast<unsigned char*>(malloc(keyLength));
    memset(mKeyBuffer, 0, keyLength);
}

FCVTypePubSubType::~FCVTypePubSubType()
{
    if (mKeyBuffer != nullptr)
    {
        free(mKeyBuffer);
    }
}

bool FCVTypePubSubType::Serialize(
    void *data,
    SerializedPayload *payload)
{
    FCVType *p_type = static_cast<FCVType *>(data);

    // Object that manages the raw buffer.
    BaoSky::Cdr::TXBuffer buffer(reinterpret_cast<char*>(payload->data), payload->max_size);
    // Object that serializes the data.
    BaoSky::Cdr::SerializeCdr ser(buffer, BaoSky::Cdr::Cdr::DEFAULT_ENDIAN, BaoSky::Cdr::CdrVersion::XCDRv1);
    payload->mIdentifier = BaoSky::Cdr::Cdr::DEFAULT_ENDIAN == BaoSky::Cdr::Endianness::BIG_ENDIANNESS ? CDR_BE : CDR_LE;

    // Serialize encapsulation
    ser.SerializeEncapsulation();
    // Serialize the object.
    auto retcode = ser.Serialize(*p_type);

    // Get the serialized length
    payload->length = static_cast<uint32_t>(ser.GetSerializedDataLength());
    return retcode == 0;
}

bool FCVTypePubSubType::Deserialize(
    SerializedPayload* payload,
    void* data)
{
    // Convert DATA to pointer of your type
    FCVType *p_type = static_cast<FCVType *>(data);

    // Object that manages the raw buffer.
    BaoSky::Cdr::TXBuffer buffer(reinterpret_cast<char*>(payload->data), payload->length);

    // Object that deserializes the data.
    BaoSky::Cdr::DeserializeCdr deser(buffer, BaoSky::Cdr::Cdr::DEFAULT_ENDIAN, BaoSky::Cdr::CdrVersion::XCDRv1);

    // Deserialize encapsulation.
    deser.DeserializeEncapsulation();
    payload->mIdentifier = BaoSky::Cdr::Cdr::DEFAULT_ENDIAN == BaoSky::Cdr::Endianness::BIG_ENDIANNESS ? CDR_BE : CDR_LE;

    // Deserialize the object.
    // deser.Deserialize(*p_type);

    return deser.Deserialize(*p_type) == 0;
}

std::function<uint32_t()> FCVTypePubSubType::GetSerializedSizeProvider(
    void* data)
{
    return [data]() -> uint32_t
    {
        BaoSky::Cdr::CdrSizeCalculator calculator(BaoSky::Cdr::CdrVersion::XCDRv1);
        size_t current_alignment{0};
        return static_cast<uint32_t>(calculator.CalculateSerializedSize(
                   *static_cast<FCVType *>(data), current_alignment)) +
               4u /*encapsulation*/;
    };
}

void* FCVTypePubSubType::CreateData()
{
    return reinterpret_cast<void*>(new FCVType());
}

void FCVTypePubSubType::DeleteData(
    void* data)
{
    delete(reinterpret_cast<FCVType *>(data));
}

bool FCVTypePubSubType::GetKey(
    void* data,
    InstanceHandle* handle,
    bool force_md5)
{
    if (!mIsGetKeyDefined)
    {
        return false;
    }

    FCVType* p_type = static_cast<FCVType*>(data);

    // Object that manages the raw buffer.
    BaoSky::Cdr::TXBuffer buffer(reinterpret_cast<char*>(mKeyBuffer), FCVType_max_key_cdr_typesize);

    // Object that serializes the data.
    BaoSky::Cdr::SerializeCdr ser(buffer, BaoSky::Cdr::Endianness::BIG_ENDIANNESS, BaoSky::Cdr::CdrVersion::XCDRv1);
    SerializeKey(ser, *p_type);
    // if (force_md5 || FCVType_max_key_cdr_typesize > 16)
    // {
    //     m_md5.init();
    //     m_md5.update(mKeyBuffer, static_cast<unsigned int>(ser.get_serialized_data_length()));
    //     m_md5.finalize();
    //     for (uint8_t i = 0; i < 16; ++i)
    //     {
    //         handle->mValue[i] = m_md5.digest[i];
    //     }
    // }
    // else
    {
        for (uint8_t i = 0; i < 16; ++i)
        {
            handle->mValue[i] = mKeyBuffer[i];
        }
    }
    return true;
}

