// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file HelloWorldTwoTypeObjectSupport.cxx
 * Source file containing the implementation to register the TypeObject representation of the described types in the IDL file
 *
 * This file was generated by the tool fastddsgen.
 */

#include "HelloWorldTwoTypeObjectSupport.hpp"

#include <mutex>
#include <string>

#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/domain/DomainParticipantFactory.hpp>
#include <fastdds/dds/log/Log.hpp>
#include <fastdds/dds/xtypes/common.hpp>
#include <fastdds/dds/xtypes/type_representation/ITypeObjectRegistry.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObject.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObjectUtils.hpp>

#include "HelloWorldTwo.hpp"


using namespace eprosima::fastdds::dds::xtypes;

// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_DataBase_type_identifier(
        TypeIdentifierPair& type_ids_DataBase)
{

    ReturnCode_t return_code_DataBase {eprosima::fastdds::dds::RETCODE_OK};
    return_code_DataBase =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "DataBase", type_ids_DataBase);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_DataBase)
    {
        StructTypeFlag struct_flags_DataBase = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::APPENDABLE,
                false, false);
        QualifiedTypeName type_name_DataBase = "DataBase";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_DataBase;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_DataBase;
        CompleteTypeDetail detail_DataBase = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_DataBase, ann_custom_DataBase, type_name_DataBase.to_string());
        CompleteStructHeader header_DataBase;
        header_DataBase = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_DataBase);
        CompleteStructMemberSeq member_seq_DataBase;
        {
            TypeIdentifierPair type_ids_baseId;
            ReturnCode_t return_code_baseId {eprosima::fastdds::dds::RETCODE_OK};
            return_code_baseId =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_int32_t", type_ids_baseId);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_baseId)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "baseId Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_baseId = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_baseId = 0x00000000;
            bool common_baseId_ec {false};
            CommonStructMember common_baseId {TypeObjectUtils::build_common_struct_member(member_id_baseId, member_flags_baseId, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_baseId, common_baseId_ec))};
            if (!common_baseId_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure baseId member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_baseId = "baseId";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_baseId;
            ann_custom_DataBase.reset();
            CompleteMemberDetail detail_baseId = TypeObjectUtils::build_complete_member_detail(name_baseId, member_ann_builtin_baseId, ann_custom_DataBase);
            CompleteStructMember member_baseId = TypeObjectUtils::build_complete_struct_member(common_baseId, detail_baseId);
            TypeObjectUtils::add_complete_struct_member(member_seq_DataBase, member_baseId);
        }
        CompleteStructType struct_type_DataBase = TypeObjectUtils::build_complete_struct_type(struct_flags_DataBase, header_DataBase, member_seq_DataBase);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_DataBase, type_name_DataBase.to_string(), type_ids_DataBase))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "DataBase already registered in TypeObjectRegistry for a different type.");
        }
    }
}
// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_ChildData_type_identifier(
        TypeIdentifierPair& type_ids_ChildData)
{

    ReturnCode_t return_code_ChildData {eprosima::fastdds::dds::RETCODE_OK};
    return_code_ChildData =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "ChildData", type_ids_ChildData);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_ChildData)
    {
        StructTypeFlag struct_flags_ChildData = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::APPENDABLE,
                false, false);
        return_code_ChildData =
            eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
            "DataBase", type_ids_ChildData);

        if (return_code_ChildData != eprosima::fastdds::dds::RETCODE_OK)
        {
::register_DataBase_type_identifier(type_ids_ChildData);
        }
        QualifiedTypeName type_name_ChildData = "ChildData";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_ChildData;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_ChildData;
        CompleteTypeDetail detail_ChildData = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_ChildData, ann_custom_ChildData, type_name_ChildData.to_string());
        CompleteStructHeader header_ChildData;
        if (EK_COMPLETE == type_ids_ChildData.type_identifier1()._d())
        {
            header_ChildData = TypeObjectUtils::build_complete_struct_header(type_ids_ChildData.type_identifier1(), detail_ChildData);
        }
        else if (EK_COMPLETE == type_ids_ChildData.type_identifier2()._d())
        {
            header_ChildData = TypeObjectUtils::build_complete_struct_header(type_ids_ChildData.type_identifier2(), detail_ChildData);
        }
        else
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "ChildData Structure: base_type TypeIdentifier registered in TypeObjectRegistry is inconsistent.");
            return;
        }
        CompleteStructMemberSeq member_seq_ChildData;
        {
            TypeIdentifierPair type_ids_childId;
            ReturnCode_t return_code_childId {eprosima::fastdds::dds::RETCODE_OK};
            return_code_childId =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_int32_t", type_ids_childId);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_childId)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "childId Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_childId = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_childId = 0x00000001;
            bool common_childId_ec {false};
            CommonStructMember common_childId {TypeObjectUtils::build_common_struct_member(member_id_childId, member_flags_childId, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_childId, common_childId_ec))};
            if (!common_childId_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure childId member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_childId = "childId";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_childId;
            ann_custom_ChildData.reset();
            CompleteMemberDetail detail_childId = TypeObjectUtils::build_complete_member_detail(name_childId, member_ann_builtin_childId, ann_custom_ChildData);
            CompleteStructMember member_childId = TypeObjectUtils::build_complete_struct_member(common_childId, detail_childId);
            TypeObjectUtils::add_complete_struct_member(member_seq_ChildData, member_childId);
        }
        CompleteStructType struct_type_ChildData = TypeObjectUtils::build_complete_struct_type(struct_flags_ChildData, header_ChildData, member_seq_ChildData);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_ChildData, type_name_ChildData.to_string(), type_ids_ChildData))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "ChildData already registered in TypeObjectRegistry for a different type.");
        }
    }
}
// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_HelloWorldTwo_type_identifier(
        TypeIdentifierPair& type_ids_HelloWorldTwo)
{

    ReturnCode_t return_code_HelloWorldTwo {eprosima::fastdds::dds::RETCODE_OK};
    return_code_HelloWorldTwo =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "HelloWorldTwo", type_ids_HelloWorldTwo);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_HelloWorldTwo)
    {
        StructTypeFlag struct_flags_HelloWorldTwo = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::APPENDABLE,
                false, false);
        return_code_HelloWorldTwo =
            eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
            "DataBase", type_ids_HelloWorldTwo);

        if (return_code_HelloWorldTwo != eprosima::fastdds::dds::RETCODE_OK)
        {
::register_DataBase_type_identifier(type_ids_HelloWorldTwo);
        }
        QualifiedTypeName type_name_HelloWorldTwo = "HelloWorldTwo";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_HelloWorldTwo;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_HelloWorldTwo;
        CompleteTypeDetail detail_HelloWorldTwo = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_HelloWorldTwo, ann_custom_HelloWorldTwo, type_name_HelloWorldTwo.to_string());
        CompleteStructHeader header_HelloWorldTwo;
        if (EK_COMPLETE == type_ids_HelloWorldTwo.type_identifier1()._d())
        {
            header_HelloWorldTwo = TypeObjectUtils::build_complete_struct_header(type_ids_HelloWorldTwo.type_identifier1(), detail_HelloWorldTwo);
        }
        else if (EK_COMPLETE == type_ids_HelloWorldTwo.type_identifier2()._d())
        {
            header_HelloWorldTwo = TypeObjectUtils::build_complete_struct_header(type_ids_HelloWorldTwo.type_identifier2(), detail_HelloWorldTwo);
        }
        else
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "HelloWorldTwo Structure: base_type TypeIdentifier registered in TypeObjectRegistry is inconsistent.");
            return;
        }
        CompleteStructMemberSeq member_seq_HelloWorldTwo;
        {
            TypeIdentifierPair type_ids_index;
            ReturnCode_t return_code_index {eprosima::fastdds::dds::RETCODE_OK};
            return_code_index =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_uint32_t", type_ids_index);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_index)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "index Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_index = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_index = 0x00000001;
            bool common_index_ec {false};
            CommonStructMember common_index {TypeObjectUtils::build_common_struct_member(member_id_index, member_flags_index, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_index, common_index_ec))};
            if (!common_index_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure index member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_index = "index";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_index;
            ann_custom_HelloWorldTwo.reset();
            CompleteMemberDetail detail_index = TypeObjectUtils::build_complete_member_detail(name_index, member_ann_builtin_index, ann_custom_HelloWorldTwo);
            CompleteStructMember member_index = TypeObjectUtils::build_complete_struct_member(common_index, detail_index);
            TypeObjectUtils::add_complete_struct_member(member_seq_HelloWorldTwo, member_index);
        }
        {
            TypeIdentifierPair type_ids_message;
            ReturnCode_t return_code_message {eprosima::fastdds::dds::RETCODE_OK};
            return_code_message =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_string_unbounded", type_ids_message);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_message)
            {
                {
                    SBound bound = 0;
                    StringSTypeDefn string_sdefn = TypeObjectUtils::build_string_s_type_defn(bound);
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_string_type_identifier(string_sdefn,
                            "anonymous_string_unbounded", type_ids_message))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_string_unbounded already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_message = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_message = 0x00000002;
            bool common_message_ec {false};
            CommonStructMember common_message {TypeObjectUtils::build_common_struct_member(member_id_message, member_flags_message, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_message, common_message_ec))};
            if (!common_message_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure message member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_message = "message";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_message;
            ann_custom_HelloWorldTwo.reset();
            CompleteMemberDetail detail_message = TypeObjectUtils::build_complete_member_detail(name_message, member_ann_builtin_message, ann_custom_HelloWorldTwo);
            CompleteStructMember member_message = TypeObjectUtils::build_complete_struct_member(common_message, detail_message);
            TypeObjectUtils::add_complete_struct_member(member_seq_HelloWorldTwo, member_message);
        }
        {
            TypeIdentifierPair type_ids_children;
            ReturnCode_t return_code_children {eprosima::fastdds::dds::RETCODE_OK};
            return_code_children =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_sequence_ChildData_unbounded", type_ids_children);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_children)
            {
                return_code_children =
                    eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                    "ChildData", type_ids_children);

                if (eprosima::fastdds::dds::RETCODE_OK != return_code_children)
                {
                ::register_ChildData_type_identifier(type_ids_children);
                }
                bool element_identifier_anonymous_sequence_ChildData_unbounded_ec {false};
                TypeIdentifier* element_identifier_anonymous_sequence_ChildData_unbounded {new TypeIdentifier(TypeObjectUtils::retrieve_complete_type_identifier(type_ids_children, element_identifier_anonymous_sequence_ChildData_unbounded_ec))};
                if (!element_identifier_anonymous_sequence_ChildData_unbounded_ec)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Sequence element TypeIdentifier inconsistent.");
                    return;
                }
                EquivalenceKind equiv_kind_anonymous_sequence_ChildData_unbounded = EK_COMPLETE;
                if (TK_NONE == type_ids_children.type_identifier2()._d())
                {
                    equiv_kind_anonymous_sequence_ChildData_unbounded = EK_BOTH;
                }
                CollectionElementFlag element_flags_anonymous_sequence_ChildData_unbounded = 0;
                PlainCollectionHeader header_anonymous_sequence_ChildData_unbounded = TypeObjectUtils::build_plain_collection_header(equiv_kind_anonymous_sequence_ChildData_unbounded, element_flags_anonymous_sequence_ChildData_unbounded);
                {
                    SBound bound = 0;
                    PlainSequenceSElemDefn seq_sdefn = TypeObjectUtils::build_plain_sequence_s_elem_defn(header_anonymous_sequence_ChildData_unbounded, bound,
                                eprosima::fastcdr::external<TypeIdentifier>(element_identifier_anonymous_sequence_ChildData_unbounded));
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_sequence_type_identifier(seq_sdefn, "anonymous_sequence_ChildData_unbounded", type_ids_children))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_sequence_ChildData_unbounded already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_children = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_children = 0x00000003;
            bool common_children_ec {false};
            CommonStructMember common_children {TypeObjectUtils::build_common_struct_member(member_id_children, member_flags_children, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_children, common_children_ec))};
            if (!common_children_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure children member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_children = "children";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_children;
            ann_custom_HelloWorldTwo.reset();
            CompleteMemberDetail detail_children = TypeObjectUtils::build_complete_member_detail(name_children, member_ann_builtin_children, ann_custom_HelloWorldTwo);
            CompleteStructMember member_children = TypeObjectUtils::build_complete_struct_member(common_children, detail_children);
            TypeObjectUtils::add_complete_struct_member(member_seq_HelloWorldTwo, member_children);
        }
        CompleteStructType struct_type_HelloWorldTwo = TypeObjectUtils::build_complete_struct_type(struct_flags_HelloWorldTwo, header_HelloWorldTwo, member_seq_HelloWorldTwo);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_HelloWorldTwo, type_name_HelloWorldTwo.to_string(), type_ids_HelloWorldTwo))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "HelloWorldTwo already registered in TypeObjectRegistry for a different type.");
        }
    }
}

