// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file PerformanceTest.cpp
 * This source file contains the implementation of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "PerformanceTest.h"

#include "txcdr/Cdr.h"

#include <utility>


namespace PerformanceTest {

TestMessage::TestMessage()
{
}

TestMessage::~TestMessage()
{
}

TestMessage::TestMessage(
        const TestMessage& x)
{
    m_seq_num = x.m_seq_num;
    m_timestamp = x.m_timestamp;
    m_message_type = x.m_message_type;
    m_payload = x.m_payload;
}

TestMessage::TestMessage(
        TestMessage&& x) noexcept
{
    m_seq_num = x.m_seq_num;
    m_timestamp = x.m_timestamp;
    m_message_type = std::move(x.m_message_type);
    m_payload = std::move(x.m_payload);
}

TestMessage& TestMessage::operator =(
        const TestMessage& x)
{

    m_seq_num = x.m_seq_num;
    m_timestamp = x.m_timestamp;
    m_message_type = x.m_message_type;
    m_payload = x.m_payload;
    return *this;
}

TestMessage& TestMessage::operator =(
        TestMessage&& x) noexcept
{

    m_seq_num = x.m_seq_num;
    m_timestamp = x.m_timestamp;
    m_message_type = std::move(x.m_message_type);
    m_payload = std::move(x.m_payload);
    return *this;
}

bool TestMessage::operator ==(
        const TestMessage& x) const
{
    return (m_seq_num == x.m_seq_num &&
           m_timestamp == x.m_timestamp &&
           m_message_type == x.m_message_type &&
           m_payload == x.m_payload);
}

bool TestMessage::operator !=(
        const TestMessage& x) const
{
    return !(*this == x);
}

/*!
 * @brief This function sets a value in member seq_num
 * @param _seq_num New value for member seq_num
 */
void TestMessage::seq_num(
        uint32_t _seq_num)
{
    m_seq_num = _seq_num;
}

/*!
 * @brief This function returns the value of member seq_num
 * @return Value of member seq_num
 */
uint32_t TestMessage::seq_num() const
{
    return m_seq_num;
}

/*!
 * @brief This function returns a reference to member seq_num
 * @return Reference to member seq_num
 */
uint32_t& TestMessage::seq_num()
{
    return m_seq_num;
}


/*!
 * @brief This function sets a value in member timestamp
 * @param _timestamp New value for member timestamp
 */
void TestMessage::timestamp(
        uint64_t _timestamp)
{
    m_timestamp = _timestamp;
}

/*!
 * @brief This function returns the value of member timestamp
 * @return Value of member timestamp
 */
uint64_t TestMessage::timestamp() const
{
    return m_timestamp;
}

/*!
 * @brief This function returns a reference to member timestamp
 * @return Reference to member timestamp
 */
uint64_t& TestMessage::timestamp()
{
    return m_timestamp;
}


/*!
 * @brief This function copies the value in member message_type
 * @param _message_type New value to be copied in member message_type
 */
void TestMessage::message_type(
        const std::string& _message_type)
{
    m_message_type = _message_type;
}

/*!
 * @brief This function moves the value in member message_type
 * @param _message_type New value to be moved in member message_type
 */
void TestMessage::message_type(
        std::string&& _message_type)
{
    m_message_type = std::move(_message_type);
}

/*!
 * @brief This function returns a constant reference to member message_type
 * @return Constant reference to member message_type
 */
const std::string& TestMessage::message_type() const
{
    return m_message_type;
}

/*!
 * @brief This function returns a reference to member message_type
 * @return Reference to member message_type
 */
std::string& TestMessage::message_type()
{
    return m_message_type;
}


/*!
 * @brief This function copies the value in member payload
 * @param _payload New value to be copied in member payload
 */
void TestMessage::payload(
        const std::vector<uint8_t>& _payload)
{
    m_payload = _payload;
}

/*!
 * @brief This function moves the value in member payload
 * @param _payload New value to be moved in member payload
 */
void TestMessage::payload(
        std::vector<uint8_t>&& _payload)
{
    m_payload = std::move(_payload);
}

/*!
 * @brief This function returns a constant reference to member payload
 * @return Constant reference to member payload
 */
const std::vector<uint8_t>& TestMessage::payload() const
{
    return m_payload;
}

/*!
 * @brief This function returns a reference to member payload
 * @return Reference to member payload
 */
std::vector<uint8_t>& TestMessage::payload()
{
    return m_payload;
}




} // namespace PerformanceTest
// Include auxiliary functions like for serializing/deserializing.
#include "PerformanceTestCdrAux.ipp"

