// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file PerformanceTestPubSubTypes.cpp
 * This header file contains the implementation of the serialization functions.
 *
 * This file was generated by the tool fastddsgen.
 */

#include "txdds/RTPS/common/SerializedPayload.h"

#include "txcdr/Cdr.h"
#include "txcdr/CdrSizeCalculator.h"
#include "txcdr/SerializeCdr.h"
#include "txcdr/DeserializeCdr.h"

#include "PerformanceTestPubSubTypes.h"
#include "PerformanceTestCdrAux.hpp"

using SerializedPayload = BaoSky::rtps::SerializedPayload;
using InstanceHandle = BaoSky::rtps::InstanceHandle;

namespace PerformanceTest {
    TestMessagePubSubType::TestMessagePubSubType()
    {
        SetName("PerformanceTest::TestMessage");
        uint32_t type_size = PerformanceTest_TestMessage_max_cdr_typesize;

        type_size += static_cast<uint32_t>(BaoSky::Cdr::Cdr::Alignment(type_size, 4)); /* possible submessage alignment */
        mTypeSize = type_size + 4;

    }

    TestMessagePubSubType::~TestMessagePubSubType()
    {
    }

    bool TestMessagePubSubType::Serialize(
        void *data,
        SerializedPayload *payload)
    {
        TestMessage *p_type = static_cast<TestMessage *>(data);

        // Object that manages the raw buffer.
        BaoSky::Cdr::TXBuffer buffer(reinterpret_cast<char*>(payload->data), payload->max_size);
        // Object that serializes the data.
        BaoSky::Cdr::SerializeCdr ser(buffer, BaoSky::Cdr::Cdr::DEFAULT_ENDIAN, BaoSky::Cdr::CdrVersion::XCDRv1);
        payload->mIdentifier = BaoSky::Cdr::Cdr::DEFAULT_ENDIAN == BaoSky::Cdr::Endianness::BIG_ENDIANNESS ? CDR_BE : CDR_LE;

        // Serialize encapsulation
        ser.SerializeEncapsulation();
        // Serialize the object.
        ser.Serialize(*p_type);

        // Get the serialized length
        payload->length = static_cast<uint32_t>(ser.GetSerializedDataLength());
        return true;
    }

    bool TestMessagePubSubType::Deserialize(
        SerializedPayload* payload,
        void* data)
    {
        // Convert DATA to pointer of your type
        TestMessage *p_type = static_cast<TestMessage *>(data);

        // Object that manages the raw buffer.
        BaoSky::Cdr::TXBuffer buffer(reinterpret_cast<char*>(payload->data), payload->length);

        // Object that deserializes the data.
        BaoSky::Cdr::DeserializeCdr deser(buffer, BaoSky::Cdr::Cdr::DEFAULT_ENDIAN, BaoSky::Cdr::CdrVersion::XCDRv1);

        // Deserialize encapsulation.
        deser.DeserializeEncapsulation();
        payload->mIdentifier = BaoSky::Cdr::Cdr::DEFAULT_ENDIAN == BaoSky::Cdr::Endianness::BIG_ENDIANNESS ? CDR_BE : CDR_LE;

        // Deserialize the object.
        deser.Deserialize(*p_type);

        return true;
    }

    std::function<uint32_t()> TestMessagePubSubType::GetSerializedSizeProvider(
        void* data)
    {
        return [data]() -> uint32_t
        {
            BaoSky::Cdr::CdrSizeCalculator calculator(BaoSky::Cdr::CdrVersion::XCDRv1);
            size_t current_alignment{0};
            return static_cast<uint32_t>(calculator.CalculateSerializedSize(
                       *static_cast<TestMessage *>(data), current_alignment)) +
                   4u /*encapsulation*/;
        };
    }

    void* TestMessagePubSubType::CreateData()
    {
        return reinterpret_cast<void*>(new TestMessage());
    }

    void TestMessagePubSubType::DeleteData(
        void* data)
    {
        delete(reinterpret_cast<TestMessage *>(data));
    }

    bool TestMessagePubSubType::GetKey(
        void* data,
        InstanceHandle* handle,
        bool force_md5)
    {
        // TODO key relate
        return true;
    }


} //End of namespace PerformanceTest

