// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file PerformanceTestCdrAux.ipp
 * This source file contains some declarations of CDR related functions.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef _DDS_GENERATED_PERFORMANCETEST_PERFORMANCETESTCDRAUX_IPP_
#define _DDS_GENERATED_PERFORMANCETEST_PERFORMANCETESTCDRAUX_IPP_

#include "PerformanceTestCdrAux.hpp"

#include "txcdr/Cdr.h"
#include "txcdr/SerializeCdr.h"
#include "txcdr/DeserializeCdr.h"
#include "txcdr/CdrSizeCalculator.h"
#include "txcdr/MemberId.h"

template<>
eProsima_user_DllExport size_t CalculateSerializedSizeUserDefined(
        BaoSky::Cdr::CdrSizeCalculator& calculator,
        const PerformanceTest::TestMessage& data,
        size_t& current_alignment)
{
    using namespace PerformanceTest;

    static_cast<void>(data);

    BaoSky::Cdr::EncodingAlgorithmFlag previous_encoding = calculator.GetEncoding();
    size_t calculated_size {calculator.BeginCalculateTypeSerializedSize(
                                BaoSky::Cdr::CdrVersion::XCDRv2 == calculator.GetCdrVersion() ?
                                BaoSky::Cdr::EncodingAlgorithmFlag::DELIMIT_CDR2 :
                                BaoSky::Cdr::EncodingAlgorithmFlag::PLAIN_CDR,
                                current_alignment)};


        calculated_size += calculator.CalculateMemberSerializedSize(BaoSky::Cdr::MemberId(0),
                data.seq_num(), current_alignment);

        calculated_size += calculator.CalculateMemberSerializedSize(BaoSky::Cdr::MemberId(1),
                data.timestamp(), current_alignment);

        calculated_size += calculator.CalculateMemberSerializedSize(BaoSky::Cdr::MemberId(2),
                data.message_type(), current_alignment);

        calculated_size += calculator.CalculateMemberSerializedSize(BaoSky::Cdr::MemberId(3),
                data.payload(), current_alignment);


    calculated_size += calculator.EndCalculateTypeSerializedSize(previous_encoding, current_alignment);

    return calculated_size;
}

template<>
eProsima_user_DllExport void SerializeUserDefined(
        BaoSky::Cdr::SerializeCdr& scdr,
        const PerformanceTest::TestMessage& data)
{
    using namespace PerformanceTest;

    scdr.CdrBeginSerializeType();

        scdr.Serialize(BaoSky::Cdr::MemberId(0));
        scdr.Serialize(data.seq_num());

        scdr.Serialize(BaoSky::Cdr::MemberId(1));
        scdr.Serialize(data.timestamp());

        scdr.Serialize(BaoSky::Cdr::MemberId(2));
        scdr.Serialize(data.message_type());

        scdr.Serialize(BaoSky::Cdr::MemberId(3));
        scdr.Serialize(data.payload());

    scdr.CdrEndSerializeType();
}

template<>
eProsima_user_DllExport void DeserializeUserDefined(
        BaoSky::Cdr::DeserializeCdr& dcdr,
        PerformanceTest::TestMessage& data)
{
    dcdr.DeserializeType(BaoSky::Cdr::CdrVersion::XCDRv2 == dcdr.GetCdrVersion() ?
                                BaoSky::Cdr::EncodingAlgorithmFlag::DELIMIT_CDR2 :
                                BaoSky::Cdr::EncodingAlgorithmFlag::PLAIN_CDR,
        [&data](BaoSky::Cdr::DeserializeCdr &dcdr, const uint32_t &mid) -> bool
        {
            bool ret_value = true;
            switch (mid)
            {
                                case 0:
                                        dcdr.Deserialize(data.seq_num());
                                    break;

                                case 1:
                                        dcdr.Deserialize(data.timestamp());
                                    break;

                                case 2:
                                        dcdr.Deserialize(data.message_type());
                                    break;

                                case 3:
                                        dcdr.Deserialize(data.payload());
                                    break;

                default:
                    ret_value = false;
                    break;
            }
            return ret_value;
        });

}

void serialize_key(
        BaoSky::Cdr::SerializeCdr& scdr,
        const PerformanceTest::TestMessage& data)
{
    using namespace PerformanceTest;

    static_cast<void>(scdr);
    static_cast<void>(data);
}




#endif // _DDS_GENERATED_PERFORMANCETEST_PERFORMANCETESTCDRAUX_IPP_

